- src/common/network/NetworkUtils.cpp
- src/common/network/NetworkUtils.h
- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
- src/graph/ExecutionEngine.cpp
- src/graph/GraphFlags.cpp
- src/graph/GraphFlags.h
- src/graph/test/SchemaTest.cpp
- src/graph/test/TestEnv.cpp
- src/kvstore/PartManager.cpp
- src/meta/SchemaManager.cpp
- src/meta/ServerBasedSchemaManager.cpp
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/processors/HBProcessor.h
- src/meta/test/MetaClientTest.cpp
- src/meta/test/MetaHttpHandlerTest.cpp
- src/storage/client/StorageClient.cpp
- src/storage/test/StorageClientTest.cpp
- src/storage/test/StorageHttpHandlerTest.cpp
- src/storage/test/TestUtils.h
1. Force meta client to reuse IOThreadPool outside.
2. Move meta_server_addrs flag outside, so we don't check the flag in MetaClient ctor any more.
3. Implement heartbeat logic.
Subtask of #283
After the repo to be public,  changes could NOT be rebased on the original pr #379 
So Let's use the new one to track it.
> Adjust meta client ctor  && implement heartbeat logic inside.

- src/common/network/NetworkUtils.cpp
- src/common/network/test/NetworkUtilsTest.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
- src/graph/test/TestMain.cpp
- src/interface/storage.thrift
- src/meta/test/MetaClientTest.cpp
- src/meta/test/TestUtils.h
- src/storage/test/StorageClientTest.cpp
- src/storage/test/TestUtils.h
Use ephemeral port to bind on in tests #260
Sometimes you need a program to bind to a port that can't be hard-coded. Generally this is when you want to run several of them in parallel; if they all bind to port a specified port, only one of them can succeed.
so use system unused ephemeral port 
This will close #260
> Use ephemeral port to bind on in tests

- src/meta/CMakeLists.txt
This is an adhoc fix on build failures due to module dependencies. For a thorough solution, please refer to this issue #406
> Make schema_obj depend on meta_thrift_obj explicitly

- src/common/base/Cord.cpp
- src/common/filter/Expressions.h
- src/common/fs/FileUtils.cpp
- src/common/network/NetworkUtils.cpp
- src/common/network/test/NetworkUtilsBenchmark.cpp
- src/graph/DescribeSpaceExecutor.h
- src/graph/DescribeTagExecutor.h
- src/graph/test/GoTest.cpp
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/partsMan/DropSpaceProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/parser/MaintainSentences.cpp
- src/parser/UserSentences.h
- src/raftex/Host.cpp
- src/raftex/test/RaftexTestBase.cpp
- src/storage/QueryStatsProcessor.cpp
One thing to remember: calling `std::move` on local objects(when `return`) and temporary objects(when passed as arguments) will make the copy elision optimization impossible.
> Some minor fixes

- CMakeLists.txt
- src/daemons/CMakeLists.txt
- src/graph/CMakeLists.txt
- src/graph/test/CMakeLists.txt
- src/meta/CMakeLists.txt
- src/meta/test/CMakeLists.txt
- src/storage/CMakeLists.txt
- src/storage/test/CMakeLists.txt
- src/storage/test/StorageHttpHandlerTest.cpp
I found the problem when i write a UT with no dependency of proxygen lib.  
It is introduced by #210 and #395  
Please pay more attention to your dependency.  @steppenwolfyuetong @darionyaphet
> Clean up dependency on proxygen libs

- src/graph/DescribeEdgeExecutor.cpp
- src/graph/DescribeSpaceExecutor.cpp
- src/graph/DescribeTagExecutor.cpp
- src/graph/UseExecutor.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/partsMan/GetSpaceProcessor.cpp
- src/meta/processors/schemaMan/GetEdgeProcessor.cpp
- src/meta/processors/schemaMan/GetTagProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/meta/test/ProcessorTest.cpp
1、Describe Tag and Edge from metad
2、"Use space"  get spaceId from metad
3、Modify DescribeSpace
> All Describe command unified get data from metad

- src/meta/SchemaManager.h
- src/meta/ServerBasedSchemaManager.cpp
- src/meta/ServerBasedSchemaManager.h
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/test/MetaClientTest.cpp
- src/storage/CompactionFilter.h
- src/storage/test/AdHocSchemaManager.cpp
- src/storage/test/AdHocSchemaManager.h
Now compaction will remove the data without schema.  And the process maybe happened before meta client cache loaded. 
So we should distinguish whether the schema is not existed or not ready?
> Fix bug about accessing meta client local cache before it is ready

- src/common/base/Status.h
- src/common/base/ThriftTypes.h
- src/daemons/CMakeLists.txt
- src/graph/PermissionManager.h
- src/interface/common.thrift
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/MetaServiceUtils.cpp
- src/meta/MetaServiceUtils.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/partsMan/DropSpaceProcessor.cpp
- src/meta/processors/usersMan/AuthenticationProcessor.cpp
- src/meta/processors/usersMan/AuthenticationProcessor.h
- src/meta/test/AuthProcessorTest.cpp
- src/meta/test/CMakeLists.txt
- src/meta/test/TestUtils.h
Instead of PR #257 .
1. Addressed comments.
2. storage the data using dataman .
> User manager in meta

- src/graph/PipeExecutor.cpp
- src/graph/PipeExecutor.h
- src/graph/TraverseExecutor.h
- src/graph/test/GoTest.cpp
Do prepare after setting onResult_ in PipeExecutor::prepare, or these cases will not work well:
***GO ... | GO ... | GO ...***
***GO ... | (GO ... | GO ...)***
> Do prepare after setting onResult_ in PipeExecutor::prepare

- src/kvstore/Common.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/Part.cpp
std::function has two defects:
1.   It must be copy constructible,  so we can't pass object which is NOT in capture list.
2.  It has problems with const-ness method.
For more information, please refer to https://github.com/facebook/folly/blob/master/folly/Function.h
> Use folly::Function instead of std::function in kvstore callback

- src/common/fs/FileUtils.cpp
- src/common/stats/StatsManager.cpp
- src/common/thread/GenericWorker.cpp
- src/dataman/RowReader.cpp
- src/dataman/RowWriter.cpp
- src/dataman/RowWriter.h
- src/dataman/test/NebulaCodecTest.cpp
- src/graph/InterimResult.cpp
- src/graph/ShowExecutor.cpp
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/kvstore/test/NebulaStoreTest.cpp
- src/meta/NebulaSchemaProvider.cpp
- src/meta/test/ProcessorTest.cpp
- src/meta/test/TestUtils.h
- src/parser/Clauses.h
- src/storage/client/StorageClient.h
- src/storage/test/QueryBoundTest.cpp
- src/storage/test/QueryStatsTest.cpp
- src/storage/test/QueryVertexPropsTest.cpp
- src/storage/test/TestUtils.h
1. Changed from `push_back` to `emplace_back`, let avoid unnecessary memory copy/move.
2. Normalize the some codes.
> Collect and modify push_back to emplace_back

- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
- src/common/filter/test/ExpressionTest.cpp
- src/graph/GoExecutor.cpp
- src/graph/InsertEdgeExecutor.cpp
- src/graph/InsertVertexExecutor.cpp
- src/graph/InterimResult.cpp
- src/graph/InterimResult.h
- src/graph/test/YieldTest.cpp
- src/parser/Clauses.cpp
- src/parser/Clauses.h
- src/parser/MutateSentences.cpp
- src/parser/MutateSentences.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/parser/test/ScannerTest.cpp
As title.
Now, you can use function call expression where a vertex id is required, like `INSERT VERTEX player(name, age) VALUES hash("Tim Duncan"): ("Tim Duncan", 42)`
close #563
> Fixed unary minus integer bug and support to take function call as vid

- docs/get-started.md
- docs/nGQL.md
add "build your owner graph" section in get-started.md
> get-started.md add build user's owner graph

- src/common/filter/Expressions.cpp
- src/common/filter/test/ExpressionTest.cpp
- src/graph/CMakeLists.txt
- src/graph/test/CMakeLists.txt
- src/graph/test/DataTest.cpp
- src/graph/test/GoTest.cpp
- src/graph/test/OrderByTest.cpp
- src/graph/test/SchemaTest.cpp
- src/graph/test/TraverseTestBase.h
- src/parser/MutateSentences.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
Delete [] of SRC_REF and DST_REF
Fix insert vertex and edge when tag or edge has the empty prop
> Fix empty prop of tag and edge

- CMakeLists.txt
As title.
For more details, please refer to [here](https://github.com/ccache/ccache)
> To speed up compiling with ccache

- src/kvstore/plugins/hbase/HBaseStore.cpp
- src/parser/CMakeLists.txt
- third-party/folly/build.sh
- third-party/rocksdb/build.sh
> To be able to build under GCC 9.1

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
The pr fix four bugs: 
1.  When commit logs, we hope it is under protection by raftLock_.  
2.  Write WALs should be protected by raftLock_.
3.  Term maybe changed when committed,  we should handle it. 
4.  When write wal failed, reset replicatingLogs_ to be false.
> Fix bugs in RAFT

- src/meta/processors/admin/Balancer.cpp
> Fixed dangling pointer in Balancer

- src/kvstore/Part.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/LogAppendTest.cpp
- src/kvstore/raftex/test/LogCASTest.cpp
- src/kvstore/raftex/test/LogCommandTest.cpp
- src/kvstore/raftex/test/TestShard.cpp
- src/kvstore/raftex/test/TestShard.h
This pr is to fix the problem that when follower becomes leader,  it will not commit the log with previous term.  As the paper said,  the logic is correct.  But the problem is that as current heart beat implementation, we will not commit anything when received response from followers.  It is incorrect. 
So this pr will use a special empty log to represent heartbeat,   the log will be written into WAL but skipped when committing.   It has no harm to performance because we don't send heartbeat when replicating logs.   And it will force the uncommitted logs to commit when the new leader send heartbeat with it's current term.
> Make heartbeat to be a special empty log

- CMakeLists.txt
Some compilers are built with `-enable-default-pie`. That is no problem generally, but glog is buggy to deal with this when retrieve the backtrace. So we disable pie from our own side.
> To link executables with -no-pie

- src/graph/AssignmentExecutor.cpp
- src/graph/test/CMakeLists.txt
- src/graph/test/GoTest.cpp
- src/parser/parser.yy
* Fixed a **_variable not defined_** bug, which occurs when a variable is assigned from a **PIPE** statement.
* Added sugar syntax to variable reference when the referred column is `id`.
* Eliminated duplicated compiling on some testing source files.
> Fixed bug on variable reference

- src/graph/test/CMakeLists.txt
- src/meta/ActiveHostsMan.cpp
`UpgradedHolder` makes a `RWSpinLock` or `ReadHolder` progress to the `UPGRADED` phase. And `UPGRADED` is an intermediate phase to transit(upgrade) from `READ` to `WRITE`.
> Fixed UpgradedHolder-related race condition in ActiveHostsMan

- src/kvstore/NebulaStore.cpp
Thanks for @wadeliuyi reporting.  The part will be stopped inside removePartition.
> Fix bug about stopping twice for part

- docs/README.md
- docs/get-started.md
Typesetting to make the web pages look more agreeable.
> Formalized release version

- src/daemons/CMakeLists.txt
- src/interface/storage.thrift
- src/meta/CMakeLists.txt
- src/meta/processors/admin/AdminClient.cpp
- src/meta/processors/admin/AdminClient.h
- src/meta/processors/admin/BalanceTask.cpp
- src/meta/test/AdminClientTest.cpp
- src/meta/test/BalanceIntegrationTest.cpp
- src/meta/test/CMakeLists.txt
- src/storage/AdminProcessor.h
- src/storage/StorageServiceHandler.cpp
- src/storage/StorageServiceHandler.h
The PR is based on #516 .
Subtask of #515
> Implement admin client for balancer

- src/common/filter/test/ExpressionTest.cpp
- src/parser/parser.yy
> Fixed recursive unary expression

- cmake/ThriftGenerate.cmake
Since there are target files that will never be generated, the generator always gets invoked.
> Fixed thrift generator

- src/graph/test/TestEnv.cpp
All servers depend on metaClient. 
So release meta client after servers.
> Fix use-after-free problem in UT

- src/meta/processors/admin/BalancePlan.cpp
In balancePlan,  after all tasks finished,  the plan will be destroyed.  
So we should save the plan firstly before tasks invoke to avoid the potential risk.
> Fix use-after-free problem in BalancerPlan

- src/graph/test/TestEnv.cpp
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/test/NebulaStoreTest.cpp
The reason is that go_test/data_test will drop space before exit.  And the procedure of drop space  is update information on meta,  then notify storage server asynchronously.  Maybe meta client receive the notification after the storage server stopped,  so it will crash.
To fix it,  we should cut-off the relationship with metaclient before kvstore clean up parts.  But i still want "drop space "could be invoked on storage server,  so i add sleep to ensure it.
> Fix failed data_test/go_test.

- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/Host.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/test/NebulaStoreTest.cpp
We don't need to hold all requests inside host.  There are two defects:
1.  Catch up data will be slow,  because we have to send request one by one.
2.  More memory  occupied due to the queue.
> Remove requests queue inside Host

- package/make_srpm.sh
- package/nebula.spec
- src/graph/ShowExecutor.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/client/MetaClient.cpp
- src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
- src/meta/processors/schemaMan/CreateTagProcessor.cpp
- src/meta/test/ProcessorTest.cpp
> Fix the same name tag and edge in same space #598

- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
> Eliminate duplicate definitions in PrimaryExpression

- src/kvstore/test/NebulaStoreTest.cpp
sumarry:
fixed coredump for sharing the same iothreadpool in the two
different NebulaStore object.
This crash will only appear if you compiled with addresssanitizer.
> issue #727 crashed by PartsTest in nebula_store_test.

- src/meta/ClusterManager.cpp
- src/meta/ClusterManager.h
When Meta starts, if this is the first time Meta creates a cluster id and at this moment leader change(in kvstore->asyncMultiPut() function), Meta Server start will fail.
> Meta Server init fail when leader change

- docs/deploy-cluster.md
- etc/nebula-storaged.conf.default
- scripts/services.sh
- src/graph/GraphFlags.cpp
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/test/LearnerTest.cpp
- src/kvstore/raftex/test/LogAppendTest.cpp
- src/kvstore/raftex/test/LogCASTest.cpp
- src/kvstore/raftex/test/LogCommandTest.cpp
- src/kvstore/raftex/test/RaftCase.cpp
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/kvstore/test/NebulaStoreTest.cpp
- src/meta/ClusterManager.cpp
- src/storage/test/QueryBoundBenchmark.cpp
In this PR, I append a document to description cluster deployment and config arguments.
> [Doc] Cluster deployment

- src/graph/GoExecutor.cpp
This time only temporarily avoided this crash,
In issue #192, I will solve this problem for better.
> Issue 756 fixed the graphd crashed.

- src/daemons/GraphDaemon.cpp
- src/graph/ExecutionEngine.cpp
- src/graph/GraphService.cpp
- src/graph/GraphService.h
- src/graph/test/TestUtils.h
> Fixed crash problem due to meta not ready

- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/partsMan/CreateSpaceProcessor.cpp
- src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
- src/meta/processors/schemaMan/CreateTagProcessor.cpp
- src/meta/processors/usersMan/AuthenticationProcessor.cpp
For now, since we support multiple replica of meta server, we may fail when write into kvstore with error code `E_LEADER_CHANGED`. Instead of crash, we check and return corresponding error code.
close #817
> Fix crash problem when create space in multiple replica meta env

- src/kvstore/wal/FileBasedWal.cpp
Or there will be possible data loss / corruption depending on the exact way how data is interpreted and handled. `close` doesn't mean automatic `fsync`.
> fsync upon closing WAL files

- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/test/MetaClientTest.cpp
Basic retry for meta client, when retry times exceed limits, handle the final response.
close #733
> Add retry for meta client

- .gitignore
- docs/deploy-cluster.md
- docs/manual-CN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md
- docs/manual-EN/statement-syntax/data-administration-statements/configuration-statements/variables-syntax.md
- src/graph/test/ConfigTest.cpp
- src/meta/GflagsManager.cpp
- src/parser/test/ParserTest.cpp
- Fix variables syntax document. close #845 
- Replace `load_config_interval_secs` with `load_data_interval_secs` in Test
- Cleanup gflags declaration about `load_config_interval_secs`
- Ignore [ccls](https://github.com/MaskRay/ccls) configuration files
> Cleanup load config interval secs

- package/nebula.spec
- share/CMakeLists.txt
- share/resources/completion.json
- share/resources/gflags.json
- src/graph/CMakeLists.txt
- src/graph/ExecutionEngine.cpp
- src/graph/test/ConfigTest.cpp
- src/interface/meta.thrift
- src/kvstore/plugins/hbase/test/CMakeLists.txt
- src/kvstore/test/CMakeLists.txt
- src/meta/CMakeLists.txt
- src/meta/ClientBasedGflagsManager.cpp
- src/meta/ClientBasedGflagsManager.h
- src/meta/GflagsManager.cpp
- src/meta/GflagsManager.h
- src/meta/KVBasedGflagsManager.cpp
- src/meta/KVBasedGflagsManager.h
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/test/CMakeLists.txt
- src/meta/test/ConfigManTest.cpp
- src/storage/StorageServer.cpp
- src/storage/test/CMakeLists.txt
- src/tools/storage-perf/CMakeLists.txt
1. Let meta client retry to register configs to meta server.
2. Add `gflags.json` to avoid hard code config mode, and all default config mode is `IMMUTABLE`.
3. Add related command in complete.json
close #780
> Fix graph failed to register config to meta.

- src/kvstore/CompactionFilter.h
- src/kvstore/plugins/hbase/test/TestUtils.h
- src/kvstore/wal/FileBasedWal.cpp
- src/meta/SchemaManager.cpp
- src/storage/CompactionFilter.h
- src/storage/StorageServer.cpp
- src/storage/test/TestUtils.h
Construct objects with smart pointer **make** function rather than `new` way.
references:
- [Quick Q: Differences between std::make_unique and std::unique_ptr with new](https://isocpp.org/blog/2019/06/quick-q-differences-between-stdmake-unique-and-stdunique-ptr-with-new)
> Use smart pointer make function to construct objects

- CMakeLists.txt
As title. 
Now we can run tests for a specific sub-directory, e.g. `ctest -L common` or `ctest -L 'kvstore|storage'`
> Group unit tests by directory

- src/common/base/Cord.cpp
- src/common/base/test/CordTest.cpp
FYI. There seems a bug in STL, that `std::string::append(nullptr, 1024)` won't crash if it doesn't have enough capacity, instead the string will be expanded(like resize). But if we use the old CXX ABI, the program will crash.
> Check if empty in Cord before serializing

- CMakeLists.txt
- cmake/FindPCHSupport.cmake
- cmake/ThriftGenerate.cmake
- src/common/base/CMakeLists.txt
- src/common/http/CMakeLists.txt
- src/graph/CMakeLists.txt
- src/meta/CMakeLists.txt
- src/parser/CMakeLists.txt
At compile time, we actually depend on the _**codegen**_ of the thrift files, but no need to _**compile**_ the generated files first.
With this PR, the overall build time could be reduced by nearly 30% in a 56 processors environment.
> Improved build concurrency

- CMakeLists.txt
Third party memory allocators like jemalloc and tcmalloc don't work well along with ASAN.
> Disabled linking against jemalloc when built with ASAN

- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
- src/common/filter/test/ExpressionTest.cpp
Close #530.
The **boost::variant** will not compare the content if the type do not match. So we should do implicit type casting.
> Do implicit type casting in relational expression.

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- docker/Dockerfile
- docker/Dockerfile.console
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/README.md
- docker/docker-compose.yaml
- Use github actions to build nebula service docker images and push them to docker hub at 2am every day night
- Fix docker-compose yaml and usage in readme
- Store nebula Dockerfiles in `docker` subdirectory rather than `vesoft-inc/nebula-docker-compose` repo
> Add docker image building workflow

- cmake/ThriftGenerate.cmake
The default configuration of _**thrift_import**_ is out of date. It would not work well. So I replace it with a manual configuration.
> Use manual configuration when generate go source code.

- .github/workflows/ci.yaml
- src/common/network/NetworkUtils.cpp
- src/common/network/NetworkUtils.h
- src/common/stats/test/CMakeLists.txt
- src/common/stats/test/StatsManagerCrossLevelTest.cpp
- src/common/stats/test/StatsManagerRateTest.cpp
- src/common/stats/test/StatsManagerTest.cpp
- src/meta/test/MetaHttpDownloadHandlerTest.cpp
- src/meta/test/MetaHttpIngestHandlerTest.cpp
- src/storage/AdminProcessor.h
This patch reduces the chances of listen port conflicts, so that we can run unit tests concurrently, i.e `ctest --output-on-failure -jN`. By doing this, the duration of unit testing could be reduced to 2 minutes from 12.
> Try to introduce concurrency to unit testing

- src/common/base/NebulaKeyUtils.cpp
- src/common/base/NebulaKeyUtils.h
`Expression::kUUID` shadows `NebulaKeyType::kUUID`.
> Fixed compile warnings about name shadowing

- docs/manual-EN/statement-syntax/data-definition-statements/show-syntax.md
- src/graph/ShowExecutor.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/processors/admin/AdminClient.cpp
- src/meta/processors/admin/Balancer.cpp
- src/meta/processors/partsMan/ListHostsProcessor.cpp
- src/meta/processors/partsMan/ListHostsProcessor.h
Show space name instead of space id in leader/partition distribution of `show hosts`. The screenshot of `show hosts` looks as follows:
close #909 
close #925
> Show space name in leader/part distribution of show hosts

- package/nebula.spec
- src/kvstore/raftex/RaftPart.cpp
- src/storage/client/StorageClient.inl
- src/tools/simple-kv-verify/SimpleKVVerifyTool.cpp
1. We only handle response from one host previously. Actually, we need to check key-value pairs from responses of all hosts.
2. During balance data, sometimes the partition is not on a hosts anymore, we need to invalidate leader info in client.
> update KVVerifyTool, support get/put kv pairs from multiple storage instance

- src/graph/DeleteVertexExecutor.cpp
- src/graph/test/DeleteVertexTest.cpp
* before: deleting a vertex without edges will cause the following exception
```
#0  0x0000000001a28d47 in nebula::storage::StorageRpcResponse<nebula::storage::cpp2::ExecResponse>::completeness (this=0x7f390db69148) at /export/nebula/src/storage/client/StorageClient.h:53
53	        return (totalReqsSent_ - failedReqs_) * 100 / totalReqsSent_;
```
> fix a bug in DeleteVertexExecutor

- src/common/filter/FunctionManager.cpp
cause: `folly::Random::rand32()` is unsigned.
> Fixed sign of rand32()

- src/common/filter/FunctionManager.cpp
Crashed due to out-of-range accessing.
> Fixed crash in builtin function right()

- CMakeLists.txt
- build_dep.sh
- docs/how-to-build.md
- docs/manual-CN/how-to-build.md
Now the third-party includes the build tools, such as gcc cmake automake ……
We package them into a rpm/deb file. Users only execute the /nebula/build_dep.sh, the dependencies will auto-download and install, and the user can easy to build! Please read the detailed procedures [how_to_build](https://github.com/vesoft-inc/nebula/blob/master/docs/how-to-build.md)
- The supported system
- Fedora29, 30
- Centos6.5, Centos7.0~7.6
- Ubuntu16.04, 18.04
- If you want to change the rocksdb, you can use it
```
cmake -DNEBULA_OTHER_ROOT=$YOUR_ROCKSDB_ROOT ..
```
close #976
> Recompile the new third-party library

- src/graph/Executor.cpp
- src/graph/SequentialExecutor.cpp
Fixed an issue that encountered an unimplemented grammar that could cause a crash.
> Issue #1126 graphd crashed

- src/graph/GoExecutor.cpp
The crash is caused by the use of two meaningless DCHECK in debug mode.
> Issue #1203 fixed the possible crash.

- etc/nebula-metad.conf.default
- etc/nebula-storaged.conf.default
Logging can have a significant impact on performance, and I found that it resulted in at least a 20 times performance degradation in my test cases. When users try nebula, they usually try out the default configurations and know nothing about them, so I think it makes more sense to set the vlog level with 0 by default.
> Change graphd/metad/storaged's vlog level config with default value 0.

- src/kvstore/NebulaStore.cpp
Since nebulaStore and raftpart share a thread pool (bgWorkers_),all raft services should to be stopped before bgWorkers_ was cleaned up.
> Fixed possible data races. 

- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
change v & minloglevel at runtime by http command curl.
It is quit useful for on-site debuging
@Amber1990Zhang help to change to Eng and add to readme.md TOC.
> [doc] add glog curl command 

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/release.yaml
- .gitignore
- ci/scripts/upload-github-release-asset.sh
- package/package.sh
- src/common/fs/test/FileUtilsTest.cpp
- Fix failed UT caused by default timezone of docker container
- Fix GitHub Actions error without enough disk, change build type to `Release`
- Upload packages and sha256sum files to release assets automatically
- Update docker images latest tag
- Change nightly version format of packages
closes #863
> Fix GitHub Actions failure and upload release assets automatically

- docs/manual-EN/1.overview/0.introduction.md
- docs/manual-EN/1.overview/1.concepts/2.nGQL-overview.md
- docs/manual-EN/1.overview/2.quick-start/1.get-started.md
- docs/manual-EN/1.overview/2.quick-start/2.trouble-shooting.md
- docs/manual-EN/1.overview/2.quick-start/4.import-csv-file.md
- docs/manual-EN/1.overview/3.design-and-architecture/1.design-and-architecture.md
- docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
- docs/manual-EN/2.query-language/1.data-types/type-conversion.md
- docs/manual-EN/2.query-language/2.functions-and-operators/comparison-functions-and-operators.md
- docs/manual-EN/2.query-language/2.functions-and-operators/group-by-function.md
- docs/manual-EN/2.query-language/2.functions-and-operators/order-by-function.md
- docs/manual-EN/2.query-language/3.language-structure/identifier-case-sensitivity.md
- docs/manual-EN/2.query-language/3.language-structure/literal-values/numeric-literals.md
- docs/manual-EN/2.query-language/3.language-structure/property-reference.md
- docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/update-vertex-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/yield-syntax.md
- docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
- docs/manual-EN/3.build-develop-and-administration/2.develop-and-interface/kv-interfaces.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/deployment/deploy-cluster.md
- docs/manual-EN/4.contributions/contribute-to-documentation.md
- docs/manual-EN/4.contributions/cpp-coding-style.md
- docs/manual-EN/4.contributions/developer-documentation-style-guide.md
- docs/manual-EN/4.contributions/how-to-contribute.md
- docs/manual-EN/README.md
Fix all heading format in English doc.
The rules of word capitalization in headings:
1.  **Always capitalize the first and last word of a title.**
2. Between the first and last word of a title **Capitalize all words except:**
**Articles:** a, an, the
Coordinate **conjunctions:** and, but, or, nor
**Short prepositions** (three letters or less): as, at, by, for, in, of, on, to, but, cum, mid, off, per, qua, re, up, via -- except when used as adverbs or as an inseparable part of a verb 
When used to form an **infinitive: to**
3. In compounds formed by hyphens, capitalize each part exactly as if they were a separate word.
> [doc]Fix doc headings

- src/common/filter/Expressions.h
- src/graph/CMakeLists.txt
- src/graph/DeleteEdgesExecutor.cpp
- src/graph/DeleteEdgesExecutor.h
- src/graph/Executor.cpp
- src/graph/test/CMakeLists.txt
- src/graph/test/DeleteEdgesTest.cpp
- src/parser/CMakeLists.txt
- src/parser/MutateSentences.cpp
- src/parser/MutateSentences.h
- src/parser/Sentence.h
- src/parser/TraverseSentences.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
* Delete Edges sentence:
```
DELETE EDGE <edge_type> <vid> -> <vid>[@weight] [, <vid> -> <vid>[@weight] ...]
```
> Implement delete edges

- src/common/filter/Expressions.cpp
- src/graph/InsertEdgeExecutor.cpp
- src/graph/InsertVertexExecutor.cpp
- src/meta/client/MetaClient.cpp
- src/storage/client/StorageClient.cpp
- src/storage/client/StorageClient.inl
It is reported by our users.  
After network broken down,  the storaged can't connect to metad some times,   meanwhile the graphd can't connect to storaged either.  Currently,  the client will wait for the response without timeout,  it is unreasonable.   
"timeout" will be helpful to recover from broken connections.
The error logs here is to help our users figure out the problems if failed.
> Add timeout for storage/meta clients and add some error logs

- src/tools/CMakeLists.txt
- src/tools/dump-edges/CMakeLists.txt
- src/tools/dump-edges/DumpEdgesTool.cpp
It will dump the edges (srcId, dstId) in the rocksdb.
Sometimes,  our users want to check the data imported.  
The tool could help them to check all edges imported.  
Of course,  currently it just check the srcId->dstId and the total edges number. 
Usage:  dump_edges --path=/rocksdb_path
> Add dump edges tool

- CMakeLists.txt
Added an option to CMake "NEBULA_CLANG_USED_GCC_TOOLCHAIN" to
specify the path of libstdc++ that Clang will use.
> Fixed an issue with Clang compilation.

- src/graph/GoExecutor.cpp
> Fixed wrong type specifier in format string

- etc/nebula-graphd.conf.production
- etc/nebula-storaged.conf.production
- share/resources/gflags.json
- src/meta/client/MetaClient.cpp
After #1236 merged,  we can't change the schema through update the load_data_interval_secs dynamically.   
It is unfriendly for our users because the schema changes take effect at least heartbeat_interval_secs seconds. 
Now,  we could support to change "heartbeat_interval_secs" on console like before.
> Support update heartbeat_interval_secs dynamically

- CMakeLists.txt
- cmake/FindPCHSupport.cmake
- src/common/time/detail/TscHelper.h
Currently, PCH does not take effect when building in the out-of-source way, since the _.gch_ file, by design, must be at the same directory with the original header. This PR resolves this problem by generating the _.gch_ file in the source tree, i.e. `${CMAKE_CURRENT_SOURCE_DIR}`.
At the mean time, the former implementation of _FindPCHSupport_ does not handle the compile options properly, so that the options used for PCH generation and source compilation are different, which is erroneous. This PR also addresses this issue.
> Fixed use of precompiled header

- cmake/FindPCHSupport.cmake
Currently, the precompiled header's generation only depends on the source header, i.e. _Base.h_. It could not reflect the changes on other configuarations, e.g. CMAKE_BUILD_TYPE. 
To address such an issue, we make the pch depend on the _CMakeCache.txt_ file, which holds all kinds of configurations.
> Make precompiled header depend on CMakeCache.txt

- CMakeLists.txt
- cmake/InstallThirdParty.cmake
Ordinarily, in Linux, Clang will automatically choose to use GCC's toolchain, such as libstdc++, ld, as, etc.
But if the standard GCC is not applicable(e.g. too old), or we just want to use an alternative one, we must tell Clang explicitly with the `--gcc-toolchain` option.
This PR accomplishes this.
Examples to use:
```bash
$ cmake -DCMAKE_C_COMPILER=/path/to/clang 
-DCMAKE_CXX_COMPILER=/path/to/clang++
..
$ cmake -DCMAKE_C_COMPILER=/path/to/clang 
-DCMAKE_CXX_COMPILER=/path/to/clang++
-DNEBULA_CLANG_USE_GCC_TOOLCHAIN=/opt/vesoft/toolset/gcc/7.5.0
..
```
> Added support for Clang to use a non-standard-location GCC's toolchain

- src/webservice/test/CMakeLists.txt
When using _gold_ as the linker, building fails with undefined referenced symbols. As for the the reason underhood, I will dig it later.
> Fixed linking error with gold

- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/storage/client/StorageClient.inl
We should randomly pick a host to send request if LEADER_CHANGED is returned with leader = (0, 0), both in MetaClient and StorageClient.
> Invalid leader when LEADER_CHANGED with leader = (0, 0)

- src/meta/client/MetaClient.cpp
Fix https://github.com/vesoft-inc/nebula/runs/378612370
Avoid use of freed MetaClient in testing. Better consider enable shared in async.
NO
> Fix the use of free object MetaClient.

- src/graph/test/FetchVerticesTest.cpp
- src/graph/test/TraverseTestBase.h
- A compilation error occurred on my PC.
In the GNU C Library, "major" is defined by <sys/sysmacros.h>.
line : 101 
- Error message:
```
[ 97%] Building CXX object src/graph/test/CMakeFiles/order_by_test.dir/OrderByTest.cpp.o
In file included from /data/source/nebula/src/graph/test/OrderByTest.cpp:10:0:
/data/source/nebula/src/graph/test/TraverseTestBase.h:281:9: internal compiler error: 段错误
const std::string& major() const {
^~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
src/graph/test/CMakeFiles/order_by_test.dir/build.make:62: recipe for target 'src/graph/test/CMakeFiles/order_by_test.dir/OrderByTest.cpp.o' failed
make[3]: *** [src/graph/test/CMakeFiles/order_by_test.dir/OrderByTest.cpp.o] …
```
> fix compilation errors due to naming conflicts

- .github/workflows/build.yaml
- .github/workflows/pull_request.yaml
This PR depends on vesoft-inc/nebula-dev-docker#28
> Fix external llvm symbolizer error for clang asan test

- src/dataman/RowReader.h
- src/kvstore/Common.h
- src/storage/Collector.h
- src/storage/query/QueryBaseProcessor.h
- src/storage/query/QueryBaseProcessor.inl
- src/storage/query/QueryBoundProcessor.cpp
- src/storage/query/QueryBoundProcessor.h
- src/storage/query/QueryEdgePropsProcessor.cpp
- src/storage/test/AdHocSchemaManager.cpp
- src/storage/test/AdHocSchemaManager.h
- src/storage/test/QueryEdgePropsTest.cpp
- src/storage/test/QueryVertexPropsTest.cpp
- src/storage/test/TestUtils.h
close #1185 , close #1154
For now, the storage would be crashed when we want a new property from the latest version tag/edge. The reason is that the data was stored with old tag/edge version, while the storage can't figure out what value type the property is.
> Return default value when prop is not find in old version tag/edge.

- src/kvstore/raftex/RaftPart.cpp
Introduced in #1614, which will cause storage crashed because of `CHECK(replicatingLogs_);`.
Thread 1 could cas `replicatingLogs_` from false to true with `logsLock_`, if thread 2 set `replicatingLogs_` right after cas, it would crash.
> fix crash in storage with high payload

- third-party/externals/rocksdb.cmake
UBsan requires RTTI, while RocksDB disable it by default.
> Build rocksdb with RTTI

- src/kvstore/NebulaStore.cpp
- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
This is the last place we pass range parameter by value.
close #1659,  close #1660.
> [Hot Fix] fix invalid usage of rocksdb iterator

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/pull_request.yaml
- src/kvstore/NebulaStore.cpp
- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
> cherry-pick #1663 to branch RC3

- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVertexProcessor.cpp
See [failed ut](https://github.com/vesoft-inc/nebula/pull/1677/checks?check_run_id=397469707).
Failed because we pass value by reference in async operation, some of them may be released before we use them.
PS: Since we have merged index, we need to add some UT no matter have index or not. (e.g. DeleteVertexTest only cover delete with index)
> [hot fix] pass value in lambda in asyncAtomicOp

- CMakeLists.txt
When `ENABLE_TESTING` is set to `OFF`, this PR excludes the _**test**_ subdirectories out of the default build, while still keep the targets. So that we can build specific target explicitly. Meanwhile, targets will get built automatically if needed.
> Keep relevant targets even if testing disabled

- .github/workflows/build.yaml
- .github/workflows/pull_request.yaml
Undefined behavior sanitizer uses lots of memories and will result in OOM error in runner machine. We should consider a better solution for UBSAN.
> Disable ubsan check temporarily since OOM error

- src/kvstore/LogEncoder.cpp
- src/kvstore/LogEncoder.h
Using `std::tuple` to replace `std::pair<BatchLogType, std::pair>`
> Using tuple to replace the nested pair

- src/graph/GoExecutor.cpp
- src/graph/GoExecutor.h
- src/graph/InsertEdgeExecutor.cpp
- src/graph/UpdateEdgeExecutor.cpp
- src/graph/test/GoTest.cpp
- src/storage/query/QueryBaseProcessor.inl
- src/storage/test/QueryBoundTest.cpp
To improve the efficient, we store properties on in-edge too.  
Main changes:
1.  Take properties when inserting reverse edges.
2.  Remove all special handling code for reversely traverse in GoExecutor.  Now,  for reversely traverse, we handle it as a special edgeType(which is negative.)
3.  Remove all checks on storage-side.
Notes:
I haven't take care of updating logic,  because i think it needs a big refactor.  I will do it later.
> Support properties on in-edge

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/test/RaftexTestBase.cpp
https://github.com/vesoft-inc/nebula/pull/1424/checks?check_run_id=445093798
Let me try to clarify what happens:
1. A is leader of term 5, append some logs
2. A is killed and rebooted, lastLogId = 42
3. A is elected as leader of term 6.
However, A keeps saying `There is a gap in the log id. The last log id is 43, and the id being appended is 43`, ant test case failed.
The problem is that we only `stop` and `start` the part in test, so when we reboot a part, the `lastLogId` could be previous result when it was killed. 
So I reload the last log id in wal. I think we don't need to scan wal files here in test, since we don't actually kill it. In reality, whenever we kill a node and restart, we will always scan all files in constructor.
> fix potential wal bug in ut

- src/common/base/NebulaKeyUtils.h
- src/storage/CompactionFilter.h
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
- src/storage/test/CMakeLists.txt
- src/storage/test/CompactionTest.cpp
When `DROP INDEX` command is complete, At this time, only the metadata of index was removed.
Then, index data needs to be deleted through the compact in storage layer.
> drop index through compact

- src/storage/test/IndexScanTest.cpp
The test case `index_scan_test` often failing on CI system.
The failing reason is : all parts need to elect leaders before data insert.
> fix unstable testcase index_scan_test

- src/kvstore/raftex/RaftPart.cpp
- src/meta/client/MetaClient.cpp
- src/meta/processors/admin/BalanceProcessor.cpp
- src/meta/processors/admin/BalanceTask.cpp
- src/meta/processors/admin/Balancer.cpp
- src/meta/processors/admin/Balancer.h
- src/meta/processors/admin/LeaderBalanceProcessor.cpp
- src/meta/processors/partsMan/ListHostsProcessor.cpp
- src/meta/test/BalancerTest.cpp
- src/storage/StorageServiceHandler.cpp
- src/storage/admin/AdminProcessor.h
Fix some problems during test:
1. Previously we update when BalanceProcessor has return, but the part alloc probably would be updated later, so some machine won't `loadData` in MetaClient. So I update meta when a BalanceTask has done `updateMeta`.
2. When we `balance remove xxx`, the src of BalanceTask could be alive, but previously we regard them as dead, which would cause some part was not removed.
3. We should forbid `balance leader` during `balance data`.
4. We don't need to `refreshCache` when add a part.
> fix some problems during balance

- src/kvstore/SnapshotManagerImpl.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/SnapshotManager.cpp
- src/kvstore/raftex/SnapshotManager.h
- src/kvstore/raftex/test/TestShard.h
It happens in our users testing.
case 1:
Suppose we have three replicas A(leader), B, C, after A crashed,
B, C will begin the election. B win, and send hb, C has gap with B
and need the snapshot from B. Meanwhile C begin the election,
C will be Candidate, but because C is in WAITING_SNAPSHOT,
so prepareElectionRequest will return false and go on the election.
Because C is in Candidate, so it will reject the snapshot request from B.
Infinite loop begins.
So we need to back the follower to avoid the case.
case 2:
It maybe loss data during balance,  because kvstore::prefix maybe return leader-change, 
at this time,  an empty snapshot will be sent to related learner.
> Fix potential raft bug

- src/meta/processors/jobMan/JobManager.cpp
Job Manager judged some tasks as failed. However they can run success manually. 
I guess this may caused by different output of curl. 
print more info if this happen again. and why job manager think those tasks failed.
> Job Manager judged some tasks failed. However they can run success manually by curl. 

- src/kvstore/RocksEngine.cpp
- src/meta/processors/admin/Balancer.cpp
- src/meta/processors/admin/Balancer.h
- src/storage/admin/AdminProcessor.h
1. As title, introduced in #1786, when recovery failed, the plan would be nullptr.
2. Add an error log when commit failed.
close #1820
> Fix meta would crash when balance in multiple relica

- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
Add bidirect syntax.
code PR #1740 #1694 
**TODO: add example**
> [doc]add bidirect

- src/storage/index/LookUpEdgeIndexProcessor.cpp
- src/storage/index/LookUpVertexIndexProcessor.cpp
fixed lookup bug .
Issus #1853
> fixed lookup bug for double free

- third-party/build-third-party.sh
There were some local fixes on #1895 that were not committed by mistake. My bad.
This fix prevent exit when the libc version detection fails due to the `ldd` outputs differ in different  platforms.
> Fix exit-on-failure in build-third-party.sh

- .github/workflows/build.yaml
- .github/workflows/package.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/release.yaml
- src/meta/test/CMakeLists.txt
Modify package/build/release workflow to checkout@v1, because v2 need node12, but centos6 hasn't.
> Fix package/build/release failed

- CMakeLists.txt
- cmake/LinkerConfig.cmake
- third-party/install-third-party.sh
Make it more friendly to tell users that now building nebula under MacOS X is not supported.
When I try to build nebula in my macbook, it print error like this.
```
>  cmake -DENABLE_TESTING=OFF ..
ld: unknown option: --version
CMake Error at cmake/LinkerConfig.cmake:12 (if):
if given arguments:
"STREQUAL" "ld"
Unknown arguments specified
Call Stack (most recent call first):
CMakeLists.txt:35 (include)
```
After ` cmake/LinkerConfig.cmake` fixed, it print error like this. And I found that "Only Linux is supported".
```
>  cmake -DENABLE_TESTING=OFF ..
ld: unknown option: --version
-- NEBULA_USE_LINKER: 
-- ENABLE_ASAN: OFF
-- ENABLE_TESTING: OFF
-- ENABLE_UBSAN: OFF
-- ENABLE_FUZZ_TEST: OFF
-- ENABLE_TSAN: OFF
-- ENABLE_STATIC_ASAN : OFF
-- ENABLE_STATIC_UBSAN : OFF
-- CCACHE: enabled but …
```
> Detect OS type and exit if not built in Linux

- src/kvstore/KVEngine.h
- src/kvstore/KVStore.h
- src/kvstore/LogEncoder.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngine.h
- src/kvstore/plugins/hbase/HBaseStore.h
- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
- src/storage/mutate/DeleteVerticesProcessor.cpp
Current implementation of removePrefix in kvstore is unusable.  It will block current thread for a long time due to scan all data with 'prefix'.  
After upgrade the rocksdb,  we could use removeRange interface to replace the 'removePrefix' in our codebase.   
I will give some basic interfaces about 'nextKey' operations to figure out the end key later.  To avoid the wrong usage,  let's remove the interface firstly.
> Remove removePrefix interface in kvstore

- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
The problem comes from the implementation about deleteRange in rocksdb 5.15.10.
In version 5.15.10,  when calling deleteRange, rocksdb save tombstone as a whole range,  which means for each read, we should scan the range with O(n).
After upgrade the version to the newest one,  rocksdb do split the tombstone range which could allow to do a binary search with O(log(n))
This is why i upgrade the rocksdb's version. 
For more information about deleteRange,  please refer to 
https://github.com/facebook/rocksdb/wiki/DeleteRange-Implementation
> Fix the read performance issue after delete range with rocksdb-5.15.10

- src/kvstore/Part.cpp
For the backward compatibility, we should not crash directly when encountering unknown log. Instead, we just skip it and give a LOG message. 
close #1967
> Remove the LOG(FATAL) when encountering the unknown log.

- src/common/base/Status.cpp
- src/interface/meta.thrift
- src/meta/client/MetaClient.cpp
- src/meta/processors/usersMan/AuthenticationProcessor.cpp
- src/meta/test/AuthProcessorTest.cpp
Related #1947 
1,  Improved error message.
2, fixed typo error.
> Improved customer friendliness for user permission.

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/LogCASTest.cpp
- src/kvstore/raftex/test/TestShard.cpp
- src/kvstore/raftex/test/TestShard.h
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.h
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.h
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
Sometimes,  we don't want to report failure when doing nothing in atomicOp.
To support it,  we should separate the status. 
Now we use folly::Optional to achieve this purpose. 
1. If folly::none returned,  we report failure.  
2. If empty string returned,  we do nothing but report succeed.
> Update the interface atomicOp to support empty string

- docs/manual-CN/4.contributions/pull-request-commit-message-guidelines.md
- docs/manual-EN/4.contributions/pull-request-commit-message-guidelines.md
Add Pull Request and Commit Message Guidelines
> [doc]pr-commit-msg

- .linters/cpp/checkKeyword.py
- .linters/cpp/hooks/pre-commit.sh
- src/graph/test/SchemaTest.cpp
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- If your code adds keywords, it will check the new keyword if in the reserved keyword or the unreserved keyword when you commit the code.
- If users want to use the reserved keyword, they can use `keyword`.
Yes @Amber1990Zhang
> Auto check keyword

- src/dataman/RowReader.cpp
- src/kvstore/Common.h
- src/storage/CommonUtils.h
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
- src/storage/test/UpdateEdgeTest.cpp
- src/storage/test/UpdateVertexTest.cpp
Currently,  there are so many CHECK and LOG(FATAL) inside RowReader,  so if encountering bad format row (For example, upgrade the cluster),  it will core dump. 
Now, instead crash,  storaged report TAG/EDGE NOT FOUND to graphd. 
close #2016
> Fix coredump for update if encountering bad format row

- src/graph/test/IndexTest.cpp
- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
- src/storage/admin/RebuildEdgeIndexProcessor.cpp
- src/storage/admin/RebuildTagIndexProcessor.cpp
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
When insert vertex, need to check if an old index exists, if so, drop the old index and write a new index. At this point, an old index key needs to be assembled by old prop for index check, however, the old property values do not have this new column. so leads to `storaged` crash by `CHECK(prop)`.
Improved this logic，When an invalid property value appears, write index skipped .
repeat step : 
- create space
- use space
- create tag1 (col1, col2)
- create index1 on tag1 (col1)
- insert vertex tag1 values (...)
- alter tag add column col3
- create index2 on tag1 (col3)
- insert vertex tag1 values (...)
> Supports older version of schema for index write

- src/common/stats/StatsManager.cpp
When graphd creates executor, it will call StatsManager::registerStats every time, write locks here affect performance.
Thanks for the discovery of @dutor !
> Optimize registerStats performance

- src/daemons/GraphDaemon.cpp
`SO_REUSEPORT` was introduced in Linux 3.9. Some old distros backport this feature, which might be buggy(like dropping connection intermittently)
Meanwhile, fbthrift is buggy on setting this flag. This patch provides a way to workaround it.
> Fixed SO_REUSEPORT

- src/graph/ShowExecutor.cpp
- src/graph/test/PermissionTest.cpp
To improve 'Show roles in space' : 
- If the logged-in user is role GOD or ADMIN , show all roles with permission space. 
- If the logged-in user is role DBA, USER or GUEST , show only his own role.
> To improve 'Show roles in space'

- etc/nebula-metad.conf.production
- src/common/utils/NebulaKeyUtils.cpp
- src/common/utils/NebulaKeyUtils.h
- src/kvstore/KVEngine.h
- src/kvstore/Part.cpp
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngine.h
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/kvstore/SnapshotManagerImpl.cpp
In poc project, 3 replica meta. If we remove the data dir of one. It would failed to start because it won't get the clusterId. It turned out that the leader send an empty snapshot which have nothing it. (Because it only scan the data with prefix space + part, however nothing start with them in meta)
> Fix meta would send empty raft snapshot

- scripts/utils.sh
> fix get pid

- src/graph/GoExecutor.cpp
- src/graph/test/GoTest.cpp
If the dst vertex without the tag `Company` it returns error message which is not clear.
If the src vertex without the tag `Company` it returns the default value.
So unify return default value.
> Fix the dst vertex use default value when use the nonexistent tag

- src/meta/processors/jobMan/JobManager.cpp
job manager send curl request to every storaged in blocking mode.
which means if user have 4 storaged,, then submit a compact job. 
they will confused why there are only 3 compact sub-job running, not 4. 
no
gflags
> increase job mgr default internal threads from 3 to 10.

- src/storage/query/QueryBaseProcessor.inl
- src/storage/test/QueryBoundTest.cpp
The `continue`s lead to this problem.
> Fix a bug which returns the history version data in query_bound.

- src/kvstore/NebulaStore.cpp
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/RaftPart.cpp
Hard to tell why...
1. The leader want to append log in range [1, 3], normally we expect the start point of the range is equal to `lastLogIdSent_ + 1`, and the end point of the range is `logIdToSend_`.
2. After we send these logs, but before the response comes back, here comes log 4, and then `logIdToSend_` is set to 4.
3. The response [1, 3] is coming back, leader found that follower has accepted them, and leader check whether there is more logs to send by comparing `lastLogIdSent_ < logIdToSend_` in line 242, it is true (3 < 4), and leader will send log [4, 4] to follower.
4. When the response of log [4, 4] comes back, compare `lastLogIdSent_ < logIdToSend_` again, in this case, they are both 4. So the leader would check `noRequest` on line 253. `noRequest` is false because the …
> fix leader will try to send snapshot by mistake, fix clean wal

- src/graph/GoExecutor.cpp
- src/graph/GoExecutor.h
- src/graph/test/GoTest.cpp
> Revert the 2087 workaround.

- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
- src/graph/GoExecutor.cpp
- src/graph/GoExecutor.h
- src/graph/InterimResult.cpp
- src/graph/InterimResult.h
- src/graph/test/GoTest.cpp
[NG-141]
If not yield input this keep same with previous.
If yield input this will join input with current result.
And I fix a bug in previous that the initial start vertices don't dedup but the later steps done. This make the previous result(with duplicate initial start vertices) different(some duplicate row deleted). Had revert it, it's not related to this issue.
> Correct/issue2087 go cover input NG-141

- CMakeLists.txt
Clang omit debug info of libstdc++ to reduce the binary size, hoping the debug info could be retrieved from the debuginfo file shipped along with libstdc++.so, which is not available in our case.
> Fix missing debug info of libstdc++ when build with Clang

- src/kvstore/NebulaStore.cpp
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
use thread local object when access meta client cache. folly::SingletonThreadLocal supply efficient access wrapper by using pointer.
> meta client thread local access.

- share/resources/gflags.json
- src/graph/test/TestEnv.h
- src/graph/test/UpdateTest.cpp
- src/kvstore/CompactionFilter.h
- src/kvstore/NebulaStore.cpp
- src/storage/CompactionFilter.h
- src/storage/StorageFlags.cpp
- src/storage/StorageFlags.h
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateEdgeProcessor.h
- src/storage/mutate/UpdateVertexProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.h
- src/storage/test/DeleteEdgesTest.cpp
1. As title
2. Make `custom_filter_interval_secs` could be updated via console.
3. Add a flag to control whether support multi-version of same key (the timestamp field in key). `enable_multi_versions`, If true, will use wall clock when insert data. If false, always insert as newest data.
4. However, there is a bug in previous `update`........ because the timestamp in `update` is wrong... @jude-zhu release a bug fix version?
```
CREATE TAG building(name string)
UPSERT VERTEX 100 SET building.name = "No1"
FETCH PROP on building 100
INSERT VERTEX building(name) VALUES 100: ("No2")
FETCH PROP on building 100
```
> fix compaction filter doesn't work in manual compaction

- src/graph/test/UpdateTest.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
Fix problems about upsert after alter schema, the default value not found.
```
CREATE TAG building(name string)
INSERT VERTEX building(name) VALUES 100: ("No1")
ALTER TAG building ADD (new_field string default "123")
FETCH PROP on building 100
UPSERT VERTEX 100 SET building.name = "No3", building.new_field = "321"
FETCH PROP on building 100
```
Known issue: when go/fetch data of old schema versions, the default value in new schema won't work, still use int as 0, string as "".
> fix update after alter

- src/dataman/ResultSchemaProvider.cpp
- src/dataman/RowReader.h
- src/jni/src/datamanlite/NebulaSchemaProvider.cpp
- src/meta/NebulaSchemaProvider.cpp
After alter schema, when we read data of old schemas, it will keeps printing some logs like `Unknown field` and `Unknown type`.
> modify some log level when get default value

- src/console/CMakeLists.txt
- src/console/CliManager.cpp
- src/console/CliManager.h
- src/console/NebulaConsole.cpp
@Amber1990Zhang need to modify all docs about use console. the `user` and `password` need to delete.
if `enable_authorize` is false, can directly use console without input username and password, and the default user name is `root`
> Support no username and password are required

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/meta/test/BalanceIntegrationTest.cpp
- src/tools/storage-perf/StoragePerfTool.cpp
See [failed log](https://github.com/vesoft-inc/nebula/pull/2223/checks?check_run_id=863918745).
In some of the ut, RaftPart would be stop and restart. When `restart`, it would add a background task `statusPolling`. And this would make part would start election at wrong time.
In the previous failed case, a part send election twice in different thread within a very short period of time, with term 5 and 6, which makes a log of term 5 failed to replicate to followers. However, this should not happen in real instance. 
BTW, fix StoragePerf tool always write the same edge.
> fix unstable raft ut

- src/parser/parser.yy
> Fix the memroy leak in the parser when parse admin job operation.

- src/graph/test/CMakeLists.txt
- src/graph/test/PartitionTest.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/client/MetaClient.cpp
- src/meta/processors/partsMan/CreateSpaceProcessor.cpp
- src/meta/processors/partsMan/CreateSpaceProcessor.h
because we leave limited memory and cpu for nebula in pubilc cloud, we must limit the number of spaces and partitions. Otherwise it's very dangerous. consider trial-version take one storaged, this may cause data loss. Never miss this
> Limit total partitions

- src/daemons/MetaDaemon.cpp
3-replica meta, stop two followers at first, then leader at last. If leader receive a heartbeat from storage, it will retry forever to updateHostInfo.
The root reason is we didn't stop and release kvstore when we stop daemon.
> fix meta can't be stopped

- etc/nebula-storaged.conf.default
- etc/nebula-storaged.conf.production
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/kvstore/test/RocksEngineConfigTest.cpp
I think there is a need to enable rocksdb's statistics, so we can dump some metrics to the log, and use it to find bottleneck.
We can enable this by specify --rocksdb_statistics_enable=true in nebula-storaged.conf, and declare the stats level through --rocksdb_stats_level(default value is kExceptHistogramOrTimers)
> Support to enable rocksdbs statistics

- src/dataman/RowReader.cpp
- src/dataman/RowReader.h
- src/dataman/RowSetReader.h
- src/dataman/RowUpdater.cpp
- src/dataman/RowUpdater.h
- src/graph/FetchVerticesExecutor.cpp
- src/graph/GoExecutor.cpp
- src/graph/GoExecutor.h
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
- src/storage/query/QueryBaseProcessor.h
- src/storage/query/QueryBaseProcessor.inl
- src/storage/query/QueryBoundProcessor.cpp
- src/storage/query/QueryStatsProcessor.cpp
VertexHolder::getDefaultProp has huge performace problem, if get some prop not exist.
before:
after:
> fix VertexHolder::getDefaultProp performance issue.

- src/storage/index/IndexExecutor.inl
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
- src/storage/query/QueryBaseProcessor.inl
- src/storage/query/QueryVertexPropsProcessor.cpp
Use partId as hint of LRU cache is a bad idea, as a machine only has some of the partitions. This will cause lock conflict a big performance issue.
PS:
Hash a limited num stored in the L1 cache of CPU, has little impact on the performance, as the access to the memory cost hundreds of CPU cycle.
> remove lru partid as hint.

- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
- src/dataman/RowWriter.h
> Using icord to avoid dynamic allocation and speed up write.

- src/kvstore/RocksEngineConfig.cpp
- src/storage/CMakeLists.txt
- src/storage/StorageServer.cpp
- src/storage/http/StorageHttpStatsHandler.cpp
- src/storage/http/StorageHttpStatsHandler.h
- src/storage/test/CMakeLists.txt
- src/storage/test/StorageHttpStatsHandlerTest.cpp
- src/webservice/GetStatsHandler.h
After #2243, rocksdb’s statistics can be enabled by specify --enable_rocksdb_statistics=true, And the statistics info will be dumped into each DB’s log file periodically.
Since all DB instances share the same Statistics obj, there is no need to dump it every where.
So it's better to manage it ourself, and exposing the statistics through webservice.
usage example:
(1) get all stats
http://host:prot/rocksdb_stats
(2) get specify stats
http://host:prot/rocksdb_stats?stats=rocksdb.bytes.read,rocksdb.block.cache.add
(3) return json format
http://host:prot/rocksdb_stats?stats=rocksdb.bytes.read,rocksdb.block.cache.add&returnjson
> Exposing rocksdb statistics through webservice

- src/tools/spark-sstfile-generator/src/main/scala/com/vesoft/nebula/tools/generator/v2/SparkClientGenerator.scala
What changes were proposed in this pull request?
Fix SparkClientGenerator. The function extraValue add duplicate double quote to index. Remove the quote in `INSERT_VALUE_TEMPLATE_WITH_POLICY`. `ENDPOINT_TEMPLATE` need NOT to be changed, because double quote is not duplicate while insert edges. Refers to #2250 #2245 
Why are the changes needed?
When using extraValue to transfrom index, double quote was added. 
before: duplicate double quote
after: aviod duplicate double quote
Does this PR introduce any user-facing change?
No.
How was this patch tested?
Built jar and test in production environment.
> fix double quote in index

- src/interface/storage.thrift
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/Part.cpp
- src/kvstore/PartManager.cpp
- src/kvstore/PartManager.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/test/MemberChangeTest.cpp
- src/meta/processors/admin/AdminClient.cpp
- src/meta/processors/admin/BalancePlan.cpp
- src/meta/processors/admin/BalanceTask.cpp
- src/storage/admin/AdminProcessor.h
1.   For leaders and followers, check the state for each part before balance. It gives a chance to recover from the last failed state.
2.  For learners,  check the peers and their state when opening. 
During chaos testing,  we found some problems when the opening part is too slow.  It always causes the members in raft group mix up its peers,  and leader election always failed.  
To recover from it,  we have this PR.
> Enhance the failover logic for balance procedure. 

- src/common/filter/FunctionManager.cpp
- src/common/filter/FunctionManager.h
atomic operation acts like dead lock, and can not go out of the while loop if multi-thread access it frequently.
> Remove lock in FunctionManager

- src/storage/test/CMakeLists.txt
- src/storage/test/GetNeighborsBenchmark.cpp
Add GetNeighborsBenchmark, no concurrency, used to compare with 2.0 under almost same data.
The copy of lastRank and lastDstId has trivial impact in 1.0, so leave it alone. @dangleptr.
> Add GetNeighborsBenchmark

- src/kvstore/raftex/RaftPart.cpp
> raft lease is always valid when replica is one

- src/graph/UpdateVertexExecutor.cpp
Statistics of `graph_update_vertex_error_qps` is incorrect. This stats should be added when status is NOT ok. #2269
> fix bugs for "graph_update_vertex_error_qps"

- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
Meet an error:
Try to start all daemon twice. 
The second one will failed, and said 
'process already existed'.
But the first one can't output log any more.
> check pid before init glog

- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
Introduced in #2278, if we want to start multiple daemon with different flag file, the `FLAGS_pid_file` is the same because we have not init `gflags` yet. (all of them is the default value of `FLAGS_pid_file`, not the one in flag file)
So we need to init `gflags`, `glogs` by manual instead of `folly::init`.
> fix multi daemon can't start on same node

- src/common/base/Logging.h
- src/kvstore/EventListner.h
- src/kvstore/Part.cpp
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/Host.h
- src/kvstore/raftex/RaftPart.cpp
1. When elected as leader, we need to reset all info in `Host`, which may trigger snapshot by mistake. Otherwise, if it is elected as leader more than once, the info in host is outdated.
2. Add more EventListener
@sherman-the-tank, we will open another PR to fix election problem.
> [RAFT] fix raft snapshot by mistake

- src/common/utils/NebulaKeyUtils.h
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/test/DeleteVerticesTest.cpp
get one core screen from BBS. 
https://discuss.nebula-graph.com.cn/t/topic/1123/8
check all reference to getTagId, 
find deleteVerticesProcessor call this without check if it is a vertex first.
> bug fix: delete vertices processor may core, if this vertex also have edges and index

- etc/nebula-storaged.conf.default
- etc/nebula-storaged.conf.production
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/storage/test/CMakeLists.txt
- src/storage/test/PrefixBloomFilterBenchmark.cpp
- src/storage/test/QueryVertexPropsTest.cpp
Currently, The DataModel of Vertex and Edge are as follows
(1)Vertex: **type(1byte)_PartID(3bytes)_VertexID(8bytes)**_TagID(4bytes)_Timestamp(8bytes)
(2)Edge: **type(1byte)_PartID(3bytes)_VertexID(8bytes)**_EdgeType(4bytes)_Rank(8bytes)_otherVertexId(8bytes)_Timestamp(8bytes)
We can use “**type(1byte)_PartID(3bytes)_VertexID(8bytes)**” as the value for prefix bloom filter, QueryEdgePropsProcessor and QueryVertexPropsProcessor can benefit from this a lot
> Add prefix bloom filter support

- share/resources/gflags.json
- src/kvstore/NebulaStore.cpp
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/kvstore/test/NebulaStoreTest.cpp
- src/kvstore/wal/FileBasedWal.cpp
- src/storage/test/GetNeighborsBenchmark.cpp
1. Fix unstable ut in NebulaStoreTest because we check the leader by `leader_` not the `role` in `RaftPart`
2. Update GetNeighbors benchmark,  add bench of encode and filter, similar to what we did in 2.0
3. Add a random delay after election failed, make sure only one election request is on-going.
4. Fix follower would crash in unusual case.
5. Keep one extra wal, because I check a log in test env and find out that even if the log gap is very small, when we reboot, it would trigger snapshot because there is only one wal.
> Minor changes in raft, fix unstable ut, update GetNeighbors benchmark

- src/daemons/MetaDaemon.cpp
- src/meta/processors/jobMan/JobManager.cpp
- src/meta/processors/jobMan/JobManager.h
- src/meta/test/JobManagerTest.cpp
shutdown job manager if its Initialization finished
> bug fix: shutdown meta server before job manager init, may core

- src/graph/LookupExecutor.cpp
- src/graph/LookupExecutor.h
- src/graph/test/LookupTest.cpp
It was splitted from PR #2277 . Only disable string range scan and contains
> Disable index range scan of string data type in graph layer

- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/test/IndexTest.cpp
As title, since the default value of enable_multi_versions is false, we could use the bloom filter to avoid extra disk read if the newly insert data does not exist.
> Try to use whole key bloom filter when insert data with index

- src/graph/DropSpaceExecutor.cpp
- src/kvstore/NebulaStore.cpp
- src/kvstore/raftex/RaftPart.cpp
1. Add a flag to control whether delete data of dropped space when restart
2. Identify a potential bug in raft, we don't modify in 1.0 for safety
> add a flag to control whether delete data of dropped space when restart

- src/kvstore/raftex/RaftPart.cpp
Fix tow bugs in the RaftPart.
- The first bug is partition will reject the same candidate who has already voted use the same term to request a vote again. This problem may occur when the RPC times out.
- The second bug is that when leader change its role from leader to follower after voting, it fails to call wal_->rollbackToLog(..), making RaftPart's lastLogId_ and Wal's lastLogId_ out of sync, which further causes the fake leader to be stuck when  fake leader appears.
- Fake leader: Become a leader but cannot send out messages and disagree with the received messages !
- The first bug will cause abnormal communication between partitions when the raft pressure is high.
- The second bug will produce fake leaders and not heal itself for a long time.
- Supplement for how the fake leader …
> Fix some raft bugs that can cause raft to be unstable and even some partitions become stuck after becoming fake leaders

- src/meta/ClusterIdMan.h
- src/meta/test/ClusterIdManTest.cpp
Introduced in https://github.com/vesoft-inc/nebula/pull/2403.
> fix meta follower can't read clusterId

- src/meta/client/MetaClient.cpp
When compact index data,  The index key will check whether the index exists. If the index does not exist, many logs will be thrown.
> fixed log blowout error for compact index data

- .github/workflows/docker.yaml
- .github/workflows/release.yaml
- docker/Dockerfile.tools
- docker/README.md
- docker/build-images.sh
nebula-tools image includes:
- storage_perf
- storage_integrity
- simple_kv_verify
- db_dump
> build docker image of db_dump and other tools

- CONTRIBUTING.md
- README-CN.md
- README.md
- Fix link broken in `README` and `README-CN`
- Add version-awareness highlights and background information to new comers
> fix: all link broken and enable Version-Awareness in README and README-Cn

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/wal/FileBasedWal.cpp
- src/kvstore/wal/FileBasedWal.h
- src/kvstore/wal/Wal.h
- src/kvstore/wal/test/FileBasedWalTest.cpp
####. fix inconsistency problem in raftpart appendlog method.
*Hi, when I read  the  implementation of raft in neblua,  I found out that may exist a inconsistency problem. In the raftpart,  if  a follower receive  logs  from  leader conflicting with itself,  it will rollback  the  log to lastCommitID. such behavior may cause inconsistency commit logs. 
here is a picture to show how it may happend : 
I think that the follower could not deletes the log arbitrarily. because some logs may have been already committed.
I  refine the  implementation to follow the guildline in the paper of raft .
no 
no
> Raft problem

- .github/workflows/pull_request.yml
- src/daemons/CMakeLists.txt
- src/daemons/GraphDaemon.cpp
- src/graph/service/GraphFlags.cpp
> Fix lint error

- .github/workflows/nightly.yml
- README-CN.md
- README.md
> Fix links in README

- .github/workflows/pull_request.yml
> Fix clang format check

- .github/workflows/pull_request.yml
- src/daemons/CMakeLists.txt
One small improvement is the classification of public libraries.
Test linters and CI by the way.
> Small improvement to daemons compilation.

- src/meta/MetaServiceUtils.cpp
- src/meta/MetaServiceUtils.h
- src/meta/processors/BaseProcessor-inl.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/Common.h
- src/meta/processors/index/CreateEdgeIndexProcessor.cpp
- src/meta/processors/index/CreateTagIndexProcessor.cpp
- src/meta/processors/parts/DropSpaceProcessor.cpp
- src/meta/processors/schema/CreateEdgeProcessor.cpp
- src/meta/processors/schema/CreateTagProcessor.cpp
- src/meta/test/IndexProcessorTest.cpp
- src/meta/test/ProcessorTest.cpp
- src/meta/test/TestUtils.h
As title
1） Tag, edge, tag index and edge index use space range id.
2） Compatible with the existing old schema creating previously.
Synchronize nebula-storage repo pr https://github.com/vesoft-inc/nebula-storage/pull/501
> use local id in the space range for tag edge index

- src/graph/validator/OrderByValidator.cpp
- src/graph/validator/OrderByValidator.h
- src/graph/validator/SequentialValidator.cpp
- src/parser/parser.yy
- tests/tck/features/fetch/FetchVertices.intVid.feature
- tests/tck/features/fetch/FetchVertices.strVid.feature
- tests/tck/features/go/GroupbyLimit.feature
- tests/tck/features/go/Orderby.feature
- tests/tck/features/lookup/ByIndex.feature
- tests/tck/features/lookup/ByIndex.intVid.feature
- tests/tck/features/optimizer/TopNRule.feature
migrate https://github.com/vesoft-inc/nebula-graph/pull/1314 to this repository.
Close #2548
> [migrate #1314]fix the wrong usage of limit sentence

- .github/workflows/pull_request.yml
- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceUtils.cpp
- src/meta/processors/admin/HBProcessor.cpp
- src/meta/processors/admin/HBProcessor.h
- src/meta/test/HBProcessorTest.cpp
- src/meta/test/RestoreProcessorTest.cpp
- src/storage/admin/RebuildEdgeIndexTask.cpp
- src/storage/admin/RebuildTagIndexTask.cpp
- src/storage/test/CMakeLists.txt
- src/tools/db-dump/CMakeLists.txt
- src/tools/db-upgrade/CMakeLists.txt
- src/tools/meta-dump/CMakeLists.txt
- src/tools/simple-kv-verify/CMakeLists.txt
- src/tools/storage-perf/CMakeLists.txt
> Cherry-pick PR from v2.5.0

- src/graph/executor/algo/ConjunctPathExecutor.cpp
- tests/tck/features/path/AllPath.IntVid.feature
- tests/tck/features/path/AllPath.feature
https://discuss.nebula-graph.com.cn/t/topic/5566/11
> fix all path bug

- src/kvstore/raftex/test/LeaderTransferTest.cpp
- src/storage/admin/AdminTaskManager.cpp
- src/storage/admin/AdminTaskManager.h
- src/storage/test/IndexWithTTLTest.cpp
- src/storage/test/RebuildIndexTest.cpp
- src/storage/test/StatsTaskTest.cpp
JobId + TaskId is not unique in some ut, which may cause `isFinished` return earlier than expected.
Close #2761
> fix unstable job related ut

- .github/actions/tagname-action/README.md
- .github/actions/tagname-action/action.yml
- .github/workflows/release.yml
- src/clients/meta/MetaClient.cpp
From then on, users need to go to the download page of nebula's official website to download the released installation package and source code package
> Cancel uploading the packages to the release assets

- src/kvstore/CMakeLists.txt
- src/kvstore/NebulaSnapshotManager.cpp
- src/kvstore/NebulaSnapshotManager.h
- src/kvstore/RateLimiter.cpp
- src/kvstore/RateLimiter.h
- src/kvstore/test/RateLimiterTest.cpp
- src/storage/admin/RebuildEdgeIndexTask.cpp
- src/storage/admin/RebuildEdgeIndexTask.h
- src/storage/admin/RebuildIndexTask.cpp
- src/storage/admin/RebuildIndexTask.h
- src/storage/admin/RebuildTagIndexTask.cpp
- src/storage/admin/RebuildTagIndexTask.h
- tests/common/nebula_service.py
Skip the first second wait in rate limiter, which will take 1 second in every case in TCK tests. And then, another core occur, see #2794, remove the DCHECK temporally. 
Duration of TCK should back to normal.
TCK with ASAN still time out, probably because of spin lock. Still working on it.
> skip the wait in rate limiter in CI

- .github/workflows/pull_request.yml
- tests/common/utils.py
- tests/tck/conftest.py
Remove unnecessary index rebuilding.
The index has been created before the data import, so instead of rebuilding.
Let's verify the stability of CI.
> tck testcases strengthening

- src/mock/MockData.cpp
This error is actually caused by the CI system running slowly when ASAN is enabled.
This is a TTL test case , default the ttl duration is 5 sec. at this point, the expected test case may not have run done, but the TTL has expired, the expected result is empty . the crash is EXPECT_EQ check.
**row[2] is empty now:**
trace:
`#0  nebula::storage::QueryTestUtils::checkRowProps (row=..., colNames=..., tags=..., edges=...) at /data/cbs/source/nebula/src/storage/test/QueryTestUtils.h:789
#1  0x0000000002c56612 in nebula::storage::QueryTestUtils::checkResponse (dataSet=..., vertices=..., over=..., tags=..., edges=..., expectRowCount=1, expectColumnCount=5, 
expectStats=0x0) at /data/cbs/source/nebula/src/storage/test/QueryTestUtils.h:381
#2  0x0000000002cbd513 in …
> fixed unstable case get_neighbors_test when ASAN turn on.

- src/storage/admin/AdminTaskManager.cpp
- src/storage/admin/RebuildEdgeIndexTask.cpp
- src/storage/admin/RebuildTagIndexTask.cpp
Rebuild index has been removed from TCK after #2797. However, there are some hot-spot in rebuild index, e.g. `getTagSchema/getEdgeSchema`, some of them has been removed in this PR, but the one when build rowreader can't be eliminated for now, wait #2786 is fixed.
> enhancement in rebuild

- src/graph/visitor/DeduceTypeVisitor.cpp
- tests/tck/features/expression/FunctionCall.feature
Fixes [https://github.com/vesoft-inc/nebula/issues/2566](https://github.com/vesoft-inc/nebula/issues/2566)
> fix time() infinite loop

- src/common/expression/CaseExpression.cpp
- tests/tck/features/aggregate/Agg.feature
- tests/tck/features/expression/Case.feature
Fixes [https://github.com/vesoft-inc/nebula/issues/2818](https://github.com/vesoft-inc/nebula/issues/2818)
> fix case expression

- src/storage/context/StorageExpressionContext.cpp
- src/storage/exec/QueryUtils.h
- tests/tck/features/expression/FixedString.feature
fixed bug for expression eval when prop data type is fixed_string
Repetition steps：
```
CREATE SPACE test_space (partition_num=1,replica_factor=1, vid_type=fixed_string(30));
USE test_space
create tag t1(c1 fixed_string(40))
create edge e1(c1 fixed_string(40))
insert vertex t1(c1) values "1":("row"), "2":("row"), "3":("row")
insert edge e1(c1) values "1" -> "2"@0:("row"), "1" -> "3"@0:("row")
go from "1" over e1 where e1.c1 == "row"
go from "1" over e1 where $$.t1.c1 == "row"
go from "1" over e1 where $^.t1.c1 == "row"
```
> fixed fixed_string expression eval for go

- .github/workflows/pull_request.yml
Reverts vesoft-inc/nebula#2513
Some markdown modifications can no longer trigger our CI, which in turn prevents PR from being merged
> Revert "Ignore some path don't impact workflow."

- src/clients/meta/MetaClient.cpp
- src/kvstore/NebulaStore.cpp
- tests/common/utils.py
- tests/requirements.txt
- tests/tck/features/lookup/ByIndex.feature
- tests/tck/features/lookup/ByIndex.intVid.feature
- tests/tck/features/lookup/TagIndexFullScan.feature
- tests/tck/utils/nbv.py
1. Need not to create new space for only read queries.
2. Wait more seconds to update schema cache in meta client
* https://github.com/mailgun/flanker/issues/168
* https://github.com/mailgun/flanker/pull/188
* https://github.com/vesoft-inc/nebula/runs/3586920120?check_suite_focus=true
> Fix ply.yacc read parsetab.py error and lookup tests optimization

- src/meta/processors/job/JobManager.cpp
> fix running jobs in dropped space block others

- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
- package/package.sh
As title.
Close https://github.com/vesoft-inc/nebula/issues/2836
> Fix version display in docker

- .github/workflows/pull_request.yml
- src/clients/meta/MetaClient.cpp
- src/meta/http/MetaHttpDownloadHandler.cpp
- src/meta/http/MetaHttpIngestHandler.cpp
- src/webservice/CMakeLists.txt
- src/webservice/Common.cpp
- src/webservice/Common.h
- src/webservice/test/CMakeLists.txt
We should not directly define static variables in the header file
> Cleanup static variables in header files

- src/common/algorithm/ReservoirSampling.h
- src/common/algorithm/test/ReservoirSamplingTest.cpp
- src/storage/exec/GetNeighborsNode.h
https://github.com/vesoft-inc/nebula/pull/2853
> fix crash in sample

- src/graph/validator/MutateValidator.cpp
- src/graph/validator/MutateValidator.h
- src/graph/validator/test/MutateValidatorTest.cpp
- tests/tck/features/insert/InsertEdgeOnDiffParts.feature
- tests/tck/features/schema/Schema.feature
Fixes [https://github.com/vesoft-inc/nebula/issues/2739](https://github.com/vesoft-inc/nebula/issues/2739)
> fix insert edge

- src/storage/exec/IndexEdgeNode.h
- src/storage/exec/IndexFilterNode.h
- src/storage/exec/IndexScanNode.h
- src/storage/exec/IndexVertexNode.h
- src/storage/index/LookupBaseProcessor-inl.h
- src/storage/index/LookupProcessor.cpp
- src/storage/test/IndexScanLimitTest.cpp
related PR #2796 
The logic of the previous PR is simple, handles limits during the index scan phase. Scanning filter, data validity, etc., are not considered.
for this PR , The items below will be covered by：
- index filter
- index ttl
- Invalid data for index
- Invalid data for prop value
- skip the execution plan when limit = 0
Temporarily unsupported
- de-dup execute node. currently, de-Dup does not work on index scans. We can ignore it for now. Handler it when `Limit + Paging Scan` is integrated
> fixed bug limit push down of index scan.

- .gitignore
- src/common/utils/NebulaKeyUtils.cpp
- src/common/utils/NebulaKeyUtils.h
- src/kvstore/KVEngine.h
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngine.h
- src/storage/CommonUtils.h
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
- src/storage/admin/AdminTask.h
- src/storage/admin/AdminTaskManager.cpp
- src/storage/admin/AdminTaskManager.h
- src/storage/admin/AdminTaskProcessor.cpp
https://github.com/vesoft-inc/nebula/issues/2764
> store admintasks' status and send the status to metad when starting

- src/common/function/test/FunctionManagerTest.cpp
```
In file included from /home/william.chen/nebula/build/third-party/install/include/gtest/gtest.h:58,
from /home/william.chen/nebula/src/common/function/test/FunctionManagerTest.cpp:7:
/home/william.chen/nebula/src/common/function/test/FunctionManagerTest.cpp: In member function 'virtual void nebula::FunctionManagerTest_functionCall_Test::TestBody()':
/home/william.chen/nebula/src/common/function/test/FunctionManagerTest.cpp:212:8: note: variable tracking size limit exceeded with '-fvar-tracking-assignments', retrying without
212 | TEST_F(FunctionManagerTest, functionCall) {
|        ^~~~~~~~~~~~~~~~~~~
```
> Fix the var-tracking-assignments warning.

- scripts/CMakeLists.txt
- scripts/meta-transfer-tools.sh
In our forum, some user complain lack of mete transfer tools. 
this tool is a simple wrapper to scp to copy local folder of metad to another (remote)place
it afford 4 options:   
1. -f (from) local metad dir
2. -t (to) remote destination
3. -u (update) any configs need to be changed
different configs should be seperated by ':'
each config has to be the form of "local_ip=172.0.0.1"
for example
```
./meta-transfer-tools.sh -f /path-to-src/metad1 -t bob@172.0.0.1:/path-to-dst -u local_ip=172.0.0.1:port=10086
```
this is not a well discussed solution for this, and I'm not very good at shell, any suggestion is welcome.
> add a script to do metad folder scp

- src/common/graph/Response.h
1. Change error code in JSON to In
2. Correct JSON format:
```  JSON struct:
{
"results": [
{
"columns": [],
"data": [
{
"row": [
"row-data"
],
"meta": [
"metadata"
]
}
],
"latencyInUs": 0,
"spaceName": "",
"planDesc ": {
"planNodeDescs": [
{
"name": "",
"id": 0,
"outputVar": "",
"description": {
"key": ""
},
"profiles": [
{
"rows": 1,
"execDurationInUs": 0,
"totalDurationInUs": 0,
"otherStats": {}
}
],
"branchInfo": {
"isDoBranch": false,
"conditionNodeId": -1
},
"dependencies": []
}
],
"nodeIndexMap": {},
"format": "",
"optimize_time_in_us": 0
},
"comment ": ""
}
],
"errors": [
{
"code": 0,
"message": ""
}
]
}
```
3. Make the JSON in the comment look nicer.
> Change error code in JSON to Int

- src/graph/planner/ngql/LookupPlanner.cpp
- src/meta/processors/zone/UpdateGroupProcessor.cpp
```
(root@nebula) [(none)]> add zone z1 "192.168.8.215":55501
Execution succeeded (time spent 4793/5348 us)
Mon, 27 Sep 2021 23:05:57 CST
(root@nebula) [(none)]> add group g1 z1
Execution succeeded (time spent 2695/3292 us)
Mon, 27 Sep 2021 23:06:02 CST
(root@nebula) [(none)]> create space s2 (vid_type=int, replica_factor=1, partition_num=1) on g1
Execution succeeded (time spent 3023/3567 us)
Mon, 27 Sep 2021 23:06:17 CST
(root@nebula) [(none)]> drop zone z1 from group g1
[ERROR (-1005)]: Conflict!
Mon, 27 Sep 2021 23:06:30 CST
```
> Add more check about drop zone with created space

- src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
- src/storage/transaction/ChainAddEdgesProcessorLocal.h
- src/storage/transaction/ChainResumeProcessor.cpp
prepareLocal() failed will also lock edge in transaction manager, which is not necessary. 
(because there isn't any prime)
> If an edge prepareLocal(), it should not go into resume process. 

- src/meta/processors/parts/CreateSpaceProcessor.cpp
- src/meta/test/ProcessorTest.cpp
I do not know why create space on empty hosts .
```
(root@nebula) [(none)]> add zone z1 "192.168.8.215":55501
Execution succeeded (time spent 4811/5352 us)
Wed, 29 Sep 2021 07:02:34 CST
(root@nebula) [(none)]> show hosts
+-----------------+-------+----------+--------------+----------------------+------------------------+
| Host            | Port  | Status   | Leader count | Leader distribution  | Partition distribution |
+-----------------+-------+----------+--------------+----------------------+------------------------+
| "192.168.8.215" | 55501 | "ONLINE" | 0            | "No valid partition" | "No valid partition"   |
+-----------------+-------+----------+--------------+----------------------+------------------------+
| "Total"         |       |          | 0            | …
```
> fix create space on empty hosts

- src/graph/optimizer/OptimizerUtils.cpp
- src/graph/optimizer/OptimizerUtils.h
- src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
- src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/util/test/ExpressionUtilsTest.cpp
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/LookupValidator.h
- src/graph/visitor/FindVisitor.cpp
- src/graph/visitor/FindVisitor.h
- src/graph/visitor/FoldConstantExprVisitor.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
- tests/tck/features/lookup/EdgeIndexFullScan.feature
- tests/tck/features/lookup/LookupEdge2.feature
- tests/tck/features/lookup/LookupTag2.feature
- tests/tck/features/lookup/TagIndexFullScan.feature
- tests/tck/features/match/SeekById.feature
- tests/tck/features/match/SeekById.intVid.feature
1. Fix constant fold for container expressions
2. Disable using other string-related relExpr as the filter of LOOKUP except `STARTS/NOT STARTS WITH`
3. Convert `IN` expression to `OR` expression in `LOOKUP` if the property in the`IN` expression has a valid index:
- Stand alone `IN` expr: `A in [B, C, D]  =>  (A == B) or (A == C) or (A == D)`
- With `AND` expr : `A in [a, b] AND B  =>  (A==a AND B) OR (A==b AND B)`
- With `OR` expr: `A in [a, b] OR B  =>   A==a OR A==b OR B`
4. If the container has only one element, the `IN` expression will be transformed to a `relEQ` expression. e.g.  `A in [B]  =>  A==B`
Close https://github.com/vesoft-inc/nebula/issues/2881
> Support lookup indexScan using IN expression as filter

- .linters/cpp/checkKeyword.py
- src/common/context/ExpressionContext.h
- src/common/expression/VertexExpression.cpp
- src/common/expression/VertexExpression.h
- src/common/expression/test/ExpressionContextMock.h
- src/common/utils/DefaultValueContext.h
- src/graph/context/Iterator.cpp
- src/graph/context/Iterator.h
- src/graph/context/QueryExpressionContext.cpp
- src/graph/context/QueryExpressionContext.h
- src/graph/validator/GoValidator.cpp
- src/graph/validator/GoValidator.h
- src/graph/validator/test/GetSubgraphValidatorTest.cpp
- src/graph/validator/test/GroupByValidatorTest.cpp
- src/graph/validator/test/LookupValidatorTest.cpp
- src/graph/validator/test/QueryValidatorTest.cpp
- src/parser/parser.yy
- src/parser/scanner.lex
- src/storage/context/StorageExpressionContext.h
- tests/tck/features/aggregate/Agg.feature
- tests/tck/features/fetch/FetchVertices.intVid.feature
- tests/tck/features/fetch/FetchVertices.strVid.feature
- tests/tck/features/go/GO.feature
- tests/tck/features/go/GoYieldVertexEdge.feature
- tests/tck/features/subgraph/subgraph.IntVid.feature
- tests/tck/features/subgraph/subgraph.feature
$^  represents the starting point of the edge
$$  represents the destination point of the edge
go from 'a' over * yield  $^ as startNode, $$ as endNode, edge as relationship
the type of $^ and $$ is VERTEX,  must add alias when use $^ or $$
> format go yield

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/common/graph/Response.h
- src/graph/context/test/CMakeLists.txt
- src/graph/executor/test/CMakeLists.txt
- src/graph/optimizer/test/CMakeLists.txt
- src/graph/planner/test/CMakeLists.txt
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/service/GraphService.cpp
- src/graph/service/GraphService.h
- src/graph/util/test/CMakeLists.txt
- src/interface/common.thrift
- src/interface/graph.thrift
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/processors/admin/VerifyClientVersionProcessor.cpp
- src/meta/processors/admin/VerifyClientVersionProcessor.h
- src/meta/test/MetaClientTest.cpp
- src/parser/test/CMakeLists.txt
- src/version/Version.cpp.in
- src/version/Version.h
- tests/conftest.py
- tests/tck/conftest.py
- tests/tck/features/verify_client_version/VerifyClientVersion.feature
nebua python client had been updated. https://github.com/vesoft-inc/nebula-python/pull/148
> Verify the client version.

- src/graph/context/ast/CypherAstContext.h
- src/graph/planner/match/LabelIndexSeek.cpp
- src/graph/planner/match/PropIndexSeek.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/SeekByEdge.feature
> Fix match start from edge.

- src/kvstore/Listener.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/TestShard.cpp
- src/kvstore/raftex/test/TestShard.h
- src/storage/transaction/ChainUpdateEdgeProcessorLocal.cpp
- src/storage/transaction/ChainUpdateEdgeProcessorLocal.h
- src/storage/transaction/TransactionManager.cpp
previously transaction register a callback function to Raft,
called at onElected(), to do a partition scan, to check if there is a (double) prime key.
but some raft internal status is not set until leader send its first log. 
which will let the transaction manager scan failed. 
so split the origin onElected to two part(1st still named onElected(), and 2nd named onLeaderReady()). 
and the scan will be called at onLeaderReady.
> split onElected and onLeaderReady

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- third-party/install-cmake.sh
- third-party/install-gcc.sh
- third-party/install-third-party.sh
close #2834 
close #2656 
（If it is requirement, issue(s) number must be listed.）
`
vesoft-inc/nebula-dev-docker#58
> Build ARM platform docker images

- src/graph/validator/LookupValidator.cpp
- src/graph/validator/test/LookupValidatorTest.cpp
- tests/tck/features/lookup/WithYield.feature
- tests/tck/features/lookup/WithYield.intVid.feature
- bug
close https://github.com/vesoft-inc/nebula/issues/3230
PathbuildExpression is for internal use, users cannot construct pathbuildExpression, so no need validate
> disable lookup yield agg function

- .github/workflows/nightly.yml
- .github/workflows/release.yml
> Use self-hosted runner to speed up nightly and releasing packaging

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/test/LookupValidatorTest.cpp
- tests/tck/features/lookup/WithYield.feature
- tests/tck/features/lookup/WithYield.intVid.feature
- third-party/install-cmake.sh
- third-party/install-gcc.sh
- third-party/install-third-party.sh
> Cherry pick from master to v2.6.1

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/pull_request_template.md
close #xxx   
（If it is requirement, issue(s) number must be listed.）
Fix typos/grammar in the template
> [Minor] Fix typos in the template

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .licenserc.yaml
- scripts/meta-transfer-tools.sh
- scripts/utils.sh
- src/common/datatypes/EdgeOps-inl.h
- src/common/datatypes/HostAddrOps-inl.h
- src/common/datatypes/PathOps-inl.h
- src/common/datatypes/ValueOps-inl.h
- src/common/geo/GeoIndex.cpp
> Add license check

- tests/Makefile
Update nebula-python installation in the test due to the change made in https://github.com/vesoft-inc/nebula-python/pull/153
https://github.com/vesoft-inc/nebula-python/pull/153
> Update nebula-python installation in the test

- src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
fix an issue that storage may stuck.
https://github.com/vesoft-inc/nebula/issues/3304
we need 3 pre-condition to repro this:
1: storage server is stopping 
2. a resume processor is running. 
3. the previous processor throw an exception.
> fix a bug may stuck

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- .github/workflows/release.yml
Don't package when publishing a release.
> Trigger packaging action when pushing release branch

- src/graph/validator/MatchValidator.cpp
- src/graph/validator/MatchValidator.h
- src/graph/visitor/FoldConstantExprVisitor.cpp
- src/graph/visitor/test/FilterTransformTest.cpp
- src/parser/MatchSentence.h
- src/storage/exec/IndexScanNode.cpp
- tests/tck/features/expression/EndsWith.feature
- tests/tck/features/expression/Null.feature
- tests/tck/features/expression/StartsWith.feature
- tests/tck/features/expression/function/Mathematical.feature
- tests/tck/features/expression/function/TypeConversion.feature
- tests/tck/features/go/GO.feature
- tests/tck/features/lookup/ByIndex.feature
- tests/tck/features/lookup/ByIndex.intVid.feature
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/schema/Schema.feature
- tests/tck/features/yield/yield.IntVid.feature
- tests/tck/features/yield/yield.feature
enhancement
close https://github.com/vesoft-inc/nebula/issues/3270
> enhance match attribute filter

- src/meta/processors/job/JobManager.cpp
> fix meta follower read remaining jobs

- src/meta/processors/parts/CreateSpaceAsProcessor.cpp
- src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
- tests/tck/features/schema/CreateSpaceAs.feature
- [X ] bug
Fix a bug can't show edge after clone space. 
Discussed from forum:
https://discuss.nebula-graph.com.cn/t/topic/6565
> [fix] can't show edge after clone space

- src/clients/meta/MetaClient.cpp
Check the result of `listHosts()`. Currently, the result of `listHosts()` is never checked.
>
> [Minor] Check the result of listHosts()

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- src/graph/executor/admin/ConfigExecutor.cpp
- src/graph/service/GraphFlags.cpp
- src/graph/session/GraphSessionManager.cpp
- tests/admin/test_configs.py
- tests/job/test_session.py
1. Modify default value for `session_idle_timeout_secs` and `client_idle_timeout_secs` from 0 (never timeout) to 28800(8 hours, which is also the default timeout MySQL uses).
2. Add gflag validator for `session_idle_timeout_secs` which checks the value when program starts and updating value. The valid range for `session_idle_timeout_secs` is [1, 604800]
Close https://github.com/vesoft-inc/nebula/issues/3305
Incompatible: Users should modify their configuration, i.e. change 0 to a valid value after this PR is merged.
Ref: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout
> Modify default session timeout

- tests/conftest.py
https://discuss.nebula-graph.com.cn/t/topic/6707/2
currently, we just display error information in `cmp_dataset` function, if there's any error not in the function, we cannot find more details.
so add step error hook, and display space if using a random space.
> add step fail hook

- .github/ISSUE_TEMPLATE/question.md
Add a question template for easier management
> Create question template

- src/tools/db-upgrade/DbUpgrader.cpp
- src/tools/db-upgrade/DbUpgrader.h
- src/tools/db-upgrade/DbUpgraderTool.cpp
- src/tools/db-upgrade/NebulaKeyUtilsV1.cpp
- src/tools/db-upgrade/NebulaKeyUtilsV1.h
support specify partId mode in upgrade tool
> support specify partId mode

- src/graph/visitor/EvaluableExprVisitor.h
Fix `EvaluableExprVisitor::visitBinaryExpr`.
That is same as `FindAnyNonEvaluableLeafExpr`. 
Can the implementation of `EvaluableExprVisitor` be unified to `FindVisitor`?
No need to change.
> small fix for EvaluableExprVisitor

- src/graph/optimizer/rule/CollapseProjectRule.cpp
- src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
- src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
- src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
- src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.cpp
- src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.cpp
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/util/FTIndexUtils.cpp
- src/graph/util/FTIndexUtils.h
- src/graph/validator/FindPathValidator.cpp
- src/graph/validator/MutateValidator.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- src/mock/MockCluster.h
- src/parser/Clauses.cpp
- src/parser/Clauses.h
Move the header-file-include to optimize compilation dependencies.
Maybe we could do same things for other header files, especially `Base.h`,`xxxUtil.h`,etc.
No need to change.
> small optimization to avoid recompilation

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
enhancement the issue template
>     NONE                                                            `
> enhancement issue template

- src/meta/processors/index/DropEdgeIndexProcessor.cpp
- src/meta/processors/index/DropTagIndexProcessor.cpp
- tests/tck/features/index/TagEdgeIndex.feature
- [☑️] bug
fix https://github.com/vesoft-inc/nebula/issues/3375#ref-issue-1071263475
https://github.com/vesoft-inc/nebula/issues/3375#ref-issue-1071263475
> checkTypeBeforeDropIndex

- src/common/memory/MemoryUtils.cpp
Fixes reading memory stats under cgroup v2.
https://github.com/vesoft-inc/nebula/issues/3278
memory.max return 'max' as string when no --memory flag provided to container on startup.
What should I do about it?
> Condition memory checks on cgroup version.

- src/common/utils/MetaKeyUtils.cpp
- src/common/utils/MetaKeyUtils.h
- src/common/utils/test/MetaKeyUtilsTest.cpp
- src/kvstore/test/DiskManagerTest.cpp
add functions to parse host, spaceId and path in diskPartsKey, and fix parseDiskPartsSpace().
add unit test for MetaUtilKeys and DiskManager
https://github.com/vesoft-inc/nebula/pull/3369
> parse diskPartsKey and add unit test

- src/graph/validator/GoValidator.cpp
- tests/tck/features/go/GO.feature
Fix inconsistent variable in yield and from clause.
[https://github.com/vesoft-inc/nebula/issues/3210](https://github.com/vesoft-inc/nebula/issues/3210)
`
> fix inconsistent variable in yield and from clause

- src/common/graph/ExecutionResponseOps-inl.h
- src/common/graph/Response.h
- src/interface/storage.thrift
Fix the latency type in the `executionResponse`. The inconsistent datatype of latency between the definition in `thrift` file and `Response.h` causes client transport `invalid data length`error.
This PR https://github.com/vesoft-inc/nebula/pull/2858 only modified the `latency` in the `thrift` file but left other definitions behind.
> Fix the latency type in the executionResponse

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/test/RaftCase.cpp
I am reviewing current implementation,  some issues are found:
1. We didn't save the info of voting for myself when start formal election, which could lead to split brain: 
* There are ABCDE 5 replicas, and BC vote for A.
* If A does not voted itself, another host could be the leader, for example, E could be the leader with votes from ADE.
2. #3322 has missed one rollback, leader will check whether term/role changed after we get AppendLogResponse, if failed, we need to rollback, otherwise, we can't write any logs to wal since `lastLogId_ != wal_->lastLogId()`.
3. When we start up, if `lastLogId_ < committedLogId_`, only lastLogId_ is set to committedLogId_.
And some minor changes, set `leader_` whenever term changed, this is a prepare for later AppendLogs refactor.
> [Raft] fix some remaining problems after pre-vote merged

- src/storage/exec/IndexScanNode.h
fix compilation error
[ 44%] Building CXX object src/graph/optimizer/CMakeFiles/optimizer_obj.dir/OptGroup.cpp.o
In file included from /home/eric.fang/nebula-ent/src/storage/exec/IndexEdgeScanNode.h:8:0,
from /home/eric.fang/nebula-ent/src/storage/index/LookupProcessor.cpp:15:
/home/eric.fang/nebula-ent/src/storage/exec/IndexScanNode.h: In lambda function:
/home/eric.fang/nebula-ent/src/storage/exec/IndexScanNode.h:261:25: error: unused variable 'iter' [-Werror=unused-variable]
auto [iter, result] = suffixSet.insert(std::move(suffix));
^
[ 45%] Building CXX object src/graph/executor/CMakeFiles/executor_obj.dir/query/DedupExecutor.cpp.o
[ 45%] Building CXX object src/storage/CMakeFiles/storage_admin_service_handler.dir/admin/RebuildEdgeIndexTask.cpp.o
cc1plus: all warnings being treated as …
> fix unused variable

- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/Unwind.feature
- tests/tck/features/match/With.feature
refer to https://discuss.nebula-graph.com.cn/t/topic/6742/8
> disable agg function in unwind clause

- src/daemons/StorageDaemon.cpp
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
- src/storage/transaction/TransactionManager.cpp
In short: 
1. let's say we(storage server) have a thread running some task.
2. user send kill SIGINT signal, linux schedule the signal handler at the thread we talked about.
3. now, we interrupt the previous task, executing the signal handler, 
it calls storage server->stop()
trying to clear everything storage server has(also include this thread!!!!). 
4. Then we stuck.
[Storage hang at exit #3434](https://github.com/vesoft-inc/nebula/issues/3434)
> simplify storage SIGINT signal handler

- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
normally, string like "zone127.0.0.1_111" is illegal for name_label, this pr is to make these illegal strings in `` could be legal for name_label.
> LABEL in could be any string

- src/parser/parser.yy
- src/parser/scanner.lex
- tests/tck/features/schema/Schema.feature
Schema support mixed Chinese and English
```
CREATE TAG  队伍(名s字ss1 string);
CREATE TAG `队   伍；`(`名s字ss1` string);
```
close #3426 
> Schema support mixed Chinese and English

- src/graph/validator/GoValidator.cpp
fix    https://github.com/vesoft-inc/nebula-ent/issues/361
> fix unused varaible

- src/clients/meta/MetaClient.cpp
- src/interface/meta.thrift
- src/meta/processors/admin/VerifyClientVersionProcessor.cpp
- src/meta/test/VerifyClientVersionTest.cpp
There are two versions here. 
One is the protocol version in thrift, which is used to verify compatibility through the whitelist; 
the other is the packaged version, which is tag or datetime-nightly.
+-------------+-------+----------+-----------+--------------+----------------+
| Host               | Port     | Status      | Role            | Git Info Sha     | Version               |
+-------------+-------+----------+-----------+--------------+----------------+
| "127.0.0.1"     | 21079 | "ONLINE" | "STORAGE" | "75f11121"    | "datetime-nightly" |
+-------------+-------+----------+-----------+--------------+----------------+
closes #3479 
> save client version

- src/clients/meta/MetaClient.cpp
> Send HB to meta leader

- src/clients/meta/MetaClient.cpp
if  the storage does not register to the cluster, it would return `E_MACHINE_NOT_FOUND`, and would always send heartbeat to the follower.
a little ugly
1. if run `add host` with the storage, it will be ok after updateLeader.
2. if not, it would always update leader, and send heartbeat to meta randomly.
> fix add hosts

- src/parser/parser.yy
- tests/tck/features/aggregate/Agg.feature
- tests/tck/features/bugfix/MatchUsedInPipe.feature
- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
- tests/tck/features/match/MatchById.IntVid.feature
- tests/tck/features/match/MatchById.feature
- tests/tck/features/match/MatchGroupBy.feature
- tests/tck/features/match/PipeAndVariable.feature
- tests/tck/features/match/StartFromAnyNode.IntVid.feature
- tests/tck/features/match/StartFromAnyNode.feature
- tests/tck/features/match/Unwind.feature
- tests/tck/features/match/VariableLengthPattern.feature
- tests/tck/features/match/VariableLengthPattern.intVid.feature
disable mixed usesage of cypher & ngql
close https://github.com/vesoft-inc/nebula/issues/3477
> disable mixed usage of cypher & ngql

- src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
- tests/tck/features/lookup/TagIndexFullScan.feature
Fix crash caused by filter stated in https://github.com/vesoft-inc/nebula/issues/3524
Close https://github.com/vesoft-inc/nebula/issues/3524
> Fix crush caused by OptimizeTagIndexScanByFilterRule

- src/common/expression/AggregateExpression.cpp
- src/common/expression/ArithmeticExpression.cpp
- src/common/expression/AttributeExpression.cpp
- src/common/expression/CaseExpression.cpp
- src/common/expression/ContainerExpression.cpp
- src/common/expression/FunctionCallExpression.cpp
- src/common/expression/LabelAttributeExpression.cpp
- src/common/expression/ListComprehensionExpression.cpp
- src/common/expression/LogicalExpression.cpp
- src/common/expression/PredicateExpression.cpp
- src/common/expression/ReduceExpression.cpp
- src/common/expression/RelationalExpression.cpp
- src/common/expression/SubscriptExpression.cpp
- src/common/expression/TextSearchExpression.cpp
- src/common/expression/TypeCastingExpression.cpp
- src/common/expression/UnaryExpression.cpp
- src/common/expression/VariableExpression.cpp
- src/common/stats/StatsManager.cpp
- src/kvstore/raftex/RaftPart.h
- src/meta/stats/MetaStats.cpp
- src/parser/SequentialSentences.h
- tests/tck/features/admin/Sessions.feature
- third-party/install-gcc.sh
> fix ci crash

- src/common/utils/test/MetaKeyUtilsTest.cpp
- src/graph/service/CloudAuthenticator.cpp
- src/kvstore/NebulaSnapshotManager.cpp
- src/kvstore/test/NebulaListenerTest.cpp
- src/kvstore/test/RocksEngineTest.cpp
- src/meta/MetaVersionMan.cpp
- src/meta/http/MetaHttpReplaceHostHandler.cpp
- src/meta/processors/admin/CreateBackupProcessor.cpp
- src/meta/processors/admin/CreateSnapshotProcessor.cpp
- src/meta/test/RestoreProcessorTest.cpp
- src/storage/BaseProcessor-inl.h
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteTagsProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/storage/test/LookupIndexTest.cpp
- src/storage/test/ScanEdgePropBenchmark.cpp
> Fix deprecated function usage

- src/graph/executor/admin/SessionExecutor.cpp
- src/graph/executor/admin/SessionExecutor.h
- src/graph/planner/plan/Admin.h
- src/graph/session/GraphSessionManager.cpp
- src/graph/session/GraphSessionManager.h
- src/graph/validator/AdminValidator.cpp
- src/interface/meta.thrift
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- tests/conftest.py
- tests/job/test_session.py
- tests/tck/conftest.py
- tests/tck/features/admin/Sessions.feature
- tests/tck/slowquery/KillSlowQueryViaDiffrentService.feature
- tests/tck/slowquery/KillSlowQueryViaSameService.feature
1. Add `SHOW LOCAL SESSIONS` command to list the sessions of the current graph node
2. [**Incompatibility**] Deprecate `SHOW ALL QUERIES`. Now `SHOW QUERIES` lists all queries in the whole cluster and `SHOW LOCAL QUERIES` lists all queries in the current graph node.
Depends on https://github.com/vesoft-inc/nebula/pull/3486 
Close https://github.com/vesoft-inc/nebula/issues/3547
> Add show local sessions command

- src/graph/visitor/ExtractFilterExprVisitor.cpp
> fix format

- src/interface/common.thrift
- src/interface/raftex.thrift
- src/kvstore/Listener.cpp
- src/kvstore/Listener.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/raftex/CMakeLists.txt
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/Host.h
- src/kvstore/raftex/RaftLogIterator.cpp
- src/kvstore/raftex/RaftLogIterator.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/TestShard.cpp
- src/kvstore/raftex/test/TestShard.h
- src/kvstore/test/NebulaListenerTest.cpp
- src/kvstore/wal/AtomicLogBuffer.h
- src/kvstore/wal/WalFileIterator.cpp
- src/kvstore/wal/WalFileIterator.h
Change notes:
1. Main change is in  `processAppendLogRequest`
A brief flow as follows (not exactly same in code):
To achieve this goal, some others need to be modified:
* In AppendLogRequest, we need to carry each log's term (which is missing previously), so as a proper iterator.
* For similarity, we need to return `committedLogId` and `committedLogTerm` in resp. But committedLogTerm is missing previously, so I add one.
2. We need to make sure `lastLogId_ == wal_->lastLogId()` in almost every case (except leader is replicating), we did this by calling `wal_->rollbackToLog`, since we handle `AppendLog` correctly, we don't need to rollback anymore, just set `lastLogId_ = wal_->lastLogId()` is enough.
3. All request and resp should carry the term, step down as follower when a higher term …
> [Raft] refactor processAppendLogRequest

- src/codec/RowWriterV2.cpp
- src/graph/executor/admin/SpaceExecutor.cpp
- src/graph/service/GraphService.cpp
- src/graph/service/QueryInstance.cpp
- tests/tck/features/bugfix/RoundFloat.feature
Close https://github.com/vesoft-inc/nebula/issues/3473
> round the float/double when insert it to integer column

- src/daemons/CMakeLists.txt
- src/daemons/StandAloneDaemon.cpp
Fix standalone cmake.
storage_common_obj is splited into 
$<TARGET_OBJECTS:graph_stats_obj>
$<TARGET_OBJECTS:meta_client_stats_obj>
$<TARGET_OBJECTS:storage_client_stats_obj>
Which is not applyed into standalone version
> Fix cmake statobj for standalone version

- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/Host.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
Close https://github.com/vesoft-inc/nebula/issues/3564
> fix parser memeory leak

- src/common/utils/IndexKeyUtils.cpp
- src/common/utils/IndexKeyUtils.h
- src/storage/admin/RebuildEdgeIndexTask.cpp
- src/storage/admin/RebuildTagIndexTask.cpp
- src/storage/exec/UpdateNode.h
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddEdgesProcessor.h
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.h
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/tools/db-upgrade/DbUpgrader.cpp
- src/tools/db-upgrade/DbUpgrader.h
- tests/tck/features/index/Index.feature
rebuild tag index with old schema version value
https://github.com/vesoft-inc/nebula/issues/3274#ref-issue-1046564795
> rebuild index for new prop

- src/daemons/GraphDaemon.cpp
- src/daemons/StandAloneDaemon.cpp
Fix Graph and Standalone: InitStat's should be done after glog is inited.
> Fix stats init order

- src/graph/executor/Executor.cpp
- src/graph/optimizer/rule/IndexScanRule.cpp
- src/graph/service/GraphService.cpp
- src/graph/service/QueryInstance.cpp
- src/graph/session/ClientSession.cpp
- src/graph/stats/GraphStats.cpp
- src/graph/stats/GraphStats.h
Co-authored-by: Yee <2520865+yixinglu@users.noreply.github.com>
Co-authored-by: Sophie <84560950+Sophie-Xie@users.noreply.github.com>
> Add more space level metrics

- src/common/stats/StatsManager.cpp
- src/common/stats/test/StatsManagerTest.cpp
- src/storage/test/CMakeLists.txt
Adjust the name format of space level metrics according to the cloud team's feedback
> Adjust the name format of space level metrics

- src/graph/validator/FetchEdgesValidator.cpp
- src/graph/validator/FetchVerticesValidator.cpp
- src/graph/validator/FindPathValidator.cpp
- src/graph/validator/GoValidator.cpp
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/test/GroupByValidatorTest.cpp
- src/graph/validator/test/LookupValidatorTest.cpp
- src/graph/validator/test/QueryValidatorTest.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- tests/tck/features/aggregate/Agg.feature
- tests/tck/features/go/GroupbyLimit.IntVid.feature
- tests/tck/features/go/GroupbyLimit.feature
- tests/tck/features/yield/yield.IntVid.feature
- tests/tck/features/yield/yield.feature
> disable agg function in ngql's yield clause & where clause

- src/graph/executor/StorageAccessExecutor.h
- src/interface/common.thrift
- src/interface/raftex.thrift
- src/kvstore/Listener.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/Host.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/RaftexService.cpp
- src/kvstore/raftex/SnapshotManager.cpp
- src/kvstore/raftex/test/LogAppendTest.cpp
- src/kvstore/raftex/test/LogCASTest.cpp
- src/storage/admin/AdminProcessor.h
Description:
This is a prepare to adjust log level later. Previously we have an extra `ErrorCode` in `raftex.thrift`, which is unified to `common.ErrorCode` as well. And there in another "code" (notorious `AppendLogResult`) in RaftPart, this PR also removed it.
All raft error code is unified now.
Tests:
Affects:
No related
> Unify raft error code

- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/kvstore/test/RocksEngineConfigTest.cpp
Description:
support bottommost level compression
Tests:
Affects:
> support bottom level compression

- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
Issue(s) number: https://github.com/vesoft-inc/nebula/issues/3609
Description:
Service crash when exit.
The crash is caused by the glog lock variable (static variable called `vmodule_lock`) being destructed before thriftServer.
Tests:
Affects:
> Fixed the bug
> fix service crash

- .github/workflows/rc.yml
- package/package.sh
This branch parameter is used when we have 3 nebula repos, it's useless at present. Fix the rc workflow version number when packaging.
> Cleanup branch param in package script

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
none
Description:
1. Remove unnecessary local variables
2. Substitute `std::map` with `folly::ConcurrentHashMap`
Tests:
Affects:
> Enhance login password check

- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddEdgesProcessor.h
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.h
- tests/tck/features/insert/InsertIfNotExists.feature
- tests/tck/features/lookup/LookUp.feature
close https://github.com/vesoft-inc/nebula/issues/3193
Description:
Tests:
Affects:
> fix_batch_insert_problem

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/mock/MockCluster.h
- src/storage/StorageServer.cpp
- src/tools/storage-perf/StoragePerfTool.cpp
- [X ] bug
Description:
It is reported if not "add host" metaClient will stuck at "waitForMetaready()" and can't stop. 
This pr try to fix this. 
waitForMetaready() will detect a flag in each loop, before retry. Set this flag. 
Because no UT call metaClient.notifyStop() before, and it is hard to know which UT will affect by this, just run CI 
Tests:
Affects:
> add notifyStop() for metaClient

- tests/common/utils.py
Description:
Modified in https://github.com/vesoft-inc/nebula/pull/3620
We'd better to retry in storage client.
Tests:
Affects:
> Fix retry in tck.

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/storage/test/ChainTestUtils.h
- src/storage/test/KillQueryTest.cpp
Use RCU replace ThreadLocal in MetaClient
https://github.com/vesoft-inc/nebula/issues/3373
https://github.com/vesoft-inc/nebula/issues/3497
At the beginning, we found that storage would crash after running for a long time (a large number of insert edge operations were performed at the same time). At the same time, Storage's memory usage will be very high. So we guess that there is a memory leak after the system OOM. However, it was later discovered that this is not the problem. Even if the Storage does not have OOM, it will crash when it is stopped. All coredump stacks destruct a static thread variable when the thread exits. This is a variable of type folly::SingletonThreadLocal introduced in MetaClient.
At the same time, in another scenario, if compaction is triggered when storage is …
> Issue3373 storage exit crash

- src/common/function/FunctionManager.cpp
- src/common/function/test/FunctionManagerTest.cpp
- tests/tck/features/function/coalesce.feature
close #3522
Description:
The last implementation is wrong, because the parameter is `List` instead of unfixed param
use unfixed param
Tests:
Affects:
> Fix coalesce bug

- src/parser/parser.yy
Description:
Already check in where_clause
Tests:
Affects:
> delete double check agg in where clause

- src/meta/processors/parts/CreateSpaceProcessor.cpp
> fix meta crash after create space

- src/clients/meta/MetaClient.cpp
- src/common/graph/Response.h
- src/interface/common.thrift
- src/meta/processors/parts/CreateSpaceProcessor.cpp
- src/meta/processors/parts/CreateSpaceProcessor.h
- src/meta/test/ProcessorTest.cpp
https://github.com/vesoft-inc/nebula/issues/3675
Description:
Tests:
Affects:
> fix issue 3675

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- src/graph/util/ExpressionUtils.cpp
- src/graph/visitor/DeduceTypeVisitor.cpp
- src/graph/visitor/test/FilterTransformTest.cpp
- src/graph/visitor/test/RewriteRelExprVisitorTest.cpp
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/match/SeekById.feature
Fix https://github.com/vesoft-inc/nebula/issues/3248
Description:
This PR fixes `filterTransform()` and adds cases.
1. Do not transfer the filter expression if it contains 2 different tagProp expressions i.e. `v.player.name =="abc" && v.player.age == 30`
2. Fix expression overflow check. Do not rewrite the expression if it would cause an overflow.
3. Refactor `rewriteRelExpr()`
4. Return semantic error when the non-addition arithmetic expression contains strings.
```
(root@nebula) [nba]> match (v:player) where v.player.name+'n'=="Tim Duncann" return v
+-----------------------------------------------------+
| v                                                   |
+-----------------------------------------------------+
| ("Tim Duncan" :player{age: 42, name: "Tim Duncan"}) | …
```
> Fix expression rewrite

- src/meta/processors/zone/DivideZoneProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/meta/test/ProcessorTest.cpp
Issue(s) number: https://github.com/vesoft-inc/nebula/issues/3670
Description:
Tests:
Affects:
> fix divide zone should be failed if two zones use the same host

- src/daemons/MetaDaemonInit.cpp
- src/meta/MetaVersionMan.cpp
- src/meta/MetaVersionMan.h
- src/meta/upgrade/MetaDataUpgrade.cpp
- src/meta/upgrade/MetaDataUpgrade.h
> fix meta upgrade for multi instance

- src/codec/RowReaderV2.h
- src/graph/planner/match/MatchPlanner.h
- src/meta/processors/Common.h
- src/meta/processors/index/FTIndexProcessor.cpp
- src/meta/processors/parts/CreateSpaceAsProcessor.cpp
- src/meta/processors/schema/AlterEdgeProcessor.cpp
- src/meta/processors/schema/AlterTagProcessor.cpp
- src/meta/processors/schema/CreateEdgeProcessor.cpp
- src/meta/processors/schema/CreateTagProcessor.cpp
- src/meta/processors/schema/DropEdgeProcessor.cpp
- src/meta/processors/schema/DropTagProcessor.cpp
- src/meta/processors/schema/GetEdgeProcessor.cpp
- src/meta/processors/schema/GetTagProcessor.cpp
- src/meta/processors/schema/ListEdgesProcessor.cpp
- src/meta/processors/schema/ListTagsProcessor.cpp
Issue(s) number:  close #3376
Description:
Merge two lock
Tests:
Affects:
> Fix race of create tag and edge

- src/meta/MetaVersionMan.cpp
- src/meta/processors/zone/DivideZoneProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/meta/test/ProcessorTest.cpp
> Support divide from itself

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftexService.cpp
- src/meta/processors/job/BalanceJobExecutor.cpp
- src/meta/processors/job/BalanceJobExecutor.h
- src/meta/processors/job/BalancePlan.cpp
- src/meta/processors/job/BalancePlan.h
- src/meta/processors/job/BalanceTask.h
- src/meta/processors/job/DataBalanceJobExecutor.cpp
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.h
- src/meta/test/BalancerTest.cpp
- src/meta/test/TestUtils.h
> Balance fix

- src/daemons/MetaDaemonInit.cpp
- src/meta/MetaVersionMan.cpp
- src/meta/MetaVersionMan.h
- src/meta/upgrade/MetaDataUpgrade.cpp
- src/meta/upgrade/MetaDataUpgrade.h
Conflicts:
src/meta/MetaVersionMan.cpp
Description:
Tests:
Affects:
> cherry pick: fix meta upgrade for multi instance (#3734)

- src/meta/processors/index/FTIndexProcessor.cpp
- src/meta/test/IndexProcessorTest.cpp
- src/meta/test/TestUtils.h
* fix bug: the same tagId/edgetype under different spaces, failed to create fulltext indexes
Description:
cherry pick  https://github.com/vesoft-inc/nebula/pull/3747
Tests:
Affects:
> cherry pick: Fix create fulltext index failed (#3747)

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/codec/RowWriterV2.cpp
- src/codec/test/ResultSchemaProvider.cpp
- src/codec/test/ResultSchemaProvider.h
- src/codec/test/SchemaWriter.cpp
- src/common/meta/NebulaSchemaProvider.cpp
- src/common/meta/NebulaSchemaProvider.h
- src/common/meta/SchemaProviderIf.h
- src/graph/util/SchemaUtil.cpp
- src/graph/util/SchemaUtil.h
- src/graph/validator/MaintainValidator.cpp
- src/graph/validator/MutateValidator.cpp
- src/mock/MockData.cpp
- src/storage/exec/QueryUtils.h
- src/storage/exec/UpdateNode.h
- src/storage/test/IndexWithTTLTest.cpp
- src/storage/transaction/ChainAddEdgesProcessorLocal.cpp
cherry pick https://github.com/vesoft-inc/nebula/pull/3666
Description:
Tests:
Affects:
> fix memory increase

- src/common/meta/Common.h
- src/graph/validator/AdminValidator.cpp
- src/graph/validator/MaintainValidator.cpp
- src/graph/validator/MaintainValidator.h
- src/graph/validator/Validator.cpp
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/MaintainSentences.cpp
- src/parser/MaintainSentences.h
- src/parser/parser.yy
- tests/admin/test_space.py
- tests/common/nebula_service.py
- tests/maintain/test_zone.py
- tests/tck/features/admin/Hosts.feature
- tests/tck/features/schema/Comment.feature
> Disable zone commands

- src/kvstore/raftex/Host.cpp
Issue(s) number: https://github.com/vesoft-inc/nebula/issues/3671
Description:
if one host succeed but others failed, raft part would try again for all hosts, including the successful host, which would lead the error E_RAFT_NO_WAL_FOUND and fall into infinite loop
Tests:
Affects:
> raft fix: fix always loop when no log need to send

- src/graph/planner/SequentialPlanner.cpp
- src/graph/planner/SequentialPlanner.h
- src/graph/planner/plan/PlanNode.h
- src/graph/validator/SequentialValidator.cpp
- src/graph/validator/Validator.cpp
- src/graph/validator/Validator.h
- src/kvstore/raftex/Host.cpp
- tests/tck/features/match/Base.feature
- tests/tck/features/match/MultiLineMultiQueryParts.feature
> Cherry pick v3.0.0 0127

- src/parser/MaintainSentences.cpp
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- tests/tck/features/admin/Hosts.feature
till now, we should use STRING to represent a zone, 
e.g.  create space test (...) on "zone1","zone2"  ,  we should always use double quotation mark, the original reason of using STRING is to handle some illegal name like "127.0.0.1zone_1111", and this pr https://github.com/vesoft-inc/nebula/pull/3424 could solve the problem. for legal name, we don't need to use double quotation mark.
e.g   create space test (...) on zone1, zone2
and for illegal name, we could do it like this 
create space test (...) on \`127.0.0.1zone_1111\`, \`127.0.0.1zone_2222\`
Description:
Tests:
Affects:
> replace STRING to name_label for zone's name

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
Close #3854
The role in meta client is `UNKNOWN` by default, and many tools use the default `MetaClientOptions`, which makes the host info is `Host("", 0)`, and the info will be write to meta if we send heartbeat. 
Just skip heartbeat when role is unknown
Tests:
Affects:
> skip heartbeat when role in meta client is not set

- src/common/time/TimeUtils.cpp
- src/common/time/parser/DatetimeReader.cpp
- src/common/time/parser/DatetimeReader.h
- src/common/time/parser/datetime_parser.yy
- src/common/time/parser/test/DateTimeParserTest.cpp
Close https://github.com/vesoft-inc/nebula/issues/3840
Tests:
Affects:
> Remove unused code.

- src/graph/executor/query/AppendVerticesExecutor.cpp
- tests/tck/features/match/Base.feature
The case `0-hop`, 3.0's performance is much lower than 2.6
```
MATCH (v: Person) return v
```
While the case `1-hop` and `2-hop`, 3.0's performance is flat with 2.0
The execution plans are here:
[2.6.txt](https://github.com/vesoft-inc/nebula/files/8020543/2.6.txt)
[3.0.txt](https://github.com/vesoft-inc/nebula/files/8020544/3.0.txt)
> Try to improve the performance of appendVertices

- .github/workflows/rc.yml
in 2.6.x, nebula version is `2.6.2`, not `v2.6.2`
because we use code in package.sh
```
version=$(git describe --exact-match --abbrev=0 --tags | sed 's/^v//')
```
```
[vesoft@qa-60 tmp]$ nebula-graph-2.6.2.el7.x86_64/bin/nebula-graphd --version
nebula-graphd version 2.6.2, Git: d113f4a, Build Time: Jan 26 2022 16:57:25
This source code is licensed under Apache 2.0 License.
```
but now in v3 
```
[vesoft@qa-tools nebula_multiple_sf1]$ ./nebula1/bin/nebula-graphd --version
nebula-graphd version v3.0.0, Git: af99990, Build Time: Jan 27 2022 22:47:10
This source code is licensed under Apache 2.0 License
```
> keep consistent with 2.6.x

- src/graph/service/GraphService.cpp
- src/graph/session/ClientSession.cpp
- src/graph/session/ClientSession.h
- src/graph/session/GraphSessionManager.cpp
- src/graph/session/GraphSessionManager.h
https://github.com/vesoft-inc/nebula/issues/3858
Just comment graph::session module.
Tests:
Affects:
> comment the graph::session module (Part 1)

- src/common/stats/StatsManager.cpp
- src/common/stats/StatsManager.h
close #3869 
Temporarily use Concurrenthashmap to fix thread unsafety issues. There is a certain performance penalty.
Tests:
Affects:
None
> fix issue 3869

- src/clients/meta/MetaClient.cpp
#3889
Crash because of out-of-range access in vector.
The byte order of schema version in meta is not same as numerical order.
| version | (INT64_MAX - version) in hex | rocksdb (INT64_MAX - version) little endian | 
|-|-|-|
| 0 | ff ff ff ff ff ff ff ff | ff ff ff ff ff ff ff ff |
| 1 | ff ff ff ff ff ff ff fe | fe ff ff ff ff ff ff ff |
|...|...|...|
|255| ff ff ff ff ff ff ff 00 | 00 ff ff ff ff ff ff ff |
|256| ff ff ff ff ff ff fe ff | ff fe ff ff ff ff ff ff |
|...|...|...|
The output order in rocksdb when we prefix scan is quite complicated, just say a simple example with 257 schema versions in range `[0, 256]`, the order will be: `255 254 253 ... 3 2 1 256 0`
Just resize to make sure the vector is valid.
Tests:
Affects:
Please confirm whether to be reflected in release notes and …
> fix crash when schema version is greater than 255

- src/graph/planner/match/VertexIdSeek.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- tests/tck/features/match/MatchById.feature
> fix match multiple id error

- src/interface/common.thrift
- src/kvstore/raftex/RaftPart.cpp
It is nature to return E_RAFT_TERM_OUT_OF_DATE or LEADER_CHANGE
when raft check leader, but this will make caller believe the append failed.
however, this log is replicated to followers(written in follower's WAL)
and the follower may become leader (use that WAL)
which means this log may eventually commit succeeded.
Tests:
Affects:
n/a
> if leader changed during raft::appendLog() RPC, use a different error code

- src/kvstore/NebulaStore.cpp
some user complain why a dropped space still exist in disk. 
Discussed before, just give this PR.  auto remove invalid space. 
Tests:
Affects:
n/a
> set auto_remove_invalid_space default true

- src/graph/planner/match/MatchClausePlanner.cpp
- tests/tck/features/bugfix/CrashWhenNullPathExpr.feature
> Fix crash of null path expression.

- src/tools/db-upgrade/DbUpgrader.cpp
fix upgrade tool 3.0,
When there is no tag under the space, the upgrade tool core.
coredump as follows:
```
I20220221 15:28:40.337662 281523 DbUpgrader.cpp:1081] Copy space id 133 wal file begin
I20220221 15:28:40.548403 281523 DbUpgrader.cpp:1228] Copy space id 133 wal file success
I20220221 15:28:40.548442 281523 DbUpgrader.cpp:1072] Path /data/nebula/storaged_backup space id 133 compaction begin
E20220221 15:28:41.543736 281518 RocksEngine.cpp:426] Ingest Failed: Invalid argument: external_files[0] is empty
F20220221 15:28:41.543795 281518 DbUpgrader.cpp:996] Faild upgrade 2:3 when ingest sst file:-8000
*** Check failure stack trace: ***
*** Aborted at 1645428522 (Unix time, try 'date -d @1645428522') ***
*** Signal 6 (SIGABRT) (0x449aa) received by PID 281002 (pthread TID …
```
> fix ingest 0 file error in upgrade tool 3.0

- src/kvstore/DiskManager.cpp
- src/kvstore/DiskManager.h
> use rcu in DiskManager

- src/graph/optimizer/rule/CollapseProjectRule.cpp
- tests/tck/features/match/With.feature
- tests/tck/features/optimizer/CollapseProjectRule.feature
https://github.com/vesoft-inc/nebula/issues/3930
Enhance ColumnPruning of Project-Project pattern.
Depended by https://github.com/vesoft-inc/nebula/pull/3750.
Some ldbc test cases need this pr to optimize memory usage and performance.
Tests:
Affects:
> [Optimizer] enhance ColumnPruning

- src/graph/planner/plan/PlanNodeVisitor.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/visitor/PropertyTrackerVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.h
> [SIMPLE]Fix prune properties

- src/storage/StorageServer.h
- src/storage/http/StorageHttpDownloadHandler.h
- src/storage/http/StorageHttpIngestHandler.h
- src/storage/http/StorageHttpStatsHandler.h
- src/storage/index/LookupProcessor.h
Description:
just add some comments
Tests:
Affects:
n/a
> add comments and change some log level for storage root / http / kv .. 

- src/storage/admin/StatsTask.cpp
#3649 
Tests:
Affects:
vertex count in `show stats` will counted by vertex key instead of tag key.
> fix Issue3649

- src/graph/planner/plan/PlanNodeVisitor.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/visitor/PrunePropertiesVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.h
- tests/tck/features/optimizer/PrunePropertiesRule.feature
For vertex/edge, only vid/eid is used to dedup
> Prune properties/no need to collect columns of dedup

- .github/workflows/rc.yml
change the name of source code
before : nebula-x.y.z.tar.gz
after : nebula-graph-x.y.z.tar.gz
Tests:
Affects:
> None
> Change the name of source code zip

- src/storage/GraphStorageLocalServer.cpp
This will crash the daemon
The request object in lambda function is captured by reference, this will crash the server when this async interface finishes to run and the task in threadManager haven't be executed.
Captured by copy.
Tests:
Affects:
> Fix lambda capture bug in GraphStorageLocalServer

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/service/GraphService.cpp
- src/graph/service/GraphService.h
- src/graph/service/PasswordAuthenticator.cpp
- src/graph/service/PasswordAuthenticator.h
Fix https://github.com/vesoft-inc/nebula/issues/3935
Fix service crash caused by connecting using a pre-v2.6.0 client.
Error message when connecting the v3.0.0 Nebula service with v2.5.0 console:
```
> ./nebula-console -addr 192.168.8.6 -port 29562 -u root -p nebula
2022/02/24 22:01:21 [INFO] connection pool is initialized successfully
2022/02/24 22:01:21 Fail to create a new session from connection pool, fail to authenticate, error: The version of the client sending request from "::ffff:192.168.8.6":49722 is lower than v2.6.0, please update the client.
panic: Fail to create a new session from connection pool, fail to authenticate, error: The version of the client sending request from "::ffff:192.168.8.6":49722 is lower than v2.6.0, please update the client.
goroutine 1 [running]: …
```
> Fix service crash caused by connecting using a pre-v2.6.0 client

- src/clients/meta/MetaClient.cpp
- src/meta/processors/BaseProcessor.h
- src/meta/processors/admin/HBProcessor.cpp
- src/meta/processors/admin/HBProcessor.h
Conflicts:
src/meta/processors/BaseProcessor.h
Tests:
Affects:
> cherry pick: machine not registed should response leader address (#3950)

- src/clients/meta/MetaClient.cpp
> unify leader change and machine not found

- src/graph/service/GraphService.cpp
This PR fixes some problems in 3.0.0 version:
1. To make the version incompatible message clearer.
2. Do client version check before `FLAGS_enable_authorize` check
Tests:
Affects:
> Update error message when connect with an out-of-date client

- src/graph/executor/query/TraverseExecutor.cpp
Remove redundant scope timer.
Tests:
Affects:
> Fix: exec time calculated twice

- .github/workflows/nightly.yml
Reverts vesoft-inc/nebula#4006
Since package.sh already has a version [time]-nightly, this is not necessary.
> Revert "Add version for nightly."

- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/PartManager.h
till now storage remove space by meta info, which does not contain learner, so the learner parts still exist after remove the space,  this will cause core in next balance.
Tests:
Affects:
> remove learner parts when removing space

- src/storage/transaction/ChainAddEdgesLocalProcessor.cpp
- src/storage/transaction/ChainDeleteEdgesLocalProcessor.cpp
- src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
[Edge prop mismatch #3030](https://github.com/vesoft-inc/nebula/issues/3030)
When committing a log. (insert an edge)
If a leader change happened after raft leader succeed replicate logs to majority.
Raft will report  leader changed. 
This will let the caller of raft think that operation failed. 
But actually, this log will be committed eventually. Because the new leader has this log. 
First I import a new error code for this status:
https://github.com/vesoft-inc/nebula/pull/3880
And now, in this pr, when toss meet this new error code, it will treat it as succeeded. 
Tests:
Affects:
> No need to mention it. just fix a bug.
> treat E_RAFT_UNKNOWN_APPEND_LOG as succeeded

- src/meta/processors/job/JobDescription.cpp
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
this pr is to solve two points:
1.  if stop a job quickly when schedule is going to start the job, it may:
the job does not exist in runningJobs_ , but exist in inFlightJobs_, so we can't create a new one even if we stopped it.
2. the start time of the job is 0 before starting, so it would always be expired through the calculation of duration, the job's info  would be erased and we can't see it in show list.
Tests:
Affects:
> fix bug stop job before it start

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
- docker/README.md
1. revert https://github.com/vesoft-inc/nebula/pull/4068, seems cannot use docker cache when using buildx.
2. fix https://github.com/vesoft-inc/nebula/issues/4037
> fix version in docker image and Revert https://github.com/vesoft-inc/nebula/pull/4068

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/service/GraphService.cpp
- src/graph/service/GraphService.h
https://github.com/vesoft-inc/nebula/pull/4080
https://github.com/vesoft-inc/nebula/pull/4075
https://github.com/vesoft-inc/nebula/pull/3939/
cherry pick to v3.0.2
Tests:
Affects:
> cherry pick: 3.0.2

- .github/workflows/rc.yml
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
cherry-pick 
https://github.com/vesoft-inc/nebula/pull/4087
> cherry pick: fix docker image version(typo) (#4087)

- src/common/thread/test/GenericThreadPoolTest.cpp
- src/common/thread/test/GenericWorkerTest.cpp
- src/graph/executor/test/StorageServerStub.cpp
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftexService.cpp
- src/kvstore/raftex/RaftexService.h
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/mock/LocalServer.h
- src/mock/MockCluster.h
- src/storage/GraphStorageLocalServer.cpp
- src/storage/GraphStorageLocalServer.h
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
There are many cases that storage can't exit gracefully, we may stuck forever or just crash... There are several reason:
1. There are four thrift server (raft/storage/admin/internal), all thread pool shared (both IOThreadPool and ThreadManager), so if the thread pool is not correctly joined, crash...
2. There are other important components for example `kvstore`, `RaftPart`, `TaskManager`, `MetaClient`, the thread pool is the same one in rpc server. And the relationship between them could be quite complicated.
1. Start thrift server with `setup`/`cleanUp`, instead of calling `serve`/`stop`. In short words, when we call `stop`, `serve` will be out of scope, and `cleanUp` will be triggered. If we concurrently call `stop` of several ThriftServer, we may crash because the thread pool are …
> Refactor StorageServer stop

- .github/actions/tagname-action/action.yml
- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
- .github/workflows/rc.yml
- .github/workflows/release.yml
- .gitignore
close #3815 
when releasing a nebula PATCH version(z version of x.y.z), create git tag on one same branch rather than a new branch, such as:
```text
release-3.2   -----+----------+------- branch
\          \
v3.2.0    v3.2.1   tag
```
use github action manual trigger to package rc version.
Tests:
Affects:
None
None
> Trigger release workflow manually

- src/meta/test/JobManagerTest.cpp
- src/parser/parser.yy
> fix memory leak

- src/graph/planner/match/VertexIdSeek.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- src/graph/visitor/VidExtractVisitor.h
- tests/tck/features/yield/parameter.feature
Fixed this case:
```cypher
:param p3 => "player100"
:param p8 => "player101"
:param p7 => {"a":{"b":{"c":"Tim Duncan","d":[1,2,3,true,"player100"]}}}
MATCH (v) WHERE id(v) == $p3
RETURN id(v) AS v
MATCH (v) WHERE id(v) IN [$p3,$p8]
RETURN id(v) AS v
MATCH (v) WHERE id(v) == $p7.a.b.d[4]
RETURN id(v) AS v
MATCH (v) WHERE id(v) IN $p7.a.b.d
RETURN id(v) AS v
```
To make right part of the expression evaluated in `src/graph/visitor/VidExtractVisitor.cpp`
Tests:
Affects:
Fixed the bug on parameters for `id(n) == $var ` , `id(n) IN [$var]`, `id(n) == $var.foo.bar`, `id(n) IN $var.foo.bar`
> Param MATCH vid seek fix

- .gitignore
- package/package.sh
Temporarily disable packaging of the nebula-console.
The normal packaging process must artificially ensure that both nebula and nebula-console have available and consistent branches before packaging, but due to the dependencies between nebula and nebula-console, some errors will reduce the efficiency of ci.
Just disable the packaging switch related with nebula-console.
Tests:
Affects:
> disable console pkg

- src/common/function/FunctionManager.cpp
- src/common/function/FunctionManager.h
- src/common/function/test/FunctionManagerTest.cpp
- src/graph/optimizer/OptimizerUtils.cpp
- tests/tck/features/bugfix/LookupIn.feature
Close https://github.com/vesoft-inc/nebula/issues/4097
There is a bug in the constant folding of function call expressions like `date('2022-03-25')` when checking purity.
Fix purity checking by bonding purity to the number of arity of the function
Tests:
Affects:
> Fix service crash caused by using function call as a part of the filter in `LOOKUP`

- .github/workflows/nightly.yml
This failure is introduced in #4105
Tests:
Affects:
None
> Fix cmake command error in nightly workflow

- .github/workflows/nightly.yml
- package/package.sh
- src/common/function/FunctionManager.cpp
- src/common/function/FunctionManager.h
- src/common/function/test/FunctionManagerTest.cpp
- src/graph/optimizer/OptimizerUtils.cpp
- src/graph/planner/match/VertexIdSeek.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- src/graph/visitor/VidExtractVisitor.h
- src/meta/test/JobManagerTest.cpp
- src/parser/parser.yy
- tests/tck/features/bugfix/LookupIn.feature
- tests/tck/features/yield/parameter.feature
> Cherry pick v3.1.0 (0401-0402)

- .linters/cpp/checkKeyword.py
- scripts/nebula.service
- src/parser/parser.yy
- src/parser/scanner.lex
KW_CLEAR is used as a keyword, so that users cannot directly use 'clear' as LABEL. Therefore, KW_CLEAR is changed to unresolved keyword here.
move KW_CLEAR to unresolved keyword.
Tests:
Affects:
> move KW_CLEAR to unresolved keyword

- src/graph/validator/GroupByValidator.cpp
- tests/tck/features/aggregate/Agg.feature
> Fix group by outputs.

- src/clients/meta/MetaClient.cpp
- src/graph/executor/admin/SpaceExecutor.cpp
- src/graph/validator/GroupByValidator.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
- src/meta/processors/zone/AddHostsProcessor.cpp
- src/meta/processors/zone/DropHostsProcessor.cpp
- src/meta/test/BalancerTest.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/storage/StorageServer.cpp
- tests/common/nebula_service.py
- tests/tck/features/aggregate/Agg.feature
- tests/tck/features/schema/Comment.feature
> Cherry pick v3.1.0 (0408-0411)

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
- package/package.sh
1. there're too many variables when building release package, and when we build nebula in test platform, we should follow these options.
2. just use `package.sh` directly when building release.
> change default variables in release

- src/graph/context/Symbols.cpp
- src/graph/optimizer/OptGroup.cpp
- src/graph/optimizer/OptGroup.h
- src/graph/optimizer/OptRule.cpp
- src/graph/optimizer/OptRule.h
- src/graph/optimizer/Optimizer.cpp
- src/graph/optimizer/rule/CollapseProjectRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformRule.cpp
- src/graph/optimizer/rule/IndexScanRule.cpp
- src/graph/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
- src/graph/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
- src/graph/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
- src/graph/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
- src/graph/optimizer/rule/PushFilterDownGetNbrsRule.cpp
- src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
- src/graph/optimizer/rule/PushFilterDownScanVerticesRule.cpp
- src/graph/optimizer/rule/PushLimitDownGetNeighborsRule.cpp
- src/graph/optimizer/rule/PushLimitDownIndexScanRule.cpp
- src/graph/optimizer/rule/PushLimitDownProjectRule.cpp
- src/graph/optimizer/rule/PushLimitDownScanAppendVerticesRule.cpp
- src/graph/optimizer/rule/PushLimitDownScanEdgesAppendVerticesRule.cpp
- src/graph/optimizer/rule/PushStepLimitDownGetNeighborsRule.cpp
- src/graph/optimizer/rule/PushStepSampleDownGetNeighborsRule.cpp
- src/graph/optimizer/rule/PushTopNDownIndexScanRule.cpp
- src/graph/optimizer/rule/PushVFilterDownScanVerticesRule.cpp
- src/graph/planner/plan/PlanNode.cpp
- src/graph/planner/plan/PlanNode.h
- src/graph/scheduler/AsyncMsgNotifyBasedScheduler.cpp
- src/graph/scheduler/AsyncMsgNotifyBasedScheduler.h
> Refactor the process of symbols in optimizer.

- src/graph/planner/match/MatchPlanner.cpp
- tests/tck/features/match/MultiLineMultiQueryParts.feature
https://github.com/vesoft-inc/nebula/issues/4154
The calculation of `Filter` before and after `InnerJoin/Cartesian` are equivalent *if the Filter can be delay*.
The calculation of `Filter` before and after `LeftJoin` are not equivalent, bcz `LeftJoin` always keep the left table rows.
So the correct solution is to introduce all visible variables via `Argument` and computes the `Filter` before `LeftJoin`.
This pr currently only fixes the case where `Filter` not referencing variables outside the definitions in the current match pattern.
Tests:
Affects:
> Fix optional of multi-match

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/processors/admin/SaveGraphVersionProcessor.cpp
- src/meta/processors/admin/SaveGraphVersionProcessor.h
- src/meta/processors/admin/VerifyClientVersionProcessor.cpp
Add SaveGraphVersionProcessor to separate client version check and version saving
Add SaveGraphVersionProcessor to separate client version check and version saving
Tests:
Affects:
> Fix incompatibility imported by https://github.com/vesoft-inc/nebula/pull/4116

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.h
- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/test/FindPathTest.cpp
- src/graph/service/GraphFlags.cpp
```
Data Structure(Previous version)
unordered_map<Value(dstVid), vector<Path> > prePaths;
Only keep dstVid and the paths to the dstVid,
There will be the following problems
```
Topology is graph 1 
problem one : redundant path
As shown in table 1, the third step will start from the two vids C and D to expand, if the start vid information is saved as shown in table 2, the third step only needs to expand from the vid D
problem two :  time complexity
comparing graph 1 and graph 2, in the conjunctPath stage, the paths can be grouped according to the startVid, and the time complexity will be reduced
Tests:
Affects:
> optimizer path

- src/clients/meta/MetaClient.cpp
#3855 only handle startup, we just skip heartbeat for tools all the time to avoid the annoying "UNKNOWN" hosts
Tests:
Affects:
Not related
> skip heartbeat for tool

- src/meta/processors/zone/DropHostsProcessor.cpp
- src/meta/processors/zone/DropHostsProcessor.h
> fix wrong space key after dropping hosts

- src/common/utils/NebulaKeyUtils.cpp
@Sophie-Xie Would you help to close it when this pr is synchronized
https://github.com/vesoft-inc/nebula-ent/issues/832
The new vertex key is not included in snapshot…… Quite error-prone to forget when we add a new prefix.
Tests:
Affects:
Fix vertex is not included in snapshot
> fix vertex is missing from snapshot

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/common/utils/NebulaKeyUtils.cpp
- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.h
- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/test/FindPathTest.cpp
- src/graph/planner/match/MatchPlanner.cpp
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphService.cpp
- src/graph/session/GraphSessionManager.cpp
- src/graph/validator/MatchValidator.cpp
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/processors/admin/SaveGraphVersionProcessor.cpp
- src/meta/processors/admin/SaveGraphVersionProcessor.h
- src/meta/processors/admin/VerifyClientVersionProcessor.cpp
- src/meta/processors/zone/DropHostsProcessor.cpp
- src/meta/processors/zone/DropHostsProcessor.h
- src/storage/query/ScanEdgeProcessor.cpp
- src/storage/query/ScanVertexProcessor.cpp
- tests/tck/features/bugfix/AggPatternExpression.feature
- tests/tck/features/match/MultiLineMultiQueryParts.feature
> Cherry pick v3.1.0 (0414-0420)

- src/kvstore/CMakeLists.txt
- src/kvstore/Common.h
- src/kvstore/KVStore.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/raftex/CMakeLists.txt
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/LogCASTest.cpp
- src/kvstore/raftex/test/LogCommandTest.cpp
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/kvstore/raftex/test/TestShard.cpp
- src/kvstore/test/NebulaStoreTest.cpp
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddEdgesProcessor.h
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.h
- src/storage/test/IndexTestUtil.h
- src/storage/test/RebuildIndexTest.cpp
- src/storage/test/StatsTaskTest.cpp
Let add tag / edge use atomic Op again. 
1. before and include Nebula 2.0, we use atomicOp to deal with some atomic operation,
e.g. change a tag/edge and its index in a batch. 
It works, but as we implement this by send raft log in a sync way. 
(all atomic op should be sent seperately, even if they are disjoint.) this is really slow.
2. In 2.6.x we use memory lock to deal with concurrent control. 
We check early(in processor) if a request can run or not. 
If it can, then we do the get/put as a normal log, which we can treat in batch.
if it can't, we return error. 
How ever, some user complain that they meet so many "Conflict error". 
That they need to retry, they believe it will slow down the bulk insert.
We explained that those conflict has to be retry either in Nebula it self or client, …
> Memory lock in raft

- src/interface/common.thrift
@forest-yuxl add comments of error code for doc, and I just added it to the code comments.
https://docs.nebula-graph.io/master/20.appendix/error-code/
>None
> Add comments of error code

- .github/workflows/release.yml
> fix two-level file directory after OSS copy

- src/clients/meta/MetaClient.cpp
- src/meta/processors/job/AdminJobProcessor.cpp
- src/meta/processors/job/DataBalanceJobExecutor.cpp
- src/meta/processors/job/JobManager.h
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
> fix error message

- src/graph/planner/ngql/SubgraphPlanner.cpp
The last step of the subgraph is to get all the edges between the visited vetices, if only the output vertices, do not need to take the last step
Tests:
Affects:
> modify subgraph loop condition

- src/common/meta/NebulaSchemaProvider.h
- src/storage/exec/IndexEdgeScanNode.cpp
- src/storage/exec/IndexEdgeScanNode.h
- src/storage/exec/IndexScanNode.cpp
- src/storage/exec/IndexScanNode.h
- src/storage/exec/IndexVertexScanNode.cpp
- src/storage/exec/IndexVertexScanNode.h
- src/storage/index/LookupProcessor.cpp
- src/storage/index/LookupProcessor.h
- src/storage/test/IndexTest.cpp
- tests/tck/features/index/Index.feature
#4230 
The main problem has two parts:
1. The `indexNullable_` in `IndexScanNode` is not initialized correctly.
2. In `IndexScanNode`, the offset of nullable bits is not calculated correctly.
Check if there is an nullable property when build plan.
Tests:
Affects:
Fix storage may crash when lookup index with nullable property.
> fix lookup crash when has nullable cols

- src/kvstore/Listener.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/SnapshotManager.cpp
During replication test, I found two problems here:
1. Once listener return FAILED when receiving snapshot, the sender won't retry (we only retry for timeout before). This is a minor issue, because usually, listener won't explicitly return error when receiving snapshot (at least listener should not @panda-sheep you need to check your `SyncListener` implementation)
2. What's worse, listener won't be able to receive snapshot. Because the listener is always in `WAITING_SNAPSHOT` state. So we just reuse the same logic in normal `RaftPart`.
Tests:
Affects:
Not related
> fix listener can't receive snapshot anymore

- README.md
https://github.com/cncf/landscape/pull/2516
Yes, we are here 👉🏻
Tests:
Affects:
> CNCF Landscape enrichment in README

- src/storage/query/GetPropProcessor.cpp
Close https://github.com/vesoft-inc/nebula/issues/4262
Tests:
Affects:
> Fix sharing filter expression inter threads.

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/storage/StorageServer.cpp
Standalone daemon exit after restart, since hosts is registered already. 
Add existing check.
Tests:
Affects:
> Fix restart failed

- src/storage/exec/IndexSelectionNode.cpp
- src/storage/exec/IndexTopNNode.cpp
- src/storage/exec/IndexTopNNode.h
- src/storage/index/LookupProcessor.cpp
1. Null pointer exception in IndexTopNNode
2. The expression in IndexSelectionNode is incorrectly shared
3. The IndexTopNNode is incorrectly constructed, resulting in incorrect data
Tests:
Affects:
> Repair some problems in query_concurrently mode

- src/graph/planner/plan/Query.cpp
Fix the issue that the result of dot format explanation of `Join` is malformed for GraphViz online tool, which caused by twice json converting.
Tests:
Affects:
> Fix the format of explain of input variables of Join.

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/wal/FileBasedWal.cpp
See the comments in code, below is an example, previously if the part start as learner, all id is 0. But after 20220530-2344, things go wrong.
Clean wal is start as learner
Tests:
Affects:
> fix learner's wal is not empty in rare cases

- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddEdgesProcessor.h
- tests/tck/features/insert/Insert.feature
When the edge has an index and insert value exceeding length, insert edge will cause crash.
Tests:
Affects:
> fix storage crash

- src/meta/processors/admin/RestoreProcessor.cpp
fix when restoring, the machine key is lost.
Examples are as follows:
During restore, the mapping relationship of hosts is as follows
```
211 -> 213
212 -> 212
213 -> 211
```
When the restore is over, there are only `211, 212,` two machine keys left, and the `213` machine key is lost.
Tests:
Affects:
> fix when restoring, the machine key is lost

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- conf/nebula-storaged.conf.default
- conf/nebula-storaged.conf.production
close #4246
Add some configs into configuration files which are commonly used.
Tests:
Affects:
Note sure if all these newly added configs are in doc.
> add some config

- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/meta/processors/BaseProcessor-inl.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/admin/RestoreProcessor.cpp
- src/meta/processors/zone/AddHostsProcessor.cpp
- src/meta/test/RestoreProcessorTest.cpp
fix zone lost in backup
Tests:
Affects:
> fix zone lost in backup

- .github/workflows/rc.yml
- docker/Dockerfile
- [ x] bug
fix docker version
Tests:
Affects:
> fix docker rc version

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
force cache the docker layer.
the layer is about 20GB, and need another 20min to export the layer.
after then each job would need 5min with the cache layer.
Tests:
Affects:
> force cache the docker layer

- src/daemons/MetaDaemon.cpp
- src/daemons/StandAloneDaemon.cpp
- src/meta/RootUserMan.h
close https://github.com/vesoft-inc/nebula-ent/issues/957
Before:
it will check whether there is a root account，when meta is restarted
After:
it will check whether there is an account with the GOD role， when the meta is restarted
Tests:
Affects:
> check god role exist when meta init

- src/graph/optimizer/rule/CollapseProjectRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformUtils.h
1. Input/Ouput variables.
2. Keep column names of Limit same with input plan node.
Tests:
Affects:
> Fix get edges transform rule.

- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/ShortestPathBase.cpp
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/algo/SingleShortestPath.cpp
Graph crash when running tck manually 
Can't be reproduced consistently.
Tck is run with 16 concurrent threads.
shared variables are locked before use in multi-threading environment
Tests:
Affects:
> fix_shortest_path_crash

- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/test/GetStatsTest.cpp
- src/meta/test/JobManagerTest.cpp
meta crash while running tck:
```txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/root/src/nebula-ent/build/bin/nebula-metad --flagfile /root/nebula-chaos-clust'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000005f7f5da in std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) ()
[Current thread is 1 (Thread 0x7f94a23e3700 (LWP 245))]
(gdb) bt
#0  0x0000000005f7f5da in std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) ()
#1  0x00000000037638c8 in std::_Rb_tree<int, …
```
> fix map concurrency issue

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- tests/Makefile
- tests/common/nebula_service.py
- tests/nebula-test-run.py
as title,
nightly and rc would test the nebula package via tck.
8 jobs:
4 system * 2 different configuration
just like:
> enhance nightly tck test job

- src/graph/executor/admin/SpaceExecutor.cpp
Invoking `std::move(StatusOr<T>).value()` will STEAL the value from `StatusOr` into a temporary object, which will be destroyed shortly.
> Fixed crash on dropping fulltext index

- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngine.h
- Replace obsolete RocksDB API "backupable db" to be compatible with RocksDB in the future
- Replace with updated RocksDB API.
- RocksDB has supported the updated API in very early versions, so it will not cause existing compatibility problems.
Tests:
Affects:
> Replace obsolete RocksDB API

- src/webservice/SetFlagsHandler.cpp
* when we use flags put interface, but we does not specify the body.
* The service will be crashed.
For example:
curl -X PUT xxx.xxx.xxx.xxxx:19559/flags
Checking for body_, if we got nullptr, Ignore this request.
Tests:
Affects:
> ex. Fixed the bug of service when we use put flags interface, but we does not specify body.
> Fix web service crash(issue:#4398)

- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
* When our space has tag index or edge index.
* When delete vertex or edge, we specify one vid more than our defined
in space.
* The sotrage will be crashed.
Solution:
1. Add vid valid verfication.
Tests:
Affects:
> ex. Fixed storaged crashed, when we delete vertex and edge specify vid more than our defined before in space.
> Fix delete vertex or edge, the storage crashed.(issue: #4397)

- src/meta/processors/job/LeaderBalanceJobExecutor.cpp
There are two read lock in LeaderBalanceJobExecutor.cpp in same thread (grab the first one then another, first not released). Once a write lock happens between two read lock, deadlock would happen.
> btw, std::shared_lock won't happen, will dig more later
Tests:
Affects:
> fix deadlock

- src/common/expression/ColumnExpression.cpp
- src/common/expression/test/ColumnExpressionTest.cpp
[#4412](https://github.com/vesoft-inc/nebula/issues/4412)
Let ColumnExpression writeTo encoder via `Value` instead of `size_t`
Tests:
Affects:
> Fix ColumnExpression encode and decode are not matched

- src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- tests/tck/features/lookup/TagIndexFullScan.feature
Rewrite `STARTS WITH` to `AND` expr and trigger  `TagIndexRangeScan` if an index is avaliable.
```
(root@nebula) [nba]> EXPLAIN  lookup on player where player.name starts with "Tim" YIELD player.name
Execution succeeded (time spent 1040/1368 us)
Execution Plan (optimize time 514 us)
-----+-------------------+--------------+----------------+--------------------------------
| id | name              | dependencies | profiling data | operator info                 |
-----+-------------------+--------------+----------------+--------------------------------
|  3 | Project           | 4            |                | outputVar: {                  |
|    |                   |              |                |   "colNames": [               |
|    |                   |              |                | …
```
> [Enhancement] Add opt rule to push down `STARTS WITH` expr

- src/clients/meta/MetaClient.cpp
- src/graph/executor/admin/SubmitJobExecutor.cpp
- src/graph/executor/test/JobTest.cpp
- src/interface/common.thrift
- src/meta/processors/job/DataBalanceJobExecutor.cpp
- src/meta/processors/job/DataBalanceJobExecutor.h
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/LeaderBalanceJobExecutor.cpp
- src/meta/processors/job/LeaderBalanceJobExecutor.h
- src/meta/processors/job/MetaJobExecutor.cpp
- src/meta/processors/job/MetaJobExecutor.h
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.h
- src/meta/test/BalancerTest.cpp
- tests/tck/job/Job.feature
https://github.com/vesoft-inc/nebula/issues/4247
https://github.com/vesoft-inc/nebula/issues/4232 (Part of the issue is addressed in #4444)
https://github.com/vesoft-inc/nebula-ent/issues/1052
1. When stop job a failed/finished job, we will return "E_SAVE_JOB_FAILURE" , which is obscure, return another error code.
2. Balance leader/data's error code is not passed out.  And balance leader has no tasks, which is quite same as #4442
Tests:
Affects:
> Job manager related fix

- src/meta/processors/job/BalanceJobExecutor.cpp
- src/meta/processors/job/BalanceJobExecutor.h
- src/meta/processors/job/DownloadJobExecutor.cpp
- src/meta/processors/job/DownloadJobExecutor.h
- src/meta/processors/job/JobDescription.h
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/processors/job/MetaJobExecutor.cpp
- src/meta/processors/job/RebuildFTJobExecutor.h
- src/meta/processors/job/SimpleConcurrentJobExecutor.cpp
- src/meta/processors/job/SimpleConcurrentJobExecutor.h
- src/meta/processors/job/StorageJobExecutor.h
- src/meta/test/JobManagerTest.cpp
We support `stop job`, but some kind of jobs are not actually stopped, this PR will report if it is not supported and make the stoppable one work as expected.
**Before**:
**After**:
Tests:
Affects:
> make 'stop job' work as expected

- src/graph/context/ast/QueryAstContext.h
- src/graph/planner/CMakeLists.txt
- src/graph/planner/ngql/IsomorPlanner.cpp
- src/graph/planner/ngql/IsomorPlanner.h
- src/graph/validator/CMakeLists.txt
- src/graph/validator/IsomorValidator.cpp
- src/graph/validator/IsomorValidator.h
> Build the planner and validator for subgraph Isomorphism

- src/graph/planner/ngql/IsomorPlanner.cpp
> add some to do in planner

- tests/tck/features/match/SeekById.feature
Fix https://github.com/vesoft-inc/nebula/issues/4417
This problem has been fixed in the master branch
Tests:
Affects:
> Add case for bugfix https://github.com/vesoft-inc/nebula/issues/4417

- src/common/function/FunctionManager.cpp
- src/common/function/test/FunctionManagerTest.cpp
- src/common/time/TimeUtils.cpp
`timestamp` and `datetime` can be convert each other.
```
(root@nebula) [(none)]> return datetime(timestamp())
+----------------------------+
| datetime(timestamp())      |
+----------------------------+
| 2022-08-16T03:32:27.000000 |
+----------------------------+
Got 1 rows (time spent 1842/2836 us)
(root@nebula) [(none)]> return datetime(timestamp(0))
+----------------------------+
| datetime(timestamp(0))     |
+----------------------------+
| 1970-01-01T00:00:00.000000 |
+----------------------------+
Got 1 rows (time spent 1173/1822 us)
Tue, 16 Aug 2022 11:32:37 CST
(root@nebula) [(none)]> return timestamp(datetime())
+-----------------------+
| timestamp(datetime()) |
+-----------------------+
| 1660620772            |
+-----------------------+
Got 1 rows (time spent 1160/1962 us) …
```
> datetime2timestamp and timestamp2datetime

- src/graph/executor/query/AggregateExecutor.cpp
- tests/tck/features/aggregate/Agg.feature
Optimize `COUNT(*)`
Tests:
Affects:
> optimize count(*)

- src/graph/executor/query/GetDstBySrcExecutor.cpp
- src/graph/planner/ngql/GoPlanner.cpp
- tests/tck/features/go/SimpleCase.feature
> [k-hop]Remove useless inner join for go in simple case

- README-CN.md
- README.md
Guide viewer the star.
Vue.js 作者尤雨溪：“开源的价值并不是那么容易量化，你不主动去要世界也不会给你。”
为什么Patreon上开源领袖Eric Raymond所得到的捐助不到vue.js的 1/10？ - 尤雨溪的回答 - 知乎
https://www.zhihu.com/question/305246119/answer/550207042
Tests:
Affects:
None.
> doc: improve star conversion rate for README

- src/storage/exec/QueryUtils.h
- src/storage/test/GetPropTest.cpp
https://github.com/vesoft-inc/nebula-ent/issues/1165
#4565 
Invalid filter will make storage crash, this only happens in enterprise version with additional filter push down rule.
Tests:
Affects:
> fix invalid filter in GetProp make storage crashed

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/BFSShortestPathExecutor.h
- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/BatchShortestPath.h
- src/graph/executor/algo/MultiShortestPathExecutor.h
- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/algo/ProduceAllPathsExecutor.h
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/algo/ShortestPathExecutor.cpp
- src/graph/executor/algo/ShortestPathExecutor.h
- src/graph/executor/algo/SingleShortestPath.cpp
- src/graph/executor/algo/SingleShortestPath.h
- src/graph/executor/algo/SubgraphExecutor.cpp
- src/graph/executor/algo/SubgraphExecutor.h
- src/graph/executor/query/MinusExecutor.cpp
- src/storage/query/GetDstBySrcProcessor.cpp
> fix dedup for GetDstBySrc

- src/graph/executor/query/ScanEdgesExecutor.cpp
- src/graph/optimizer/rule/GetEdgesTransformUtils.h
- src/graph/planner/plan/PlanNodeVisitor.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/visitor/PropertyTrackerVisitor.cpp
- src/graph/visitor/PropertyTrackerVisitor.h
- src/graph/visitor/PrunePropertiesVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.h
- tests/tck/features/optimizer/PrunePropertiesRule.feature
close https://github.com/vesoft-inc/nebula-ent/issues/1157
Tests:
Affects:
> extract attribute from properties function

- tests/tck/conftest.py
- tests/tck/features/delete/DeleteVertexWithoutEdge.feature
- tests/tck/features/geo/GeoBase.feature
- tests/tck/features/index/Index.feature
- tests/tck/features/insert/insertVertexOnly.feature
- tests/tck/features/lookup/LookUp.feature
- tests/tck/features/lookup/LookupTag2.feature
#4611 
Retry tck query executions on failures.
(1) Instead of using `executing query`, we can now write the following in tck cases: `When executing query and retrying it on failure every 6 seconds for 3 times:`
This will retry the query every 6 seconds for 3 times after it fails for the first time, until it either runs successfully or it has been retried for all 3 times.
(2) I have also applied it in some tck cases that has failed previously because of unfinished DDLs or some other similar reasons.
Tests:
Affects:
> Add tck execution with retry

- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
…reakPad
In the released installation package, when `ENABLE_BREAKPAD` is enabled, if the `log` directory does not exist, it will fail to start `meta/stroage (storagelistener)`.
Many versions have this problem.
close https://github.com/vesoft-inc/nebula-ent/issues/1257
Tests:
Affects:
> fix startup service failed when log directory not exists and enable_breakpad

- src/common/utils/MetaKeyUtils.cpp
- src/common/utils/MetaKeyUtils.h
- src/meta/processors/index/ListEdgeIndexesProcessor.cpp
- src/meta/processors/index/ListTagIndexesProcessor.cpp
- src/meta/processors/schema/ListEdgesProcessor.cpp
- src/meta/processors/schema/ListTagsProcessor.cpp
- src/meta/test/IndexProcessorTest.cpp
- src/meta/test/MetaClientTest.cpp
fix `list tag/edge/tagindex/edgeindex` logic to display data correctly. 
Although it was discovered by the enterprise version, the community version also has the same problem.
`list tag/edge/tagindex/edgeindex` logic has problems, resulting in display wrong data
The test case is as follows(used for enterprise version):
1) The master cluster is in the synchronous state at the beginning, do the following:
```
show sync status;
create tag player1(name string, age int, p3 int, p4 int);
stop sync
```
2) Suppose the slave cluster did the following before synchronizing:
```
create tag index fix on player1(p3);
desc tag index fix
show tag indexes
```
3） The master cluster does the following:
```
create tag index fix on player1(age);
desc tag index fix
show tag indexes
```
4）Then the master …
> fix list tag/edge/tagindex/edgeindex

- src/common/datatypes/Geography.cpp
- src/common/datatypes/Geography.h
- src/common/function/FunctionManager.cpp
- src/common/geo/io/wkb/test/WKBTest.cpp
- src/common/geo/test/GeoFunctionTest.cpp
When geography dataum is found to be illegal, print the specific cause of the error to facilitate troubleshooting.
eg.
```
E20220902 03:24:24.550307 350836 FunctionManager.cpp:2440] ST_GeogFromText error: The geography LINESTRING(0 1, 2 3) built from wkt LINESTRING(0 1, 2 3) is invalid, error: FindValidationError, S2 Errorcode: 1, message: Vertex 0 is not unit length
```
Tests:
Affects:
> Better error msg for validity check of geography

- src/kvstore/raftex/Host.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/meta/processors/parts/ListHostsProcessor.cpp
issue from ent version https://github.com/vesoft-inc/nebula-ent/issues/1153
Metad status is not checked now and hardcoded in show meta hosts.
When leader of space0 part0 receive heartbeat response, record the last time. Check it when show command is called.
Tests:
Affects:
> Add meta offline detect

- src/storage/admin/RebuildIndexTask.cpp
[rebuild tag index job always failed after stop a running job #1263](https://github.com/vesoft-inc/nebula-ent/issues/1263)
This hit a status check
```
if (std::get<0>(it->first) == space_ && it->second != IndexState::FINISHED) { ... }
```
While failed job keep its state `IndexState::BUILDING` and never changed before restarting in function `RebuildIndexTask::invoke`, so that no other rebuild task could pass this check.
Current always set it to `FINISHED` when this function end its lifetime.
Tests:
Affects:
> Fix a bug that rebuild index will always failed after a failed job unless restart.
> Always set rebuildIndexGuard to finish(succeed or failed)

- src/kvstore/Part.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/storage/admin/AdminProcessor.h
> fix issue 4274

- src/graph/validator/MaintainValidator.cpp
Tests:
Affects:
abandon uppercase letters in fulltext index name
> abandon uppercase letters in fulltext index name

- src/graph/planner/ngql/LookupPlanner.cpp
- tests/tck/features/lookup/LookUp.feature
yield distinct not return a distinct result set in LOOKUP
Add `Dedup` plan node in LookupPlanner.
```
(root@nebula) [nba]> lookup on player where player.age>40 yield keys(vertex) as p;
+-----------------+
| p               |
+-----------------+
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
| ["age", "name"] |
+-----------------+
Got 8 rows (time spent 7735/8484 us)
Fri, 16 Sep 2022 11:12:03 CST
(root@nebula) [nba]> lookup on player where player.age>40 yield distinct keys(vertex) as p;
+-----------------+
| p               |
+-----------------+
| ["age", "name"] |
+-----------------+
Got 1 rows (time spent 7447/8064 us)
Fri, 16 Sep 2022 11:12:15 CST
```
Tests:
Affects:
Please confirm whether to be …
> lookup with dedup

- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/optimizer/PrunePropertiesRule.feature
getProp interface's behave is 
before tagless
1、  if <vid + tag> exists in kvstore return value  else 2
2、 if vid exisits in tagless vids return value else return nothing
after tagless
1、if <vid+tag> exists in kvstore return value else return nothing
When attribute clipping, if there is no specified tag at the  vertex, all tags in the schema need to be added
Tests:
Affects:
> fix tagless

- src/clients/meta/MetaClient.h
- src/common/conf/test/ConfigurationTest.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/storage/exec/HashJoinNode.h
- src/storage/test/IndexWriteTest.cpp
> fix some typos

- tests/common/nebula_test_suite.py
- tests/common/utils.py
- tests/tck/conftest.py
Upload testcases to SQLAuto server
Add code for Python scripts for testing in the folder 'tests'
None
Tests:
Affects:
test: Upload testcases to SQLAuto server
> feat: upload testcases to SQLAuto server

- src/daemons/MetaDaemonInit.cpp
- src/meta/RootUserMan.h
https://github.com/vesoft-inc/nebula-ent/issues/1319#event-7444097789
`can ready from follower` flag not set so that follower alway get a LEADER_CHANGED error when read from kv.
Tests:
Affects:
> allow check god user read from follower

- src/common/hdfs/HdfsCommandHelper.cpp
folly::subprocess won't execute cmd now because "no such file" and if you add whole path , thers's some system environment like `JAVA_HOME` won't work.
So I specify bash to run cmd for now.
Also there's some problem with system ENV. if you use `sudo `, then you lose some ENV info.
Tests:
Affects:
> add bash -c for folly::subprocess

- src/storage/admin/StatsTask.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
1. when use_vertex_key=true,not save tagless key 
2. The value of Vertices in show stats needs to be deduplicated
Tests:
Affects:
> fix bug of tagless

- src/meta/processors/job/BalanceJobExecutor.cpp
- src/meta/processors/job/BalanceJobExecutor.h
- src/meta/processors/job/BalancePlan.cpp
- src/meta/processors/job/BalancePlan.h
- src/meta/processors/job/DataBalanceJobExecutor.cpp
- src/meta/processors/job/DataBalanceJobExecutor.h
- src/meta/processors/job/JobDescription.h
- src/meta/processors/job/JobExecutor.cpp
- src/meta/processors/job/JobExecutor.h
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/processors/job/LeaderBalanceJobExecutor.cpp
- src/meta/processors/job/LeaderBalanceJobExecutor.h
- src/meta/processors/job/MetaJobExecutor.cpp
- src/meta/processors/job/MetaJobExecutor.h
- src/meta/processors/job/StorageJobExecutor.cpp
- src/meta/processors/job/StorageJobExecutor.h
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.h
- src/meta/test/BalancerTest.cpp
- src/meta/test/GetStatsTest.cpp
- src/meta/test/JobManagerTest.cpp
fix comments
Use future to make meta jobs of different spaces execute in parallel
note:
Because the balance leader is for all spaces, it will not be dealt with here.
Same as https://github.com/vesoft-inc/nebula-ent/pull/1259
Also resolved issue https://github.com/vesoft-inc/nebula-ent/issues/867
Tests:
Affects:
> job use future

- src/clients/storage/StorageClient.cpp
- src/clients/storage/StorageClient.h
- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/SingleShortestPath.cpp
- src/graph/executor/query/GetNeighborsExecutor.cpp
- src/graph/executor/query/TraverseExecutor.cpp
- src/interface/storage.thrift
- src/storage/CommonUtils.h
- src/storage/exec/FilterNode.h
- src/storage/exec/GetNeighborsNode.h
- src/storage/query/GetNeighborsProcessor.cpp
- src/storage/query/GetPropProcessor.cpp
- src/storage/query/QueryBaseProcessor-inl.h
- src/storage/query/QueryBaseProcessor.h
- src/storage/query/ScanEdgeProcessor.cpp
- src/storage/query/ScanVertexProcessor.cpp
- src/storage/test/GetNeighborsTest.cpp
close https://github.com/vesoft-inc/nebula/issues/4649
Add vertexFilter to getNeighbor interface, when the filter condition of the  vertex is not satisfied, do not return the data for this vertex and corresponding edge 
Tests:
Affects:
> add vertex filter for GetNeighbors

- src/storage/mutate/AddVerticesProcessor.cpp
According to PRD, the vertex key should only insert it when the user_vertex_key is turned on or user insert vertex (not tag) explicitly.
Because insert vertex/tag use the same code from graphd to storaged, it seems we can only judge if it is insert_vertex by checking the prop_names is empty.
Tests:
Affects:
> only write vertex key when flag is set or explictly insert vertex

- src/meta/test/JobManagerTest.cpp
fix error in job manager UT in ASAN
```
I20220926 11:01:14.179844 18070 JobManager.cpp:136] JobManager::scheduleThread enter
*** Aborted at 1664161274 (Unix time, try 'date -d @1664161274') ***
*** Signal 11 (SIGSEGV) (0x0) received by PID 15368 (pthread TID 0x7f6b17917700) (linux TID 18070) (code: address not mapped to object), stack trace: ***
/__w/nebula/nebula/build/bin/test/job_manager_test(_ZN5folly10symbolizer17getStackTraceSafeEPmm+0x31)[0x507e771]
/__w/nebula/nebula/build/bin/test/job_manager_test(_ZN5folly10symbolizer21SafeStackTracePrinter15printStackTraceEb+0x26)[0x5075c76]
/__w/nebula/nebula/build/bin/test/job_manager_test[0x5073c07]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x1441f)[0x7f6c01f4c41f]
/__w/nebula/nebula/build/bin/test/job_manager_test(_ZN6nebula4meta16FlushJobExecu …
```
> fix job manager ut in asan

- src/graph/executor/admin/ShowHostsExecutor.cpp
https://github.com/vesoft-inc/nebula-ent/issues/1290
Change to default http port for storage now. And fixed later.
```
(root@nebula) [(none)]> show hosts;
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
| Host            | Port | HTTP port | Status   | Leader count | Leader distribution | Partition distribution | Version |
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
| "192.168.8.212" | 1779 | 19779     | "ONLINE" | 102          | "nba:100, space3:2" | "nba:100, space3:2"    | ""      |
+-----------------+------+-----------+----------+--------------+---------------------+------------------------+---------+
Got 1 rows (time spent 2637/3544 …
```
> fixed `show hosts`

- src/common/graph/Response.h
- src/graph/executor/admin/SubmitJobExecutor.cpp
- src/interface/common.thrift
- src/meta/processors/job/JobDescription.h
- src/meta/processors/job/TaskDescription.h
https://github.com/vesoft-inc/nebula-ent/issues/1295
set default to a new status as E_JOB_SUBMITTED.
Tests:
Affects:
> set job default status as submitted until get some result

- src/graph/context/Iterator.cpp
- src/graph/context/test/IteratorTest.cpp
close https://github.com/vesoft-inc/nebula/issues/4694
In a distributed environment, getNeighbor may return multiple datasets, and due to filter conditions, not every dataset has data
Tests:
Affects:
> fix subgraph crash

- tests/tck/features/optimizer/PrunePropertiesRule.feature
close https://github.com/vesoft-inc/nebula/issues/4639
fix uncertain test cases caused by different environments
Tests:
Affects:
> fix_ambiguous_case

- src/common/datatypes/Map.cpp
- src/common/datatypes/test/ValueTest.cpp
- tests/tck/features/go/GO.feature
Fix https://github.com/vesoft-inc/nebula/issues/4702
Tests:
Affects:
> fix map hash method

- src/graph/validator/test/YieldValidatorTest.cpp
- src/graph/visitor/DeduceTypeVisitor.cpp
- tests/tck/features/go/GO.feature
https://github.com/vesoft-inc/nebula/issues/4711
Tests:
Affects:
> Fix aggregate expression type deduce

- src/common/hdfs/HdfsCommandHelper.cpp
check errno from folly::subProcess 
Tests:
Affects:
> fix hdfs download command will always return succeeded sometimes

- src/storage/admin/RebuildIndexTask.cpp
- src/storage/admin/RebuildIndexTask.h
https://github.com/vesoft-inc/nebula-ent/issues/1410
Tests:
Affects:
> remove rebuild index guard when job finished

- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/validator/MutateValidator.cpp
- src/storage/exec/GetPropNode.h
- src/storage/query/GetPropProcessor.cpp
- tests/tck/features/delete/DeleteTag.IntVid.feature
- tests/tck/features/insert/insertVertexOnly.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/ttl/TTL.feature
As title, when vertex_key is not used, we forbid it. Otherwise, it will report succeeded, but no data is inserted.
Fix https://github.com/vesoft-inc/nebula-ent/issues/1420, it seems we can't simply prefix scan, we need to check if any tag is valid indeed. And valid means: tag schema exists and no ttl expired.
Tests:
Affects:
> forbid insert vertex when vertex_key flag is off

- src/graph/planner/ngql/GoPlanner.cpp
- tests/tck/features/go/SimpleCase.feature
Fix https://github.com/vesoft-inc/nebula/issues/4734
Tests:
Affects:
> fix dep of loop in go planner

- src/kvstore/raftex/RaftPart.cpp
#3926 introduced some new logic in raft, but the error code returned is always leader change, this would make some misunderstanding, especially when there is only one replica
Tests:
Affects:
> fix inappropriate error code from raft 

- src/storage/admin/StatsTask.cpp
Stats handle the flag use_vertex_key:
1. if off, count vertex by deduplicated tag
2. if on, count vertex by vertex key
Tests:
Affects:
> stats handle the flag use_vertex_key, and JobManager Related fix

- src/clients/meta/MetaClient.cpp
- src/interface/common.thrift
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/StorageJobExecutor.cpp
- src/meta/test/GetStatsTest.cpp
- src/meta/test/JobManagerTest.cpp
Two bugs are fixed:
1. Some job do not support stop, e.g. COMPACT/DOWNLOAD/INGEST and so on. Previously in #4460, we have already report error. However, sadly, when we `show job`, the job is marked as STOPPED, which is not expected. It looks like as  below:
After this PR, these unstoppable job will still keep in RUNNING state.
2. Some job need to run in storage leader. There is a corner case that, when we create a new space, before storage report leader distribution to meta, we start a job, e.g. STATS. For now JobManager can't select a storage to run the job, and the task won't be sent to storage for execution. Since no storage ever run it,  the job will always stay in RUNNING.
1. Only save STOPPED when it really stopped
2. If no leader found, report error.
Tests:
Affects:
Please confirm …
> JobManager related fix

- src/common/hdfs/HdfsCommandHelper.cpp
- src/kvstore/RocksEngine.cpp
- src/kvstore/test/RocksEngineTest.cpp
- src/storage/admin/DownloadTask.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/1463
close https://github.com/vesoft-inc/nebula-ent/issues/1464
When exchange generate SST files, some part may do not have data, so there won't exist corresponding part directory. After we change the way to execute hdfs command, this will be an issue. Because there will be an error like `dir not exists`, so when storage really start download, first `ls`, if the directory exists then copy.
And we need to handle ingest no files into rocksdb.
Tests:
Affects:
> download job related fix

- src/meta/processors/job/StorageJobExecutor.h
fill space and job id in storage job executor
Tests:
Affects:
> fix storage job

- src/common/expression/ContainerExpression.h
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/IndexSelecting.feature
- tests/tck/features/match/SeekById.feature
https://github.com/vesoft-inc/nebula/issues/4708
Tests:
Affects:
> Avoid full scan of match when there is an Relational In predicate

- src/graph/planner/plan/PlanNode.cpp
- src/graph/planner/plan/Query.cpp
- tests/tck/features/match/MatchById.feature
https://github.com/vesoft-inc/nebula-ent/issues/1489
Tests:
Affects:
> Fix mutil-match crash

- src/graph/executor/algo/SubgraphExecutor.cpp
- src/graph/planner/ngql/SubgraphPlanner.cpp
- src/graph/validator/GetSubgraphValidator.cpp
- tests/tck/features/subgraph/subgraph.IntVid.feature
- tests/tck/features/subgraph/subgraph.feature
- tests/tck/features/subgraph/subgraphWithFilter.feature
close https://github.com/vesoft-inc/nebula/issues/4770
https://github.com/vesoft-inc/nebula/issues/4764
Tests:
Affects:
> fix subgraph step

- src/common/expression/UnaryExpression.h
- src/graph/executor/query/RollUpApplyExecutor.cpp
- tests/tck/features/match/PathExpr.feature
Close https://github.com/vesoft-inc/nebula/issues/4760
The `roolUp` executor produces wrong results.
After fix:
```
(root@nebula) [nba]> match p = (v:player{name:"Tim Duncan"})-[e]->(t) where not (v)-[]->(t:player) return t
+--------------------------------+
| t                              |
+--------------------------------+
| ("Spurs" :team{name: "Spurs"}) |
+--------------------------------+
Got 1 rows (time spent 22.629ms/23.301331ms)
```
Tests:
Affects:
> Fix wrong output when using pattern expression as the filter in MATCH

- src/graph/executor/StorageAccessExecutor.cpp
Close https://github.com/vesoft-inc/nebula/issues/4794
The storage stats is a single line which is hard to read.
Before:
```
| 14 | IndexScan      | 2            | {                                                                                                                                                                                       | outputVar: {                                            |
|    |                |              | ver: 0, rows: 1, execTime: 0us, totalTime: 2810us                                                                                                                                       |   "colNames": [                                         |
|    |                |              | "127.0.0.1":39735 exec/total: 1585(us)/2431(us) …
```
> [enhancement] Add indents to storage details when profiling a query

- src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
Of https://github.com/vesoft-inc/nebula-ent/issues/1569
Tests:
Affects:
> Filter should keep column names.

- src/common/expression/ListComprehensionExpression.cpp
- src/common/expression/PredicateExpression.cpp
- tests/tck/features/bugfix/BoolCheckingInExpr.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1624
Tests:
Affects:
> Add implicit bool checking in expr predication.

- src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
- tests/tck/features/bugfix/PushFilterDownProject.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1613
Could check this issue, the Filter node push down to Project, but the VariableProperty don't be replaced.
Tests:
Affects:
> Fix filter push down project.

- src/kvstore/Listener.cpp
- src/kvstore/Listener.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/raftex/test/TestShard.h
- src/kvstore/test/DiskManagerTest.cpp
- src/kvstore/wal/AtomicLogBuffer.h
- src/kvstore/wal/FileBasedWal.cpp
- src/kvstore/wal/FileBasedWal.h
- src/kvstore/wal/test/FileBasedWalTest.cpp
- src/kvstore/wal/test/WalFileIterTest.cpp
Modified some code generation to ensure that it is the same as the enterprise version. Avoid additional trouble caused by different codes.
Tests:
Affects:
> catch up ent

- src/graph/executor/admin/SubmitJobExecutor.cpp
https://github.com/vesoft-inc/nebula-ent/issues/1553
As you can see, time show in this table is not in the same format, since a toString() method,  I unify them to version without toString, so that it can look the same.
Tests:
Affects:
> unify time format in show job

- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
1. exclude /usr/lib
2. exclude tests
3. exlucde unit test
Tests:
Affects:
> correct covarage

- src/tools/meta-dump/MetaDumpTool.cpp
Add job info to meta dump tool for that we may want to know the all jobs status in all spaces.
Tests:
Affects:
> add jobs info to meta dump tool

- src/common/expression/AttributeExpression.cpp
- tests/tck/features/expression/Attribute.feature
- tests/tck/features/match/With.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1574
An `e.non-exist-prop == true` expr is rewritten to `e.non-exist-prop` without checking whether `e.non-exist-prop` exists. This is fine by itself.
And, while the filter operator evaluates the `e.non-exist-prop` condition, it finds it to be of the `Value::kNullUnknownProp` type. This causes unexpected error messages that terminte the query.
After discussion, we've decided that `e.non-exist-prop == true` shall return a plain null value.
`e.non-exist-prop == true` returns plain null.
It may be the case that all nulls of the unkown_prop type shall be changed to plain ones. But I want to keep the impact of a bug fix to its minimal level. So I only made this change for edges, excluding tags' properties. This may cause inconsistent nulls …
> fix wrong expr evaluation on bool-type property in with

- src/storage/context/StorageExpressionContext.h
- src/storage/exec/GetDstBySrcNode.h
- src/storage/exec/StoragePlan.h
- src/storage/mutate/UpdateEdgeProcessor.h
- src/storage/mutate/UpdateVertexProcessor.h
- src/storage/query/GetDstBySrcProcessor.cpp
- src/storage/query/GetDstBySrcProcessor.h
- src/storage/query/GetNeighborsProcessor.cpp
- src/storage/query/GetNeighborsProcessor.h
- src/storage/query/QueryBaseProcessor-inl.h
- src/storage/query/QueryBaseProcessor.h
Replace std::vector<Value> with std::deque<Value> to improve the memory allocation.
Tests:
Affects:
> Profile storage GetDstBySrcProcessor

- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
Nightly's coverage step will fail frequently. It is speculated that when ENABLE_COVERAGEis set to on, the number of concurrent links is large, leading to OOM.
Try to reduce the number of compilation threads to avoid this problem.
Tests:
Affects:
> fix nightly coverage oom

- src/common/datatypes/HostAddr.h
- src/graph/executor/StorageAccessExecutor.cpp
- src/graph/executor/StorageAccessExecutor.h
- src/graph/executor/algo/ShortestPathBase.cpp
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/algo/SubgraphExecutor.cpp
- src/graph/executor/query/GetDstBySrcExecutor.cpp
- src/graph/executor/query/GetNeighborsExecutor.cpp
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/util/CMakeLists.txt
- src/graph/util/Utils.cpp
- src/graph/util/Utils.h
- src/storage/query/GetDstBySrcProcessor.cpp
- tests/common/plan_differ.py
- tests/tck/conftest.py
- tests/tck/features/explain/ExplainAndProfile.feature
Return the valid profiling JSON format to client
Tests:
Affects:
> Fix graph profiling data format

- src/common/network/NetworkUtils.cpp
- src/common/network/NetworkUtils.h
- src/common/network/test/NetworkUtilsTest.cpp
https://github.com/vesoft-inc/nebula/issues/3333
When one network device has more than one ip, will failed to started up, because `validateHostOrIp` will failed, see the issue for more information.
Tests:
Affects:
> fix validateHostOrIp fail when one device has more than one ip

- src/graph/executor/StorageAccessExecutor.cpp
- src/graph/visitor/ExtractFilterExprVisitor.cpp
- tests/tck/features/bugfix/ExtractFilter.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1551
It caused by extract filter don't reset ok status when the first logical and expr can be split.
Tests:
Affects:
> Fix extract filter.

- src/graph/optimizer/OptimizerUtils.cpp
- src/graph/optimizer/rule/OptimizeEdgeIndexScanByFilterRule.cpp
- src/graph/optimizer/rule/OptimizeTagIndexScanByFilterRule.cpp
- src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/validator/LookupValidator.cpp
- src/graph/visitor/FoldConstantExprVisitor.cpp
- src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
Close https://github.com/vesoft-inc/nebula/issues/4898
Tests:
Affects:
> Fold constant for List/Set expression

- src/graph/optimizer/rule/PushFilterDownAggregateRule.cpp
- src/graph/optimizer/rule/PushFilterDownProjectRule.cpp
- src/graph/planner/plan/PlanNode.cpp
- src/graph/planner/plan/PlanNode.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/bugfix/MatchCrash.feature
- tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
- tests/tck/features/optimizer/PushFilterDownProjectRule.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1580
Close https://github.com/vesoft-inc/nebula-ent/issues/1683
- `colNames[i]` runs out-of-range in `PrunPropertiesVisitor.cpp`, caused by errors in PushFilterDownAggregateRule & PushFilterDownFilterRule.
- `colNames` becomes larger than `groupItems` in PushFilterDownAggregateRule, causing `groupItems[i]` to run out-of-range.
- Check range sizes in for loop in `PrunPropertiesVisitor.cpp`.
- Found the reason why the sizes differ in `PushFilterDownAggregateRule` and `PushFilterDownProjectRule`. Try fixing the exchange of operators.
Design-wise, these two structures that shall have the same size belong to different classes: one in the base class, the other in a derived class. They are manipulated independently in many places, directly or …
> Fix two crash issues caused by the optimizer's filter push-down rules

- src/common/context/ExpressionContext.h
- src/common/expression/ListComprehensionExpression.cpp
- src/common/expression/PredicateExpression.cpp
- src/common/expression/ReduceExpression.cpp
- src/common/expression/VariableExpression.cpp
- src/common/expression/VariableExpression.h
- src/common/expression/test/ExpressionContextMock.h
- src/common/expression/test/ListComprehensionExpressionTest.cpp
- src/common/expression/test/PredicateExpressionTest.cpp
- src/common/expression/test/ReduceExpressionTest.cpp
- src/common/utils/DefaultValueContext.h
- src/graph/context/QueryExpressionContext.cpp
- src/graph/context/QueryExpressionContext.h
- src/graph/planner/match/MatchSolver.cpp
- src/graph/util/ParserUtil.cpp
- src/graph/visitor/ValidatePatternExpressionVisitor.cpp
- src/graph/visitor/test/VisitorTestBase.h
- src/storage/context/StorageExpressionContext.cpp
- src/storage/context/StorageExpressionContext.h
- src/storage/exec/IndexExprContext.h
Fix https://github.com/vesoft-inc/nebula/issues/4844
Tests:
Affects:
> make evaluation of inner var expr thread-safe

- src/common/meta/GflagsManager.cpp
- tests/admin/test_configs.py
`UPDATE CONFIGS` statement will lead to storage crash when update rocksdb configs.
In the test `test_configs`,  we will try to modify the value of `storage:rocksdb_column_family_options`. And we save the value as an `Expression` after parser. In this case, it's a `Map`.
Then, `gflags` only accepts string type value. We transfer the `Value::Map` to `map<std::string,std::string>`. But we add extra quotes. For example, `a:1` while be transferred to `"a":"1"`, but `b:"x"` will be transferred to `"b":""x""`, which is error format for json.
But I still don't know why this problem is not triggered in our CI.
A preliminary guess is that the update of config will wait for the metaClient to pull regularly. The interval between two modifications is too short, so the metaClient does not find this …
> fix update config

- src/kvstore/Listener.cpp
- src/kvstore/Listener.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/plugins/elasticsearch/ESListener.h
- src/kvstore/test/NebulaListenerTest.cpp
Also a prepare work:
1. Only pass necessary parameter to Listener's constructor, other's could be passed to their inherited classes.
2. Modify the comment about Listener to keep up with latest changes.
Tests:
Affects:
> Minor enhancement about listener

- src/storage/exec/UpdateResultNode.h
- src/storage/test/UpdateVertexTest.cpp
- tests/README.md
- tests/tck/features/update/Update.feature
https://github.com/vesoft-inc/nebula/issues/4926
when the sym_ in PropertyExpression is empty, return reference of string and pass it to folly::stringFormat will crash.
```
(gdb) bt
#0  0x00007f26e967f079 in vfprintf () from /lib64/libc.so.6
#1  0x00007f26e96aa179 in vsnprintf () from /lib64/libc.so.6
#2  0x0000000002c2a2b3 in ?? ()
#3  0x0000000002c2b737 in folly::stringVPrintf[abi:cxx11](char const*, __va_list_tag*) ()
#4  0x0000000002c2b8df in folly::stringPrintf[abi:cxx11](char const*, ...) ()
#5  0x00000000014ce1ca in nebula::storage::UpdateResNode<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::doExecute(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x00000000014bd030 in …
```
> fix folly::stringPrintf when ref empty str

- src/kvstore/NebulaStore.cpp
- src/kvstore/RocksEngine.cpp
- src/kvstore/RocksEngine.h
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/test/RocksEngineTest.cpp
Legacy PR from #4254. (Legacy problem has been addressed in this PR)
This problem is found in nebula-ng. Some of our rocksdb api is not well verified in PlainTable, for example, whether the data is in sst will effect the api result. The main problem is that:
1. Since PlainTable only support prefix-based Seek, we need to specify prefix_same_as_start not only in prefix, but also range and rangeWithPrefix.
2. And the length of prefix_extractor need to be modified. Because within PlainTable, if the prefix bloom filter is not inserted, you can't be read by prefix any more. So to make sure every data could be read, we use the minimum length we use in prefix, which is 4.
Tests:
Affects:
> fix some rocksdb api will fail in PlainTable

- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- tests/tck/features/expression/LogicalExpression.feature
Close #4951 
Lack of support for xor.
Added some methods for xor.
Tests:
Affects:
> Fix graphd's crash due to lack of support of xor.

- tests/tck/features/optimizer/PrunePropertiesRule.feature
As title https://github.com/vesoft-inc/nebula/pull/4949 introduced tck case 's result is not ordered, fix with any order
Tests:
Affects:
> fix PrunProperties tck random order

- src/clients/meta/MetaClient.h
- src/storage/CommonUtils.cpp
- src/storage/CommonUtils.h
- src/storage/exec/QueryUtils.h
- tests/tck/features/ttl/TTL.feature
close https://github.com/vesoft-inc/nebula/issues/4962
As title, the reason is that we only read the ttl property from RowReader, we need to use latest schema as well for data with older schema version.
`QueryUtils::readValue` already handle this.
Add some comments.
Tests:
Affects:
> fix ttl not work when ttl column has default value

- src/common/http/test/CMakeLists.txt
- src/common/http/test/HttpClientTest.cpp
- src/mock/CMakeLists.txt
- src/mock/FakeHttpServer.cpp
- src/mock/FakeHttpServer.h
> Http client ut

- src/graph/executor/query/InnerJoinExecutor.cpp
- src/graph/executor/query/InnerJoinExecutor.h
- src/graph/executor/query/JoinExecutor.cpp
- src/graph/executor/query/JoinExecutor.h
- src/graph/executor/test/JoinTest.cpp
- src/graph/planner/plan/Query.cpp
- tests/tck/features/match/MultiQueryParts.feature
Fix https://github.com/vesoft-inc/nebula/issues/4960
Tests:
Affects:
> fix duplicate output column names of join

- src/graph/planner/match/MatchPathPlanner.cpp
- src/graph/validator/test/MatchValidatorTest.cpp
- tests/tck/features/bugfix/DupAliasInMatch.feature
Fix https://github.com/vesoft-inc/nebula-ent/issues/1605, https://github.com/vesoft-inc/nebula-ent/issues/1727
Emit `addVertises` node if the last node in the pattern is duplicated.
Tests:
Affects:
> Fix dup alias in MATCH

- src/graph/context/ast/CypherAstContext.h
- src/graph/planner/match/MatchClausePlanner.cpp
- src/graph/planner/match/MatchPathPlanner.cpp
- src/graph/planner/match/MatchPathPlanner.h
- src/graph/planner/match/MatchPlanner.cpp
- src/graph/planner/match/MatchSolver.cpp
- src/graph/planner/match/MatchSolver.h
- src/graph/planner/match/SegmentsConnector.cpp
- src/graph/planner/match/SegmentsConnector.h
- src/graph/planner/match/ShortestPathPlanner.cpp
- src/graph/planner/match/ShortestPathPlanner.h
- src/graph/planner/match/UnwindClausePlanner.cpp
- src/graph/planner/match/WhereClausePlanner.cpp
- src/graph/planner/match/YieldClausePlanner.cpp
- src/graph/planner/plan/ExecutionPlan.cpp
- src/graph/planner/plan/ExecutionPlan.h
> Cleanup match planner

- src/interface/common.thrift
Close #4986 
Related to #4907 
Remove a member in an enum may result in generating inconsistent thrift codes and building errors. Not sure what the exact reason is. But keeping the enmu unchanged avoids this risk.
- Add the removed member back (i.e., `UNKNOWN_PROP`) with a deprecated comment marker.
- It serves as a placeholder to avoid size differences of `enum NullType`.
- It will never be sent to clients, as `UNKNOWN_PROP` has been removed in `Value.h`.
Tests:
Affects:
> added a deprecated marker in common.thrift

- src/clients/meta/MetaClient.cpp
- src/interface/meta.thrift
- src/meta/processors/admin/HBProcessor.cpp
- src/meta/processors/job/StorageJobExecutor.cpp
- src/meta/processors/listener/ListenerProcessor.cpp
- src/meta/processors/parts/ListHostsProcessor.cpp
- src/meta/test/JobManagerTest.cpp
- src/meta/test/MetaClientTest.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/storage/StorageServer.cpp
Synchronize from the enterprise version, support the following functions:
Tests:
Affects:
> sync from ent repo for supportting show hosts storage listener

- src/graph/executor/query/TraverseExecutor.h
- src/storage/exec/GetNeighborsNode.h
- tests/tck/features/match/SelfReflectiveEdges.feature
Close #4929 
Duplicated results in matches.
Reason:
- Self-reflective edges like `(v0)-[e]->(v0)` are stored as two different versions in the storage: the outbound one and the inbound one.
- When fetching edges of both directions in the GetNeighborsNode, these two physical versions are treated as two distinct edges, although they are the same edge.
- Such redudant edges returned from the storage cause the query engine's traverse operator to process redudant edges, resulting in extra overhead and wrong results.
In the GetNeighborsNode, if an edge fetched from the storage has identical srcID and dstID, check whether it has been visited previously. If so, skip it.
Tests:
Affects:
> Skip redudant self-reflective edges in GetNeighborsNode

- src/graph/visitor/PropertyTrackerVisitor.cpp
- tests/tck/features/optimizer/PrunePropertiesRule.feature
Close #4974 
`match (v0:player)-[e0]->(v1) where id(v0) == "Tim Duncan" unwind e0.start_year as a return count(a)
`
$a was pruned in this query, causing the unwind operator to produce NULL dataset, which in the end leads to wrong counting results.
Disable the pruning of `Expression::Kind::kVarProperty` and `Expression::Kind::kInputProperty` in PropertyTrackerVisitor.
Tests:
Affects:
> Remove the pruning of Expression::Kind::kVarProperty in agg.

- src/common/expression/PredicateExpression.cpp
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/OptGroup.cpp
- src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
- src/graph/optimizer/rule/PushFilterDownTraverseRule.h
- src/graph/planner/plan/Query.h
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/storage/query/QueryBaseProcessor-inl.h
- tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
> push filter down traverse rule

- src/graph/executor/logic/ArgumentExecutor.cpp
- tests/tck/features/match/MultiLineMultiQueryParts.feature
> [LDBC] Fix argument when the input is `NULL`

- .github/workflows/pull_request.yml
Fix the problem that clang cannot be installed through apt,with sudo.
With github runner default label:ubuntu-latest upgrade from
Tests:
Affects:
> Fix apt install failed

- src/common/function/FunctionManager.cpp
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/OptimizeLeftJoinPredicateRule.cpp
- src/graph/optimizer/rule/OptimizeLeftJoinPredicateRule.h
- tests/tck/features/match/MultiQueryParts.feature
- tests/tck/features/optimizer/OptimizeLeftJoinPredicateRule.feature
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
> optimize left join predicate & Eliminate useless appendVertices

- src/common/expression/PredicateExpression.cpp
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.cpp
- src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.h
- tests/tck/features/match/MultiQueryParts.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
- tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
> Port: remove useless appendVertices below innner/left join

- src/graph/optimizer/rule/PushEFilterDownRule.cpp
- src/graph/optimizer/rule/PushEFilterDownRule.h
- tests/tck/features/optimizer/PushEFilterDownRule.feature
- tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
> Fix  wrong invoke of toEdgeName

- src/common/datatypes/Edge.h
- src/common/datatypes/Path.h
- src/common/datatypes/Value.cpp
- src/common/datatypes/Value.h
- src/common/datatypes/ValueOps-inl.h
- src/common/datatypes/Vertex.h
- src/graph/context/Iterator.cpp
- src/graph/context/Iterator.h
* shallow copy vertex & edgee
* add delete
* fix error
* delete error code
* optimize getVertex
* fix memory leak
* delete useless code
* address comment
* fix multiple threads double free  pointer problem
The type of vertex and edge in value is replaced from raw pointer to unique_ptr in other PR
Tests:
Affects:
> Share memory for vertex and edge value (#1565)

- src/graph/executor/query/AppendVerticesExecutor.cpp
- src/graph/planner/plan/Query.h
Do not make an rpc request if no need to fetch properties.
Tests:
Affects:
> Enhance the AppendVertices operator to avoid unnecessary rpc overhead

- tests/tck/features/match/SelfReflectiveEdges.feature
Replace insert/delete vertices/edges in a tck with operating on a new empty graph.
This fix has been applied in the ent repo.
Tests:
Affects:
> Fix a tck.

- README.md
it breaks sometimes
n/a
n/a
before:
after:
na
Tests:
Affects:
na
> fixed broken badges

- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/With.feature
Fix #5022 
Consider a clause segment like "unwind a as b with *". The project operator generated to implement "with *" shall carry on all aliases from its previous "unwind" clause, consisting of the aliases that the unwind passes on as well as the alises it generated (e.g., the b in this example).
In the current implementation, only the `unwindCtx->alias` (e.g., the b in this example) is added into the project. With only this alias passed, there would be missing columns in the project's output variable, which in turn would prevent the argument operator, if any, to find its needed columns for its input variable.
Argument will NULL input variable crashses the graphd.
Detailed analysis of the crash bug has been posted in the above issue.
Added aliasesAvailable and aliasesGenerated into the …
> Pass aliases from unwind to project.

- src/graph/optimizer/Optimizer.cpp
- src/graph/optimizer/Optimizer.h
Fix https://github.com/vesoft-inc/nebula/issues/4982.
Related https://github.com/vesoft-inc/nebula-ent/issues/1487.
In most cases, we can considier to constrict the depth of the plan tree to avoid stack overflow crash caused by some bad queries.
But for some queries such as `statement1 interest statement2 interest statement3 ...`,
which is a very normal statement, even if there are many statements to intersect,
we may need to consider the multi-way operator in planner to avoid the overflow.
e.g.
The binary intersect operator:
```
intersect
/       \
intersect   c 
/     \
a       b
```
The multi-way intersect operator:
```
intersect
/   |    \
a    b     c
```
Tests:
Affects:
> Restrict the max depth of plan tree in optimizer

- tests/data/test/README.md
> Add note about test data.

- src/clients/meta/MetaClient.cpp
- src/clients/storage/StorageClientBase-inl.h
- src/graph/executor/StorageAccessExecutor.h
- src/interface/common.thrift
- src/meta/processors/BaseProcessor-inl.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/index/CreateEdgeIndexProcessor.cpp
- src/meta/processors/index/CreateTagIndexProcessor.cpp
- src/meta/processors/schema/CreateTagProcessor.cpp
- src/meta/test/IndexProcessorTest.cpp
- src/meta/test/ProcessorTest.cpp
- src/tools/db-dump/CMakeLists.txt
Close #4947, #4948, https://github.com/vesoft-inc/nebula-ent/issues/1890, https://github.com/vesoft-inc/nebula-ent/issues/1749
Mainly to improve some error code and error message, skip db_dump tool when packaging.
Tests:
Affects:
> Minor enhancement about error message

- src/common/expression/AttributeExpression.cpp
- src/common/expression/test/AttributeExpressionTest.cpp
- src/common/expression/test/ExpressionContextMock.h
- src/common/expression/test/ListComprehensionExpressionTest.cpp
- src/common/expression/test/PredicateExpressionTest.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
- tests/tck/features/match/Unwind.feature
Close #5051 
LabelTagProperty expressions in unwind are treated as AttributeExpressions, causing property-not-found errors.
- Rewrite them to LabelTagProperty expressions and get evaluated as such.
- Hacked AttributeExpression to allow other hard-to-fix expressions like ListComprehensionExpression to work correctly.
Tests:
Affects:
> Fix expressions that shall be rewritten to LabelTagProperty

- src/codec/Common.h
- src/codec/RowWriterV2.cpp
- tests/tck/features/fetch/FetchEmpty.feature
- tests/tck/features/index/Index.feature
> add some truncated fixed string case

- src/clients/meta/MetaClient.cpp
- src/interface/common.thrift
- src/meta/processors/zone/AddHostsProcessor.cpp
- src/meta/test/ProcessorTest.cpp
start nebula graph with address 192.168.8.134:9669
add hosts 192.168.8.134:9669
create space
expected:
only store data in storage
actual:
partitions are wrong.
when add a host, check if the host is storage, if not, it can't be added
Tests:
Affects:
> could not add a host that is not a storage

- .github/workflows/pull_request.yml
Temporarily close the workflow job of ubuntu20.04
Temporarily close the workflow job of ubuntu20.04
It is only temporarily closed, and you need to revert pr in the future
Tests:
Affects:
> Temporarily close the workflow job of ubuntu20.04

- src/clients/storage/StorageClientBase-inl.h
Close https://github.com/vesoft-inc/nebula-ent/issues/1971
Close https://github.com/vesoft-inc/nebula/issues/5101
ex->what() is called without checking whether ex is nullptr.
For this else body in particular, no need to call ex->what().
Tests:
Affects:
> Fix the crash caused by a nullptr variable

- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/util/test/ExpressionUtilsTest.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- tests/tck/features/match/SeekById.feature
Fix #5063, Fix https://github.com/vesoft-inc/nebula-ent/issues/1530
Fix https://github.com/vesoft-inc/nebula/issues/5067
Tests:
Affects:
> fix wrong vid finder for logic or expr

- src/graph/executor/query/FilterExecutor.cpp
- tests/tck/features/match/Base.feature
Close https://github.com/vesoft-inc/nebula/issues/5097
NullType::BAD_TYPE triggers error in filter. We've decided to keep similar issues as the status quo.
Improved the error message, telling users how to bypass this problem.
Tests:
Affects:
> revise error messages.

- src/graph/service/PermissionCheck.cpp
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
Users except GUEST can do data balance.
Add data balance permission check for writespace.
Tests:
Affects:
> add job permission check for data balance

- src/storage/BaseProcessor.h
- src/storage/exec/IndexScanNode.cpp
- src/storage/test/IndexTest.cpp
- src/storage/test/IndexTestUtil.h
- tests/tck/features/index/Index.feature
Add index test cases about:
1. Index that contains FIXED_STRING property
2. TTL in index value
3. Basic compound index test in tck
Tests:
Affects:
> Add index test cases

- src/graph/validator/GroupByValidator.cpp
- tests/tck/features/yield/parameter.feature
Close #5111 
Yield after the pipe operator fails to get its input variable correctly, causing the aggregate executor to use a DefaultIterator from an empty dataset, many unimplemented methods of which contain LOG(FATAL) that crashes the service.
Deduce properties for aggregate expressions, allowing it to get its input variable generated before the pipe operator correctly.
Tests:
Affects:
> Fix a crash bug. Deduce props in yield.

- src/interface/common.thrift
- src/kvstore/listener/elasticsearch/ESListener.cpp
- src/kvstore/listener/elasticsearch/ESListener.h
- src/meta/processors/index/FTIndexProcessor.cpp
- tests/tck/features/fulltext_index/FultextIndexDDL.feature
1. Add fulltext index ddl tck test case
2. fix ESListener crash when there is no elasticsearch
Tests:
Affects:
> Add more fulltext index tck case

- src/meta/processors/index/CreateEdgeIndexProcessor.cpp
- src/meta/processors/index/CreateTagIndexProcessor.cpp
- tests/tck/features/index/Index.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/1685
Two logic is restricted:
* If create a string property index with length <= 0, return error.
* If length is specified for a fixed_string property index, return error. (Because in tag/edge, the fixed_string property has been specified, index will reuse it)
Tests:
Affects:
> forbid string index length <= 0

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- conf/nebula-standalone.conf.default
- conf/nebula-storaged-listener.conf.production
- conf/nebula-storaged.conf.default
- conf/nebula-storaged.conf.production
- src/graph/executor/admin/SpaceExecutor.cpp
- src/graph/service/GraphFlags.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
- src/storage/test/StorageHttpPropertyHandlerTest.cpp
- src/storage/transaction/ChainAddEdgesGroupProcessor.cpp
- src/storage/transaction/ChainDeleteEdgesGroupProcessor.cpp
- src/storage/transaction/ChainUpdateEdgeLocalProcessor.cpp
- src/tools/simple-kv-verify/CMakeLists.txt
- src/tools/storage-perf/CMakeLists.txt
- tests/admin/test_space.py
- tests/tck/features/match/With.feature
* Close https://github.com/vesoft-inc/nebula-ent/issues/1857 : disable toss
* Close https://github.com/vesoft-inc/nebula-ent/issues/1738 https://github.com/vesoft-inc/nebula-ent/issues/1953: add query_concurrently to conf, remove kv_separation from conf because rocksdb has bug
* Close https://github.com/vesoft-inc/nebula-ent/issues/1954, https://github.com/vesoft-inc/nebula-ent/issues/1978: rename listener's pid_file name and log_dir name
* Close https://github.com/vesoft-inc/nebula-ent/issues/1797: make default value of `local_config` as true
* Some other minor enhancement, disable some useless tools.
Tests:
Affects:
> Close toss, and some other minor enhancement

- src/common/memory/MemoryTracker.h
As discussed here: https://github.com/vesoft-inc/nebula/pull/5082/files#r1057092947
Tests:
Affects:
> Enhance MemoryStats to avoid the false sharing effect on the CPU cache

- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/planner/match/MatchPathPlanner.cpp
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
close https://github.com/vesoft-inc/nebula-ent/issues/1668
close https://github.com/vesoft-inc/nebula-ent/issues/2022
Tests:
Affects:
> add tagFilter for traverse

- src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/FindVisitor.cpp
- src/graph/visitor/FindVisitor.h
- tests/tck/features/match/Base.feature
Close https://github.com/vesoft-inc/nebula/issues/5123
Close https://github.com/vesoft-inc/nebula/issues/5120
Close https://github.com/vesoft-inc/nebula-ent/issues/1996
Tests:
Affects:
> fix push down of rank(e)

- src/common/datatypes/Edge.cpp
- src/common/datatypes/Vertex.h
- src/common/expression/test/TestBase.h
- src/graph/context/ast/CypherAstContext.h
- src/graph/validator/MatchValidator.cpp
- src/graph/validator/MatchValidator.h
- src/parser/parser.yy
- tests/tck/features/bugfix/ListSlicingWithNull.feature
- tests/tck/features/expression/Case.feature
- tests/tck/features/expression/function/Mathematical.feature
- tests/tck/features/function/coalesce.feature
- tests/tck/features/set/Set.feature
- tests/tck/features/yield/return.feature
Close https://github.com/vesoft-inc/nebula/issues/5115,
By the way, fix https://github.com/vesoft-inc/nebula/issues/5113
Usage:
`cypher_statement1 UNION/INTERSECT/MINUS cypher_statement2`
e.g.
```
match (v:player) where id(v) == "Tony Parker" return v
union/intersect/minus
match (v:player) where id(v) == "Tim Duncan" return v
```
Tests:
Affects:
> support intersect/minus for cypher

- conf/nebula-storaged-listener.conf.default
- conf/nebula-storaged-listener.conf.production
- src/graph/executor/admin/SpaceExecutor.cpp
- src/kvstore/listener/Listener.cpp
- src/kvstore/listener/Listener.h
Close https://github.com/vesoft-inc/nebula-ent/issues/2010
Listener may crash because the `Listener` has been removed while the background thread is still running. (There life time is different)
We can't use `shared_from_this` like what we did in `RaftPart` because Listener is already an inherited class from `RaftPart`. So for simplicity, we just add one thread `applyPool_` for each `Listener`, and when stopping the Listener, we stop the pool as well, which make their lifetime same.
There are some other minor changes, that is for to keep same configuration as the ent version.
Tests:
Affects:
> fix listener may crash when remove

- src/graph/service/QueryInstance.cpp
The format function will truncate the error message that `Status::Error` used if it is longer than 256 bytes.
```
std::string Status::format(const char *fmt, va_list args) {
char result[256];
vsnprintf(result, sizeof(result), fmt, args);
return result;
}
```
Tests:
Affects:
> fix error msg trancated

- src/graph/optimizer/rule/PushFilterDownHashInnerJoinRule.cpp
- tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Close #5147 
When pushing down a filter over a hash join, the output columns of the join were set to those of the filter, causing the aggregate after the join to lose its dependent columns and produce null values. 
When pushing filters over hash joins, the columns of the join shall stay unchanged, since the filter may at most change the cardinality of the join's inputs and never change its columns.
Tests:
Affects:
> Fix PushFilterDownHashInnerJoinRule

- src/clients/meta/MetaClient.cpp
- src/common/datatypes/Value.cpp
- src/common/graph/Response.h
- src/common/thrift/ThriftClientManager-inl.h
- src/interface/common.thrift
- src/meta/ActiveHostsMan.cpp
- src/meta/ActiveHostsMan.h
- src/meta/processors/BaseProcessor-inl.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/admin/CreateSnapshotProcessor.cpp
- src/meta/processors/admin/CreateSnapshotProcessor.h
- src/meta/processors/admin/DropSnapshotProcessor.cpp
- src/meta/processors/admin/DropSnapshotProcessor.h
- src/meta/processors/admin/HBProcessor.cpp
- src/meta/processors/admin/SnapShot.cpp
- src/meta/processors/job/JobManager.h
- src/meta/test/CMakeLists.txt
- src/meta/test/SnapshotProcessorsTest.cpp
- src/meta/test/TestUtils.h
- src/mock/RpcServer.h
Fix Bug:
1. check running job may mutate data before create snapshot.
2. when create snapshot failed in some storage host, unlock the writing before return.
Add tests for Create/Drop/ListSnapshots
Tests:
Affects:
> improve snapshots and add some tests

- src/graph/executor/query/TraverseExecutor.cpp
- tests/tck/features/bugfix/MatchNodeLabelFilter.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2022
Tests:
Affects:
> fix node label filter

- tests/tck/conftest.py
- tests/tck/features/match/Path.feature
- tests/tck/features/optimizer/CasesUsingTestSpace.feature
- tests/tck/features/optimizer/PushFilterDownHashInnerJoinRule.feature
Close https://github.com/vesoft-inc/nebula/issues/5154
#5154 has been fixed by https://github.com/vesoft-inc/nebula/commit/373a847ed8eac7428a91fb68423ef34941a440ee.
Adding the coresponding tck here.
Tests:
Affects:
> Add match tck, covering fixed bugs

- src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformRule.cpp
- tests/tck/features/bugfix/LackFilterGetEdges.feature
Close #5145 
This filter can't push down, so the limit can't push down too. Report error is the only way before #5170 
Tests:
Affects:
> Fix scan efilter.

- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
> optimize match node label

- src/parser/parser.yy
- tests/tck/features/set/Set.feature
- tests/tck/features/yield/return.feature
Close https://github.com/vesoft-inc/nebula/issues/5182
Reopen https://github.com/vesoft-inc/nebula/issues/5113
Tests:
Affects:
> revert strange return

- src/meta/MetaServiceUtils.cpp
- src/meta/processors/schema/AlterEdgeProcessor.cpp
- src/meta/processors/schema/AlterTagProcessor.cpp
- src/meta/test/ProcessorTest.cpp
Introduced in #5130, `processor_test` may timeout because history schemas will be scanned. And there is a bug in alter processor...
Need to lower iteration times, it takes about 2 mins in my env with debug version, let's see if ci could survive.
Tests:
Affects:
> fix processor_test timeout

- src/interface/common.thrift
The error codes compatible with community and enterprise editions.
Tests:
Affects:
> fix error code

- src/common/function/FunctionManager.cpp
- src/graph/planner/match/SegmentsConnector.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/bugfix/AliasTypeDeduce.feature
- tests/tck/features/match/PathExpr.feature
- tests/tck/features/match/PathExprRefLocalVariable.feature
https://github.com/vesoft-inc/nebula-ent/issues/2060
Tests:
Affects:
> Fix pattern expression with same edge variable

- src/graph/executor/mutate/DeleteExecutor.cpp
- src/graph/executor/mutate/InsertExecutor.cpp
- src/graph/executor/mutate/UpdateExecutor.cpp
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/validator/MutateValidator.cpp
- src/meta/processors/index/FTIndexProcessor.cpp
- tests/tck/conftest.py
Close https://github.com/vesoft-inc/nebula-ent/issues/2105
Tests:
Affects:
> Fix memory leak, remove toss gflag

- conf/nebula-graphd.conf.default
Close https://github.com/vesoft-inc/nebula/issues/5190
The config `max_sessions_per_ip_per_user` is exposed in the production config but not in the default config.
Tests:
Affects:
> [Simple] Add `max_sessions_per_ip_per_user` to default config file

- src/common/memory/MemoryTracker.cpp
#5205 
This log may happend before GLOG initialized, have checked ThreadMemoryStats do retrurn reserved bytes, delete it.
Tests:
Affects:
> remove memtracker DLOG

- tests/Makefile
- tests/tck/features/match/Base.feature
- tests/tck/features/match/VariableLengthPattern.feature
> more TCK tests for variable pattern match clause

- src/common/expression/AttributeExpression.cpp
- src/common/expression/test/AttributeExpressionTest.cpp
- src/common/expression/test/ExpressionContextMock.h
- src/common/expression/test/ListComprehensionExpressionTest.cpp
- src/common/expression/test/PredicateExpressionTest.cpp
- tests/tck/features/expression/Attribute1.feature
- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
Reverted the changes of #5054 on AttributeExpression in an attempt to guarantee the correctness of LDBC-needed queries at the cost of reopening some minor bugs found before.
Tests:
Affects:
> Resumed the evaluation fo vertices in AttributeExpression (UTs included)

- src/graph/session/GraphSessionManager.cpp
- src/meta/processors/session/SessionManagerProcessor.cpp
Close https://github.com/vesoft-inc/nebula-ent/issues/2152, maybe relates to https://github.com/vesoft-inc/nebula-ent/issues/2176
`UpdateSessions()` should deal with errors like leader change.
Tests:
Affects:
> Fix update sessions when leader change happens

- src/common/expression/MatchPathPatternExpression.h
- src/graph/context/ast/CypherAstContext.h
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
- src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformRule.cpp
- src/graph/planner/match/MatchPathPlanner.cpp
- src/graph/planner/match/ShortestPathPlanner.cpp
- src/graph/planner/plan/Algo.cpp
- src/graph/planner/plan/Algo.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/validator/MatchValidator.cpp
- src/graph/validator/MatchValidator.h
- src/parser/MatchPath.h
- tests/tck/features/match/PathExpr.feature
- tests/tck/features/match/PathExprRefLocalVariable.feature
- tests/tck/features/match/VariableLengthPattern.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2045
match (v:player)-[e:like*2]->(b) where id(v) == 'Tony Parker' AND (b)-[*1..2]->(v) return distinct e
before
```
|  8 | Traverse       | 7            |                | outputVar: {                                        |
|    |                |              |                |   "colNames": [                                     |
|    |                |              |                |     "b",                                            |
|    |                |              |                |     "__VAR_1"                                       |
|    |                |              |                |   ],                                                |
|    |                |              |                |   "type": "DATASET", …
```
> fix match step range

- src/clients/meta/MetaClient.cpp
- src/common/graph/Response.h
- src/interface/common.thrift
- src/meta/MetaServiceUtils.cpp
- tests/tck/features/ddl/Ddl.feature
- tests/tck/features/schema/Schema.feature
Followup of Case 1 in https://github.com/vesoft-inc/nebula/issues/2671
Previous PR: #5130 
In this PR, we distinguish behaviors of adding column that is currently existed from historically existed. So users will get better hints.
Tests:
Affects:
> Update response message when adding schema historically existed

- src/graph/validator/GoValidator.cpp
- src/graph/validator/GoValidator.h
- src/graph/visitor/ExtractPropExprVisitor.cpp
- src/graph/visitor/ExtractPropExprVisitor.h
- tests/tck/features/go/GO.feature
Fix https://github.com/vesoft-inc/nebula/issues/5236
Tests:
Affects:
> fix extract props visitor

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/maintain/EdgeExecutor.cpp
- src/graph/executor/maintain/EdgeIndexExecutor.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/Base.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/2223
Tests:
Affects:
> forbid invalid prop expr used in cypher

- src/kvstore/listener/elasticsearch/ESListener.cpp
> fix delete fulltext index

- src/common/datatypes/Value.cpp
- src/common/datatypes/Value.h
- src/common/expression/AttributeExpression.cpp
- src/common/expression/test/AttributeExpressionTest.cpp
- src/common/expression/test/ListComprehensionExpressionTest.cpp
- src/common/expression/test/PredicateExpressionTest.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/expression/Attribute.feature
- tests/tck/features/expression/Attribute1.feature
- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/match/Path.feature
- tests/tck/features/match/With.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
Close https://github.com/vesoft-inc/nebula/issues/5226
Close https://github.com/vesoft-inc/nebula/issues/5249
Tests:
Affects:
Support for a new notation for property expressions to better distinguish between tag name and property name.
> Enhance attribute-accessing expression to ensure self-consistency

- tests/tck/features/go/GO.feature
- tests/tck/features/path/AllPath.feature
- tests/tck/features/path/ShortestPath.feature
- tests/tck/features/subgraph/subgraph.feature
> Add tck test

- tests/job/test_session.py
> Add more session tests

- src/common/expression/TextSearchExpression.h
- src/graph/util/test/FTindexUtilsTest.cpp
The default number of doc returned when querying ES is 10. In order to reduce users' confusion when using, for example, he has a lot of data, but in fact only 10 items can be found. When using, we query 10000 items by default, which is the maximum limit of a single ES query.
Tests:
Affects:
> modify ft index default limit size

- package/package.sh
The dump_syms tool path should be match with third party version.
This pr affect all version use nebula third party 3.3.
Tests:
Affects:
> fix third party version in package.sh

- src/common/function/FunctionManager.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/DeduceTypeVisitor.cpp
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
Close https://github.com/vesoft-inc/nebula/issues/5286
Tests:
Affects:
> rewrite none_direct_dst(e) to e._dst

- src/common/memory/MemoryUtils.cpp
minor: check is wrong , and not necessary, just print error log if ratio is set a invalid value 
Tests:
Affects:
> remove unnecessary check when print error log

- src/graph/planner/match/LabelIndexSeek.cpp
- src/graph/planner/match/MatchClausePlanner.cpp
- src/graph/planner/match/PropIndexSeek.cpp
- src/graph/planner/match/VertexIdSeek.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- tests/tck/features/basic/data.feature
- tests/tck/features/match/SeekById.feature
- tests/tck/features/optimizer/CasesUsingTestSpace.feature
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
- tests/tck/features/yield/parameter.feature
> Don't rewrite vid in list expr to or expr

- src/graph/executor/algo/SubgraphExecutor.cpp
- src/graph/executor/query/DataCollectExecutor.cpp
- tests/tck/features/bugfix/FixIterCrash.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/2336
Close https://github.com/vesoft-inc/nebula/issues/5292
The cast of iter to GetNeighborsIter using static_cast may fail and leave a non-accessible GetNeighborsIter*, which would later crash the graphd on seg fault.
Tried using dynamic_cast. On the advice by @yixinglu, changed to protect the static_cast by checking the kind of iter.
Tests:
Affects:
> Fix the crash caused by failed downcast of iter

- src/meta/processors/zone/DropHostsProcessor.cpp
- src/meta/processors/zone/MergeZoneProcessor.cpp
> fix meta crashed in #5303

- src/graph/context/Iterator.cpp
- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/BatchShortestPath.h
- src/graph/executor/algo/ShortestPathBase.cpp
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/algo/ShortestPathExecutor.cpp
- src/graph/executor/algo/SingleShortestPath.cpp
- src/graph/executor/algo/SingleShortestPath.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
- src/graph/util/Utils.cpp
- src/graph/util/Utils.h
1. Move the total rpc time from storage info to other stats
2. cleanup traverseExecutor implementation.
Tests:
Affects:
> Fix total rpc time in stats

- src/graph/planner/plan/Algo.cpp
Before
```
-----+--------------+--------------+----------------+-------------------------------
|  5 | Subgraph     | 4            |                | outputVar: {                 |
|    |              |              |                |   "colNames": [],            |
|    |              |              |                |   "type": "DATASET",         |
|    |              |              |                |   "name": "__Subgraph_5"     |
|    |              |              |                | }                            |
|    |              |              |                | src: $-._vid                 |
|    |              |              |                | tag_filter:                  |
|    |              |              |                | edge_filter:                 |
|    |              | …
```
> fix desc subgraph inputVar

- src/clients/storage/StorageClientBase.h
- src/common/base/Base.h
- src/common/datatypes/List.h
- src/common/datatypes/Value.cpp
- src/common/datatypes/Value.h
- src/common/datatypes/Vertex.h
- src/graph/context/CMakeLists.txt
- src/graph/context/iterator/GetNbrsRespDataSetIter.cpp
- src/graph/context/iterator/GetNbrsRespDataSetIter.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
tuning the one step expand in traverse executor
Tests:
Affects:
> Improve the traverse executor performance

- src/graph/context/iterator/GetNbrsRespDataSetIter.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
run traverse executor in parallel when the number rows of response greater than the threshold value.
Expand each response of RPC in parallel
Tests:
Affects:
> Traverse executor in parallel

- src/kvstore/Part.cpp
- src/kvstore/Part.h
Close https://github.com/vesoft-inc/nebula-ent/issues/2399
Close https://github.com/vesoft-inc/nebula/issues/5320
Meta does not clean up all data before receiving snapshot... The bug must have existed for quite a long time...
Delete all data by delete range. The code is quite ugly, but I don't think of any better ways...
Tests:
Affects:
> Fix meta's cleanup not work as expected

- cmake/ClangTidy.cmake
- cmake/FindMoldLinker.cmake
- cmake/nebula/LinkerConfig.cmake
use the [mold](https://github.com/rui314/mold) linker to speed up nebula compilation:
1. download the mold linker from the [release page](https://github.com/rui314/mold/releases) and decompress the tar to your `$PATH` directory, such as `$HOME/.local` by 
`tar zxf mold-1.10.1-x86_64-linux.tar.gz --strip-components=1 -C $HOME/.local/`
3. enter the nebula repo build directory
4. specify the `NEBULA_USE_LINKER` variable when you configure the cmake:
```
cmake -DNEBULA_USE_LINKER=mold ..
```
5. happy to build nebula now
Tests:
Affects:
> Support mold linker

- src/codec/RowWriterV2.cpp
- src/graph/util/SchemaUtil.cpp
- src/graph/util/SchemaUtil.h
- src/graph/validator/MutateValidator.cpp
- src/storage/query/QueryBaseProcessor-inl.h
- tests/tck/features/yield/parameter.feature
> DML support parameters

- src/graph/validator/LookupValidator.cpp
- src/storage/ExprVisitorBase.cpp
- tests/tck/features/yield/parameter.feature
https://discuss.nebula-graph.com.cn/t/topic/12100/21
Tests:
Affects:
> Fix the crash when lookup parameter expression eval in storage

- src/clients/storage/InternalStorageClient.cpp
- src/clients/storage/StorageClientBase-inl.h
- src/clients/storage/StorageClientBase.h
- src/graph/context/iterator/PropIter.cpp
- src/graph/executor/Executor.h
- src/graph/executor/StorageAccessExecutor.h
- src/graph/executor/query/AppendVerticesExecutor.cpp
- src/graph/executor/query/GetEdgesExecutor.cpp
- src/graph/executor/query/GetVerticesExecutor.cpp
- src/graph/executor/query/IndexScanExecutor.cpp
- src/graph/executor/query/ScanEdgesExecutor.cpp
- src/graph/executor/query/ScanVerticesExecutor.cpp
- src/graph/executor/query/TraverseExecutor.cpp
> Remove the lock from collectResponse in storage client

- .github/workflows/pull_request.yml
add mold linker for pull_request workflow
Tests:
Affects:
> add mold linker

- src/meta/processors/user/AuthenticationProcessor.cpp
- tests/tck/features/user/User.feature
If user does not exist `desc user xxx` will be raise "User not existed!"
Close #5141
If use does not exist `desc user xxx` will be raise "User not existed!"
add account exist verify in meta service
Tests:
manunal test:
```
(root@nebula) [(none)]> desc user u6
[ERROR (-1005)]: User not existed!
Wed, 15 Feb 2023 22:43:06 CST
```
Affects:
> If user does not exist `desc user xxx` will be raise "User not existed!"

- src/common/datatypes/Set.cpp
- src/common/datatypes/Set.h
- src/common/function/FunctionManager.cpp
- src/graph/context/ast/CypherAstContext.h
- src/graph/executor/query/FulltextIndexScanExecutor.cpp
- src/graph/planner/match/VertexIdSeek.cpp
- src/graph/planner/match/VertexIdSeek.h
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/FoldConstantExprVisitor.cpp
- src/graph/visitor/VidExtractVisitor.cpp
- src/graph/visitor/VidExtractVisitor.h
- src/graph/visitor/test/ExtractFilterExprVisitorTest.cpp
- src/graph/visitor/test/FoldConstantExprVisitorTest.cpp
- tests/tck/features/match/MatchById.feature
https://discuss.nebula-graph.com.cn/t/topic/12208
Tests:
Affects:
> Support match from id Set and fix some related issues

- tests/tck/features/yield/parameter.feature
> Small fix for parameter tck

- src/common/function/FunctionManager.cpp
- tests/tck/features/yield/return.feature
> Fix crash of list related functions

- src/graph/service/GraphService.cpp
- tests/tck/features/admin/Sessions.feature
Close https://github.com/vesoft-inc/nebula/issues/5293
Conver the client IP into ipv4 format to be compatible with the ent version
```
(root@nebula) [(none)]> show sessions
+------------------+----------+-----------+----------------------------+----------------------------+-------------------+----------+---------------+
| SessionId        | UserName | SpaceName | CreateTime                 | UpdateTime                 | GraphAddr         | Timezone | ClientIp      |
+------------------+----------+-----------+----------------------------+----------------------------+-------------------+----------+---------------+
| 1678096861048380 | "root"   | ""        | 2023-03-06T14:01:01.048380 | 2023-03-06T14:01:01.048380 | "127.0.0.1:29562" | 0        | "192.168.8.6" | …
```
> Fix client ip format in show sessions command

- src/graph/optimizer/CMakeLists.txt
- tests/tck/features/optimizer/EliminateAppendVerticesRule.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
- tests/tck/features/optimizer/PushEFilterDownRule.feature
- tests/tck/features/optimizer/PushFilterDownNodeRule.feature
Close https://github.com/vesoft-inc/nebula/issues/5396
The rule  is aimed to optimize https://github.com/vesoft-inc/nebula/issues/4273 at first, 
but this issue could be optimized by the property pruner when the flag optimize_appendvertices is on.
Tests:
Affects:
> remove EliminateAppendVerticesRule

- src/graph/session/GraphSessionManager.cpp
- src/graph/session/GraphSessionManager.h
Close https://github.com/vesoft-inc/nebula/issues/5392
When multiple threads try to increment session counts at the same time, there is a chance that `emplace()` will return false. To avoid this issue, it's recommended to use insert_or_assign instead of emplace because the check for session counts doesn't need to be too strict.
Use `insert_or_assign` instead of `emplace`.
Tests:
Affects:
> Fix `addSessionCount()` in multu-thread case

- src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
- src/graph/util/ExpressionUtils.cpp
- src/graph/util/ExpressionUtils.h
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/ttl/TTL.feature
- tests/tck/features/yield/parameter.feature
- tests/tck/ldbc/interactive_workload/ComplexReads.feature
https://github.com/vesoft-inc/nebula-ent/issues/2485
Tests:
Affects:
> Fix undefined parameter

- src/common/function/FunctionManager.cpp
- src/graph/util/ParserUtil.cpp
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/ValidatePatternExpressionVisitor.cpp
- src/parser/MatchPath.h
- src/storage/query/GetNeighborsProcessor.h
- tests/tck/features/match/Base.feature
- tests/tck/features/match/PathExprRefLocalVariable.feature
Fix https://github.com/vesoft-inc/nebula/issues/5289
Tests:
Affects:
> Pattern expression supports reference local edge variable

- src/storage/CommonUtils.cpp
Close #5376
Add a flag to control which unit that ttl uses, user **should not modify** it after one ttl column is specified. This behavior has been discussed with @MuYiYong. I think the flag should not be exposed as well. For those scenario who want to use ttl in ms, just set the flag to true once and for all before any ttl column is specified.
For example, if `ttl_use_ms` is false by default, set a ttl column as 500, so data of 500 seconds ago are expired. If user change `ttl_use_ms` from false too true, data of 500ms ago are expired. So again, don't modify it unless no more ttl columns are used.
Tests:
Affects:
> support ttl in ms

- .github/workflows/rc.yml
* add go cache
* Use latest stable version instead of fixed history version
action/setup-go@v4 enables go cache by default, if you do not specify the path of the go.sum file or close the cache, a warning will be generated
Tests:
Affects:
> add go cache

- src/common/expression/LogicalExpression.cpp
- src/graph/visitor/ExtractFilterExprVisitor.cpp
- src/graph/visitor/ExtractFilterExprVisitor.h
- tests/tck/features/optimizer/PushFilterDownBugFixes.feature
Fix https://github.com/vesoft-inc/nebula/issues/5423
Tests:
Affects:
> Fix ExtractFilterExprVisitor.

- src/common/datatypes/Value.cpp
- src/common/expression/test/RelationalExpressionTest.cpp
- src/graph/executor/logic/LoopExecutor.cpp
- tests/tck/features/expression/BugFixWithngdata.feature
Fix https://github.com/vesoft-inc/nebula/issues/5432
`EMPTY == EMPTY` shall not return true.
```
EMPTY == (x), return value: 
==      EMPTY		NULL		Others
EMPTY	NULL		FALSE		FALSE
EMPTY < (x), return value:
<	EMPTY		NULL		Others
EMPTY	NULL		NULL		NULL
```
Tried to return null in all cases if an EMPTY value is involved in comparisions. But some cases have relied on it to return FALSE. Thus, I applied the above truth table for `==` and `<`.
I think we currently haven't explained any truth table involving EMTPY or EMTPY-like values in our documents. Right? Not sure. 
Simlar to NULL (https://docs.nebula-graph.com.cn/3.4.0/3.ngql-guide/3.data-types/5.null/), we may need to explain the behaviours involving EMTPY or EMTPY-like values.
For example, queries like 
```
MATCH (v:player)-[]-(v2) WHERE …
```
> Fix the comparisions involving EMPTY.

- src/graph/visitor/DeduceTypeVisitor.cpp
- src/graph/visitor/ExtractPropExprVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.h
Sort out the code that may cause crash in the implementation of the expression visitor
Tests:
Affects:
> [Minor] Delete some fatals and comment some CHECKs

- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/With.feature
Fix https://github.com/vesoft-inc/nebula/issues/5282
MatchValidator didn't check duplicate columns comprising those generated from WITH and UNWIND.
Mark those columns from WITH and UNWIND.
Tests:
Affects:
> Avoid duplicate columns in return

- src/common/datatypes/Path.h
- tests/tck/features/match/Path.feature
Fix https://github.com/vesoft-inc/nebula/issues/5187
The same self-reflective step with +/- edge types were treated as different steps.
Consider them as equal.
Tests:
Affects:
> Fix the == operator of Path

- src/graph/visitor/PropertyTrackerVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
Fix https://github.com/vesoft-inc/nebula/issues/5329
'v.tag' means all properties of that tag are needed. They shall not be pruned by the optimizer.
Add a wildcard `"*"` into the VertexProp map in the tracker when encountered expressions like `v.tag` after the `tag` has been verified to be a real tag.
Tests:
Affects:
> Allow the expressions like 'v.tag' in return

- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/validator/GoValidator.cpp
- src/graph/validator/GoValidator.h
> Generate an plan base on the output

- src/daemons/StandAloneDaemon.cpp
- src/storage/StorageServer.cpp
Fix standalone's compile.
Tests:
Affects:
> fix standalone version's compile

- src/kvstore/raftex/RaftPart.h
> remove some raft lock for higer performance

- src/graph/service/QueryInstance.cpp
- src/graph/validator/ExplainValidator.cpp
- tests/tck/features/explain/ExplainAndProfile.feature
https://github.com/vesoft-inc/nebula/issues/5274
Support the tck format for the output of EXPLAIN
Explain/Profile has added support for the TCK output format, with the "TCK" string being appended to the kAllowedFmtType list.
related link:
- the pr link of nebula repo: https://github.com/vesoft-inc/nebula/pull/5414
- the pr link of nebula-console: https://github.com/vesoft-inc/nebula-console/pull/210
- the pr link of nebula nebula-go:https://github.com/vesoft-inc/nebula-go/pull/265
- the pr link of nebula-doc:https://github.com/vesoft-inc/nebula-docs/pull/2017
- the pr link of nebula-doc-cn:https://github.com/vesoft-inc/nebula-docs-cn/pull/2664
Tests:
Affects:
> Support the tck format for the output of EXPLAIN

- src/codec/RowWriterV2.cpp
- src/codec/RowWriterV2.h
- tests/tck/features/geo/GeoBase.feature
Fix https://github.com/vesoft-inc/nebula/issues/5459
When inserting, the geography value is converted to a WKB string format. However, it is not possible to differentiate whether a string being inserted into a property of geography type is in fact a WKB string or just an ordinary string.
So I add an argument `isWKB` to distinguish it:
```
WriteResult RowWriterV2::write(ssize_t index, folly::StringPiece v, bool isWKB)
```
Tests:
Affects:
> Add the type check when inserting geography value

- .github/workflows/rc.yml
Fix tagnum is not passed into GITHUB_OUTPUT
Tests:
Affects:
> Fix tagnum is not passed into GITHUB_OUTPUT

- .github/workflows/rc.yml
Fix tagnum is not passed into GITHUB_OUTPUT
Tests:
Affects:
> Update rc.yml (#5466)

- src/common/function/FunctionManager.cpp
- src/graph/context/ast/CypherAstContext.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
- src/graph/optimizer/rule/RemoveAppendVerticesBelowJoinRule.cpp
- src/graph/planner/match/MatchPathPlanner.cpp
- src/graph/planner/match/MatchSolver.cpp
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/validator/MatchValidator.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/match/VariableLengthPattern.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
- tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
> refactor traverse output

- resources/gflags.json
- src/common/meta/GflagsManager.cpp
- src/kvstore/Common.h
- src/kvstore/CompactionFilter.h
- src/kvstore/NebulaStore.cpp
- src/storage/CompactionFilter.h
- src/storage/test/CompactionTest.cpp
- src/storage/test/IndexWithTTLTest.cpp
- tests/admin/test_configs.py
Fix the issue that, many expired data in the bottommost level don't get garbage collected
https://github.com/vesoft-inc/nebula/issues/5438
Tests:
Affects:
> Change the compaction filter logic to let periodic compaction go through custom compaction filter, to gc expired data

- src/graph/executor/algo/CartesianProductExecutor.cpp
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/PushFilterDownCrossJoinRule.cpp
- src/graph/optimizer/rule/PushFilterDownCrossJoinRule.h
- src/graph/planner/match/MatchSolver.cpp
- src/graph/planner/match/StartVidFinder.h
- src/graph/planner/plan/Algo.cpp
- src/graph/planner/plan/Algo.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- tests/tck/features/optimizer/PushFilterDownCrossJoinRule.feature
> Push filter down cross join

- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/SingleShortestPath.cpp
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/AllShortestPaths.feature
- tests/tck/features/match/SingleShorestPath.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2554
close https://github.com/vesoft-inc/nebula-ent/issues/2558
Tests:
Affects:
> Fix shortest path crash

- src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
- src/graph/optimizer/rule/PushEFilterDownRule.cpp
- src/graph/optimizer/rule/PushFilterDownNodeRule.cpp
- src/graph/optimizer/rule/UnionAllIndexScanBaseRule.cpp
- tests/tck/features/geo/GeoBase.feature
Fix https://github.com/vesoft-inc/nebula/issues/5476
Tests:
Affects:
> fix crash of geo

- src/common/expression/Expression.h
- src/common/expression/PropertyExpression.h
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/PushFilterDownTraverseRule.cpp
- src/graph/optimizer/rule/PushFilterThroughAppendVerticesRule.cpp
- src/graph/optimizer/rule/PushFilterThroughAppendVerticesRule.h
- tests/tck/features/bugfix/LackFilterGetEdges.feature
- tests/tck/features/match/SeekById.feature
- tests/tck/features/optimizer/CollapseProjectRule.feature
- tests/tck/features/optimizer/PrunePropertiesRule.feature
- tests/tck/features/optimizer/PushFilterDownBugFixes.feature
- tests/tck/features/optimizer/PushFilterDownCrossJoinRule.feature
- tests/tck/features/optimizer/PushFilterDownTraverseRule.feature
- tests/tck/features/optimizer/PushLimitDownProjectRule.feature
- tests/tck/features/optimizer/RemoveAppendVerticesBelowJoinRule.feature
Split the optimizer rule `PushFilterDownTraverseRule` to `PushFilterThroughAppendVerticesRule` and `PushFilterDownTraverseRule`.
This pr is for refactoring purposes but also introduces some optimizations, such as non-endpoint predicates that can be pushed down before AppendVertices.
The purpose of refactoring is that the previous implementation was too ad-hoc for further optimization, and there were some conflicts between rules, so we should try to avoid similar code implementation from a more common perspective, especially for the development of optimizer.
Tests:
Affects:
> Split optimizer rules

- src/graph/util/ExpressionUtils.cpp
- tests/tck/features/optimizer/EmbedEdgeAllPredIntoTraverseRule.feature
> Fix expression util function

- .github/workflows/nightly.yml
https://github.com/vesoft-inc/nebula/issues/5474
Tests:
Affects:
> add standalone build&tck to nightly

- tests/tck/features/bugfix/ContainsFilter.feature
> fix ContainsFilter random fail

- src/graph/visitor/PropertyTrackerVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/match/MatchGroupBy.feature
part of https://github.com/vesoft-inc/nebula-ent/issues/2615
close https://github.com/vesoft-inc/nebula/issues/5491
Tests:
Affects:
> fix pruneproperties

- src/graph/validator/FindPathValidator.cpp
- src/graph/validator/GetSubgraphValidator.cpp
- tests/tck/features/yield/parameter.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2571
close https://github.com/vesoft-inc/nebula-ent/issues/2570
Tests:
Affects:
> rewrite param in subgraph & path

- src/common/expression/RelationalExpression.cpp
- tests/tck/features/expression/RelationalExpr.feature
Fix https://github.com/vesoft-inc/nebula-ent/issues/2604
Tests:
Affects:
> Fix regex expression

- src/meta/KVBasedClusterIdMan.h
Same as [Add salt when generating cluster id to reduce duplication #2545](https://github.com/vesoft-inc/nebula-ent/pull/2545)
I don't know why but there are 2 methods used to generate cluster ids
Tests:
Affects:
> Add salt when generating cluster id to reduce duplication

- src/graph/context/ast/CypherAstContext.h
- src/graph/executor/logic/ArgumentExecutor.cpp
- src/graph/optimizer/Optimizer.cpp
- src/graph/planner/CMakeLists.txt
- src/graph/planner/PlannersRegister.cpp
- src/graph/planner/match/StartVidFinder.h
- src/graph/planner/match/VariableVertexIdSeek.cpp
- src/graph/planner/match/VariableVertexIdSeek.h
- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/planner/plan/Logic.cpp
- src/graph/planner/plan/Logic.h
- src/graph/validator/MatchValidator.cpp
- tests/tck/features/match/MatchByVariable.feature
- tests/tck/features/match/PathExpr.feature
- tests/tck/features/match/PathExprRefLocalVariable.feature
- tests/tck/features/match/With.feature
#5509
The following query will execute full index scan even though the filter in where clause is from some specified vid list. it's very  slow for these cases since nebula could not find a reasonable start point for path pattern.
```
with 'Tim Duncan' as vid match (v)--(v2) where id(v)==vid return *;
```
I add a new start point seeker in match planner to generate a argument plan node referencing the input data from other clause. this argument plan node can avoid to scan all index or vertices/edges.
In this PR, I restrict the usage of the seeker for the filter related to node and exclude the case that some variable is from current match path pattern, such as:
```
with 1 as vid match (v)--(v2) where id(v)==v2 return *;
```
The index selection for variable will be supported in next pr. …
> Support variable when seeking by id in match clause

- .github/actions/tagname-action/action.yml
update unsupported syntax
Tests:
Affects:
> update unsupported action syntax

- src/graph/executor/algo/AllPathsExecutor.cpp
- tests/tck/features/path/AllPath.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2733
Tests:
Affects:
> fix allpath limit

- conf/nebula-storaged.conf.production
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
https://github.com/vesoft-inc/nebula/issues/5456 
Open the rocksdb engines in parallel to speed up the startup of storaged
Tests:
Affects:
> Feat: Speed up the startup of storaged

- src/graph/executor/query/ExpandAllExecutor.cpp
- src/graph/executor/query/ExpandAllExecutor.h
- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/validator/GoValidator.cpp
- src/graph/validator/test/QueryValidatorTest.cpp
- tests/tck/features/go/SimpleCase.feature
> simple case m to n

- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/validator/GoValidator.cpp
- tests/tck/features/go/SimpleCase.feature
> Fix simple case

- src/parser/parser.yy
- tests/tck/features/bugfix/SyntaxErrorCrash.feature
> Fix crash double free of expr.

- src/webservice/SetFlagsHandler.cpp
Fix web service crash if the request parameter is invalid. In this issue, if the config value is not string, the `item.second.asString()` in the source code will lead an exception.
Tests:
Affects:
> Fix web service crash if set flag with invalid request parameter

- src/common/utils/MetaKeyUtils.cpp
close https://github.com/vesoft-inc/nebula/issues/5574
3.5 has write a random cluster id in meta. If it is not backup/restore, storage will failed to start-up when restoring.
Tests:
Affects:
> fix cluster id is not backuped

- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/OptRule.cpp
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule.cpp
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule.h
- src/graph/optimizer/rule/PushLimitDownGetEdgesRule.cpp
- src/graph/optimizer/rule/PushLimitDownGetEdgesRule.h
- src/graph/optimizer/rule/PushLimitDownGetVerticesRule.cpp
- src/graph/optimizer/rule/PushLimitDownGetVerticesRule.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/validator/FindPathValidator.cpp
- src/graph/validator/GetSubgraphValidator.cpp
- src/graph/validator/LookupValidator.cpp
- tests/common/nebula_service.py
- tests/tck/conftest.py
Support the optimization for pushing the limit into the fulltext index scan, such as:
```
LOOKUP ON tag2 WHERE prefix(tag2.prop2,"nebula")
YIELD id(vertex) as id, tag2.prop1 as prop1, tag2.prop2 as prop2 |
LIMIT 1,1
```
```
Execution Plan (optimize time 2609 us)
-----+-------------------+--------------+----------------+--------------------------------------------------
| id | name              | dependencies | profiling data | operator info                                   |
-----+-------------------+--------------+----------------+--------------------------------------------------
|  8 | Project           | 9            |                | outputVar: {                                    |
|    |                   |              |                |   "colNames": [ …
```
> Add optimizer rule for pushing limit into the fulltext index scan 

- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/MergeLimitAndFulltextIndexScanRule.cpp
- src/graph/optimizer/rule/MergeLimitAndFulltextIndexScanRule.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
> Merge limit and full text index scan rule

- src/common/function/FunctionManager.cpp
- src/common/plugin/fulltext/elasticsearch/ESAdapter.h
- src/graph/context/ast/QueryAstContext.h
- src/graph/executor/query/FulltextIndexScanExecutor.cpp
- src/graph/executor/query/InnerJoinExecutor.cpp
- src/graph/optimizer/CMakeLists.txt
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule.cpp
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule.h
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule2.cpp
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule2.h
- src/graph/planner/Planner.cpp
- src/graph/planner/Planner.h
- src/graph/planner/ngql/LookupPlanner.cpp
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/util/CMakeLists.txt
- src/graph/util/Constants.cpp
- src/graph/util/Constants.h
- src/graph/util/ValidateUtil.cpp
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/LookupValidator.h
- src/parser/parser.yy
> Support to return score from es query

- src/common/expression/TextSearchExpression.cpp
- src/common/expression/TextSearchExpression.h
- src/common/plugin/fulltext/elasticsearch/ESAdapter.cpp
- src/common/plugin/fulltext/elasticsearch/ESAdapter.h
- src/graph/executor/query/FulltextIndexScanExecutor.cpp
- src/graph/validator/LookupValidator.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
> modify ft search

- src/graph/executor/maintain/FTIndexExecutor.cpp
- src/meta/processors/BaseProcessor-inl.h
- src/meta/processors/index/FTIndexProcessor.cpp
- src/meta/processors/schema/AlterTagProcessor.cpp
- tests/tck/features/fulltext_index/FultextIndexDDL.feature
> show analyzer when show ft index

- src/graph/executor/query/IndexScanExecutor.cpp
- tests/tck/features/match/MatchByVariable.feature
fix vesoft-inc/nebula-ent#2835
Tests:
Affects:
> Fix crash of seeking by variable in match clause

- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule2.cpp
- src/graph/optimizer/rule/PushLimitDownFulltextIndexScanRule2.h
- tests/tck/features/fulltext_index/FulltextIndexScan.feature
the `PushLimitDownFulltextIndexScanRule` does not work well since the rule pattern has changed and this issue was introduced in #5597 
Tests:
Affects:
> Fix PushLimitDownFulltextIndexScanRule 

- src/meta/processors/session/SessionManagerProcessor.cpp
- [*] enhancement
In our cluster, there are tens of thousands of sessions established, when executing listing sessions, the metad is blocked as it will print every session to the disk, it's time costed and not very necessary.
Besides, the session id is printed twice, the first time is with VLOG(3) in the above line.
Remove the unnecessary sessions print.
Affects:
> Fix too many logs print when listing sessions
> Fix too many logs print when listing sessions

- .github/workflows/pull_request.yml
Reverts vesoft-inc/nebula#5623
something wrong for sccache.
> Revert  "Change ccache to sccache"

- .github/workflows/pull_request.yml
- src/graph/executor/algo/AllPathsExecutor.cpp
- src/graph/executor/algo/AllPathsExecutor.h
close https://github.com/vesoft-inc/nebula-ent/issues/2906
close https://github.com/vesoft-inc/nebula-ent/issues/2904
before:
now:
```
(root@nebula) [nba]> go from 'Tim Duncan' over * yield id($$) as dst| find all path from $-.dst to $-.dst  over * bidirect upto 100 steps yield path as p |yield count(*)
[ERROR (-1005)]: GraphMemoryExceeded: (-2600)
Thu, 06 Jul 2023 10:45:24 CST
```
Tests:
Affects:
> fix all path memory tracker

- src/graph/planner/plan/Query.h
- src/graph/util/FTIndexUtils.cpp
- tests/tck/features/optimizer/EmbedEdgeAllPredIntoTraverseRule.feature
Close https://github.com/vesoft-inc/nebula-ent/issues/2927
Tests:
Affects:
> Fix edge all predicate embedding when generating path

- src/graph/executor/algo/ShortestPathExecutor.cpp
- src/graph/planner/match/ShortestPathPlanner.cpp
- tests/tck/features/match/AllShortestPaths.feature
- tests/tck/features/match/SingleShorestPath.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2932
if the variable name of the starting node and the ending node are the same, an error will be reported
if minStep == 0 and startVid == endVid then shortest path does not exist
Tests:
Affects:
> support find circular

- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/algo/ProduceAllPathsExecutor.h
```
(root@nebula) [nba]> find all path from 'Tim Duncan' to 'Tony Parker' over * bidirect upto 80 steps yield path as p | yield count(*)
[ERROR (-1005)]: GraphMemoryExceeded: (-2600)
```
Tests:
Affects:
> fix all path memory tacker

- src/graph/executor/algo/AllPathsExecutor.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/2906
replace collect with collectAll, the returned Future will become completed when all input futures have become completed
avoid threads continue to run After the query exits under abnormal circumstances(OOM)
Tests:
Affects:
> fix allpath memory tracker

- src/graph/validator/MutateValidator.cpp
- tests/tck/features/delete/DeleteEdge.IntVid.feature
- tests/tck/features/delete/DeleteEdge.feature
- tests/tck/features/delete/DeleteTag.IntVid.feature
- tests/tck/features/delete/DeleteTag.feature
- tests/tck/features/delete/DeleteVertex.IntVid.feature
- tests/tck/features/delete/DeleteVertex.feature
- tests/tck/features/delete/DeleteVertexWithoutEdge.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2953
Tests:
Affects:
> fix_delete_validate

- src/graph/executor/query/ExpandAllExecutor.cpp
- src/graph/executor/query/ExpandExecutor.cpp
- src/graph/executor/query/TraverseExecutor.cpp
- tests/tck/features/go/GO.feature
close https://github.com/vesoft-inc/nebula/issues/5663
iterRef returns the original iterator pointer, when multiple statements refer to the same variable, there will be competition
Tests:
Affects:
> change iterRef to iter

- src/graph/validator/SetValidator.cpp
- src/graph/validator/SetValidator.h
- tests/tck/features/set/Set.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2992
Tests:
Affects:
> fix union bug

- src/graph/executor/Executor.h
- src/graph/executor/query/AppendVerticesExecutor.cpp
- src/graph/executor/query/FilterExecutor.cpp
- src/graph/executor/query/InnerJoinExecutor.cpp
- src/graph/executor/query/LeftJoinExecutor.cpp
- src/graph/executor/query/ProjectExecutor.cpp
- src/graph/executor/query/TraverseExecutor.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/3006
collectAll holds an iterable collection type whose element type is Future, and any error in the component Future will not cause the process to terminate prematurely
collect() is similar to collectAll(), the only difference is that if any of the input Futures throws an exception, the Future will be terminated early
so when we set memory tracker, if we use folly::collect , and a thread triggers the limit of the memory threshold，the program may end and there are other threads running.
Tests:
Affects:
> fix master concurrency bug

- src/graph/service/GraphFlags.cpp
session_reclaim_interval_secs is not for reclaim session, but also for update session
Tests:
Affects:
> fix gflags's description of session_reclaim_interval_secs

- src/graph/executor/query/AppendVerticesExecutor.cpp
- src/graph/executor/query/FilterExecutor.cpp
- src/graph/executor/query/InnerJoinExecutor.cpp
- src/graph/executor/query/LeftJoinExecutor.cpp
- src/graph/executor/query/ProjectExecutor.cpp
- tests/tck/features/expression/StartsWith.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3179
When the filter operator is running concurrently, if the condition is abnormal in the scatter function `(WHERE v.player.name STARTS WITH 1)`, an error message will be returned. This exception error message needs to be captured in the gather function.
```
if (val.isBadNull() || (!val.empty() && !val.isImplicitBool() && !val.isNull())) {
return Status::Error("Failed to evaluate condition: %s. %s%s",
condition->toString().c_str(),
"For boolean conditions, please write in their full forms like",
" <condition> == <true/false> or <condition> IS [NOT] NULL.");
}
```
Tests:
Affects:
> fix filter bug

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- .github/workflows/release.yml
* change oss to minio
Tests:
Affects:
> change oss to minio

- src/graph/optimizer/OptContext.h
- src/graph/optimizer/OptGroup.cpp
- src/graph/optimizer/Optimizer.cpp
- src/graph/optimizer/Optimizer.h
- src/graph/scheduler/Scheduler.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.h
close https://github.com/vesoft-inc/nebula-ent/issues/3052
The execution plan tree is a DAG
In the optimizer phase, checkPlanDepth, explore, getPlan, pruneProperties and analyzeLifetime in the scheduling phase will recursively traverse the execution plan tree, and nodes that have been visited will be visited again.
Tests:
Affects:
> each group applies a rule only once

- src/common/function/FunctionManager.cpp
- tests/tck/features/expression/FunctionCall.feature
fix https://github.com/vesoft-inc/nebula/issues/5772
> fix round crash

- src/graph/executor/algo/AllPathsExecutor.cpp
- tests/tck/features/path/AllPath.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3390
when invoke the erase interface, if the iterator you pass in exceeds the range of std::vector (that is, greater than the end() of std::vector), then this will be undefined behavior
Tests:
Affects:
> fix limit bug

- src/graph/executor/algo/AllPathsExecutor.cpp
- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/SingleShortestPath.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/3395
Tests:
Affects:
> change collect to collectAll

- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/validator/SequentialValidator.cpp
- src/graph/validator/Validator.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/3446
```
go from 'xx' over like yield edge as e
UNION 
go from 'xx' over like yield edge as e
UNION
go from 'xx' over like yield edge as e
UNION
go from 'xx' over like yield edge as e
```
will generated 8 validator ( 1 sequential validator,  3 union validator, 4 go validator)
so when verifying with makevalidator, set max_statements * 2
BUT
```
create tag likea (age int);
create tag likeb (age int);
create tag likec (age int);
create tag liked (age int);
```
will generated 5 validator ( 1 sequential validator,  4 create tag validator)
At this time, if max_statement =3, it will not be intercepted because max_statement *2 = 6  in  makeValidate function.
Tests:
Affects:
Please confirm whether to be reflected in release notes and how to …
> fix max_statements

- src/graph/executor/algo/AllPathsExecutor.cpp
- tests/tck/features/path/NoLoop.feature
fix https://github.com/vesoft-inc/nebula/issues/5764
Use of the noloop parameter in the find path statement does not exclude the self-loop case
New logical judgement on self-loops in the AllPathsExecutor::doBuildPath() function
Tests:
Affects:
> fix:a single node self-loop when executing NOLOOP

- src/common/memory/MemoryTracker.h
- tests/tck/features/path/NoLoop.feature
https://github.com/vesoft-inc/nebula/issues/5807
try to fix it 
Tests:
Affects:
> fix-MemoryTracker master

- tests/common/comparator.py
- tests/tck/features/path/NoLoop.feature
In pr https://github.com/vesoft-inc/nebula/pull/5805, results were the same but the test framework reported an error.
In compare_node(lhs, rhs),If lhs.tags == [] and rhs.tags is None, the two tags should be equal.
Tests:
Affects:
> fix compare node

- README.md
polishing readme, the cncf logo was broken in recent landscape site refactor, this change mainly fixed that.
> chore: fix broken image and lift docs URLs

- tests/Makefile
Avoid master incompatibility leading to CI failure. 
Fixed the nebula-python version to avoid similar problems.
Tests:
Affects:
> Fixed nebula-python version instead of master

- src/storage/query/ScanEdgeProcessor.cpp
fix possible graph coredump when metadata refresh during certain query invoke ScanEdgeProcessor::checkAndBuildContexts especially in asan binary
return the ret when it is not succeeded
Tests:
Affects:
> fix possible graph coredump when metadata refresh during certain query invoke ScanEdgeProcessor::checkAndBuildContexts especially in asan binary

- src/graph/executor/query/ExpandAllExecutor.cpp
- src/graph/executor/query/ExpandExecutor.cpp
- src/graph/planner/plan/Query.h
- tests/tck/features/go/SampleLimit.feature
- tests/tck/features/go/SampleLimit.intVid.feature
- tests/tck/features/optimizer/PushSampleDownRule.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3528
Tests:
Affects:
> push step limit down storage 

- src/graph/optimizer/rule/GeoPredicateIndexScanBaseRule.cpp
- tests/tck/features/geo/GeoBase.feature
Fix https://github.com/vesoft-inc/nebula/issues/5919
When geo indexes and other indexes are on a tag/edge type, the services will crash because it may wrongly choose a non-geo index for a geo-related query.
Tests:
Affects:
> fix the bug that index scan rule chooses a wrong geo index

- src/common/network/NetworkUtils.cpp
- src/common/network/NetworkUtils.h
- src/meta/processors/job/DownloadJobExecutor.cpp
- src/webservice/SetFlagsHandler.cpp
* Fixed a security bug involving shell injection
* Fixed a security bug involving authentication bypass
> Fixed vulnerability issues

- src/graph/executor/Executor.cpp
- src/graph/executor/query/LimitExecutor.cpp
- src/graph/stats/GraphStats.cpp
- src/graph/stats/GraphStats.h
- [ ✅] feature
Add-Monitoring-Metrics-to-NebulaGraph
5841
Tests:
- [✅] N/A
Affects:
Add-Monitoring-Metrics-to-NebulaGraph
> Add Monitoring Metrics to NebulaGraph #5841

- src/graph/planner/match/MatchSolver.cpp
- src/graph/planner/match/MatchSolver.h
- src/graph/util/OptimizerUtils.cpp
- src/graph/util/OptimizerUtils.h
- tests/common/plan_differ.py
- tests/tck/features/match/PushFilterDown.feature
- tests/tck/features/yield/parameter.feature
https://discuss.nebula-graph.com.cn/t/topic/15979
进行全量索引扫描时,无法将条件下推至底层IndexScan算子,而利用索引进行前缀搜索时可以。
When performing a full index scan, it is not possible to push down the conditions to the underlying IndexScan operator, whereas it is possible when using the index for prefix searches.
修改OptimizerUtils.h中的函数,使其在未找到最佳索引时,仍然会接受filter并写入`IndexQueryContext`中。
此修改仅能让以and连接的条件下推。
修改MatchSolver.cpp,使其能同样识别OR类型表达式。
在tck测试中,对于未经过转换的字典对象,不再将其key放入keylist,因为该情况后续未使用keylist
直接通过keylist是否为空判断字典是否不存在嵌套
Tests:
Affects:
> Optimize filter pushdown and fix the bug in TCK tests.

- CMakeLists.txt
- src/common/base/test/CMakeLists.txt
- src/common/datatypes/test/CMakeLists.txt
- src/common/expression/test/CMakeLists.txt
- src/common/function/FunctionManager.cpp
- src/common/function/test/CMakeLists.txt
- src/common/function/test/FunctionManagerTest.cpp
- src/common/geo/test/CMakeLists.txt
- src/common/utils/test/CMakeLists.txt
https://github.com/vesoft-inc/nebula/pull/5846
给pr5846修复相关的test cmake,我看这个ci卡了几个月的了..fix一下
在FunctionManager中,新增了proxygen,所以涉及到FunctionManager相关的test就需要同样增加proxygen的库.
Tests:
Affects:
> fix cmake error in pr #5846

- conf/nebula-graphd.conf.default
- conf/nebula-metad.conf.default
- conf/nebula-standalone.conf.default
- conf/nebula-storaged-listener.conf.default
- conf/nebula-storaged.conf.default
- src/daemons/SetupLogging.cpp
#5688 
add option log_clean_days to enable build-in log rotation enabled leveraging glog
use google::EnableLogCleaner func
Tests:
Affects:
> option to enable build-in log rotation enabled leveraging glog #5688

- src/common/function/FunctionManager.cpp
return round(5) crash
add type check
Tests:
Affects:
> fix round(5) crash, check type error

- src/common/expression/VariableExpression.h
- src/graph/util/ExpressionUtils.cpp
- tests/tck/features/bugfix/ParameterQuery.feature
- tests/tck/features/match/Path.feature
- tests/tck/features/yield/parameter.feature
> fix IndexScan with label containing parameters
