- src/console/CmdProcessor.cpp
- src/console/CmdProcessor.h
> Support semicolon at the end of "exit" sentence

- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
> Support unreserved keywords

- src/graph/test/SchemaTest.cpp
- src/parser/parser.yy
> improve unreserved keywords feature

- src/common/base/test/CMakeLists.txt
- third-party/rocksdb/build.sh
> fixed parallel compilation errors

- etc/nebula-graphd.conf.default
- src/daemons/GraphDaemon.cpp
- src/graph/GraphFlags.cpp
- src/graph/GraphFlags.h
- src/kvstore/raftex/RaftPart.cpp
> Fixed number of worker threads

- src/meta/processors/schemaMan/ListEdgesProcessor.cpp
- src/meta/processors/schemaMan/ListTagsProcessor.cpp
> remove unused code

- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/meta/ActiveHostsMan.cpp
- src/meta/ActiveHostsMan.h
- src/meta/processors/admin/HBProcessor.cpp
Fix meta daemons crashed because of invalid operation when leader has not been elected.
> fix metad crashed when reboot

- src/common/base/NebulaKeyUtils.h
> Use basic type instead of int32/int64

- src/graph/DescribeSpaceExecutor.cpp
- src/graph/test/GoTest.cpp
- src/kvstore/KVEngine.h
- src/kvstore/KVStore.h
- src/kvstore/LogEncoder.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/PartManager.h
- src/kvstore/raftex/RaftPart.h
- src/meta/client/MetaClient.h
> fix typos and remove extra semicolons

- src/kvstore/NebulaStore.cpp
- src/meta/ActiveHostsMan.h
Fix dangle ptr of kvstore in ProcessorTest.
> fix dangling ptr of ActiveHostsMan in ut

- CMakeLists.txt
- src/common/time/CMakeLists.txt
- src/common/time/Duration.cpp
- src/common/time/WallClock.cpp
- src/common/time/WallClock.h
- src/common/time/detail/TscHelper.cpp
- src/common/time/detail/TscHelper.h
- src/common/time/test/CMakeLists.txt
- src/common/time/test/DurationBenchmark.cpp
- src/common/time/test/WallClockBenchmark.cpp
- src/common/time/test/WallClockTest.cpp
- src/console/CliManager.cpp
To provide much faster xxxNowInSec() and xxxNowInMilliSec() methods
This class will replace TimeUtils class in a separate PR
> Added WallClock class

- src/common/test/CMakeLists.txt
- src/graph/DescribeEdgeExecutor.cpp
- src/graph/DescribeSpaceExecutor.cpp
- src/graph/DescribeTagExecutor.cpp
- src/graph/Executor.cpp
- src/graph/Executor.h
- src/graph/GoExecutor.cpp
- src/graph/InsertEdgeExecutor.cpp
- src/graph/InsertEdgeExecutor.h
- src/graph/InsertVertexExecutor.cpp
- src/graph/InsertVertexExecutor.h
- src/graph/UseExecutor.cpp
- src/graph/test/CMakeLists.txt
- src/graph/test/DataTest.cpp
- src/parser/test/ParserTest.cpp
1、Support insert multi tags
2、Support insert multi edges
> Support insert multi tags and edges

- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/test/NebulaStoreTest.cpp
> Fix init bug in nebula store

- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
- src/graph/test/TestEnv.cpp
- src/kvstore/KVStore.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/Part.cpp
- src/kvstore/Part.h
- src/kvstore/PartManager.h
- src/kvstore/plugins/hbase/HBaseStore.h
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
- src/kvstore/test/NebulaStoreTest.cpp
- src/kvstore/wal/FileBasedWal.cpp
- src/meta/ActiveHostsMan.cpp
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/test/ProcessorTest.cpp
- src/meta/test/TestUtils.h
- src/storage/BaseProcessor.inl
- src/storage/test/StorageClientTest.cpp
- src/storage/test/TestUtils.h
This is the basic feature for cluster deployment.
> Support multi copies for kvstore

- src/console/CliManager.cpp
- src/console/CliManager.h
- src/console/CmdProcessor.cpp
- src/console/CmdProcessor.h
- src/console/NebulaConsole.cpp
- src/graph/ExecutionPlan.cpp
- src/interface/graph.thrift
Mainly improved the following three humanized output:
1)   prompt enhancement, including user, host, current space name
2)  After successfully executing nGQL and outputting the content,  add a blank line
3)  NGQL output, head and data changed to left alignment
close #427
> Improve console humanized output

- src/graph/GoExecutor.cpp
- src/graph/test/GoTest.cpp
close #632 
I didn't think it through when I implemented the _DISTINCT_ .  And some corresponding tests have been added.
> Fix crash when vertex not exist.

- src/common/base/Base.h
- src/common/base/NebulaKeyUtils.h
- src/common/filter/Expressions.h
- src/daemons/CMakeLists.txt
- src/dataman/RowReader.h
- src/graph/GoExecutor.cpp
- src/interface/storage.thrift
- src/meta/test/CMakeLists.txt
- src/storage/Collector.h
- src/storage/CommonUtils.h
- src/storage/QueryBaseProcessor.h
- src/storage/QueryBaseProcessor.inl
- src/storage/QueryBoundProcessor.cpp
- src/storage/QueryBoundProcessor.h
- src/storage/QueryEdgePropsProcessor.cpp
- src/storage/QueryEdgePropsProcessor.h
- src/storage/QueryStatsProcessor.cpp
- src/storage/QueryStatsProcessor.h
- src/storage/QueryVertexPropsProcessor.cpp
- src/storage/test/AdHocSchemaManager.cpp
- src/storage/test/AdHocSchemaManager.h
- src/storage/test/CMakeLists.txt
- src/storage/test/QueryBoundTest.cpp
- src/tools/storage-perf/CMakeLists.txt
This is the basic version for filter in storage layer.
With this pr,  the filter could work at least. 
Subtask of #67
> Implement filter in storage

- docs/CNAME
> Added CNAME file in docs

- src/common/filter/FunctionManager.cpp
- src/graph/test/YieldTest.cpp
> Fix crash when call hash.

- src/kvstore/NebulaStore.cpp
- src/kvstore/RocksEngine.h
> Fix unstable nebula_store_test(#664)

- src/storage/client/StorageClient.cpp
- src/storage/client/StorageClient.h
- src/storage/client/StorageClient.inl
- src/storage/test/StorageClientTest.cpp
- src/tools/storage-perf/StoragePerfTool.cpp
> Implement leader change logic

- src/common/base/SignalHandler.cpp
- src/common/base/SignalHandler.h
- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
- src/daemons/StorageDaemon.cpp
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/raftex/RaftexService.cpp
- src/kvstore/raftex/RaftexService.h
- src/kvstore/raftex/test/RaftexTestBase.cpp
- src/kvstore/test/NebulaStoreTest.cpp
- src/meta/test/TestUtils.h
- src/storage/test/TestUtils.h
1: fix crash when thrift service port has been used
2: fix storage crash when raft service port has been used
>  fix crash when thrift service port has been used

- src/common/filter/FunctionManager.cpp
> Fixed confusing error message for function call expression

- src/graph/test/ConfigTest.cpp
fix ut sometimes because of register config async.
> fix ConfigTest occasional failure

- scripts/nebula.service
> Improved nebula.service

- src/common/fs/FileUtils.cpp
- src/common/fs/FileUtils.h
> Extend FileUtils::makeDir with customized permission mode

- README-CN.md
- docs/manual-CN/get-started.md
- docs/manual-CN/nGQL-tutorial.md
- docs/nGQL-tutorial.md
comment ngql tutorial
update wechat link
>  comment ngql tutorial

- src/daemons/GraphDaemon.cpp
> Fixed improper setting of networking IO threads in Graphd

- src/console/CmdProcessor.cpp
> Improved displaying in nebula console

- .dockerignore
- .github/workflows/ci.yaml
- Ignore LICENSES folder in docker container
- Disable GitHub actions in PR
> Disable GitHub actions in PR

- src/client/go/nebula/client.go
> Make execute function of graph go client public

- docs/get-started.md
- docs/manual-CN/get-started.md
Fixed issue with pipeline execution command in get-start document.
> Fixed issue with pipeline execution command in get-start document.

- CMakeLists.txt
- cmake/FindPCHSupport.cmake
- src/common/filter/Expressions.cpp
- src/common/filter/Expressions.h
- src/graph/Executor.cpp
- src/graph/InterimResult.h
- src/graph/SchemaHelper.cpp
- src/storage/UpdateEdgeProcessor.cpp
- src/storage/UpdateVertexProcessor.cpp
* Fixed compilation error
* Fixed PCH support for Clang
> Fixed build with Clang

- etc/nebula-graphd.conf.default
- etc/nebula-metad.conf.default
- etc/nebula-storaged.conf.default
set `ws_ip` default value `127.0.0.1`
> Add default http service ip in service configure files 

- .github/workflows/docker.yaml
- Try to fix github actions error in #949 
close #949
> Rename github actions environment variables

- README-CN.md
- docs/README.md
> Fixed broken links

- src/client/java/build.sh
- src/tools/importer/pom.xml
#910 Usage case: 
```
java -jar target/importer-1.0.0-beta.jar args
```
> Support IMPORTER assembled with its dependencies

- docs/how-to-build.md
- docs/manual-CN/how-to-build.md
Add building with docker container to `how-to-build`.
> [Doc] Update how to build

- src/meta/processors/admin/AdminClient.cpp
> Fixed bug due to undefined eval order on arguments of function call

- .dockerignore
- .github/workflows/docker.yaml
- package/nebula.spec
- Add more ignored files for docker
- Use `$(nproc)` threads to package
- Correct schedule UTC time
> Correct cron job schedule time and ignore more files for docker image

- src/storage/BaseProcessor.h
- src/storage/GetUUIDProcessor.h
- src/storage/client/StorageClient.inl
Fix leader is not updated when LEADER_CHANGED returned or exception occurs.
> fix leader is not updated in uuid

- src/parser/parser.yy
> Fixed memory leak in parser

- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
fixed the possible crash(Found by running fuzzy test).
> Fixed crash in parser

- docs/manual-CN/interfaces/kv-interfaces.md
- docs/manual-EN/interfaces/kv-interfaces.md
Update kv interface, address wum's comments.
> [doc]update kv interface

- docs/manual-CN/statement-syntax/data-administration-statements/download-and-ingest-statements/download-and-ingest-syntax.md
- docs/manual-EN/statement-syntax/data-administration-statements/download-and-ingest-statements/download-and-ingest-syntax.md
> [doc]Download and ingest

- src/common/fs/FileUtils.cpp
- src/common/fs/FileUtils.h
> Fix console couldn't read soft link

- docs/manual-EN/statement-syntax/data-manipulation-statements/delete-syntax.md
- src/graph/test/FetchVerticesTest.cpp
- src/meta/test/BalanceIntegrationTest.cpp
- src/storage/test/QueryBoundBenchmark.cpp
- src/storage/test/QueryBoundTest.cpp
- src/storage/test/QueryStatsTest.cpp
- src/storage/test/QueryVertexPropsTest.cpp
- src/storage/test/StorageClientTest.cpp
- src/storage/test/TestUtils.h
> fix typo vetex

- docs/manual-EN/functions-and-operators/comparison-functions-and-operators.md
As title, translated from #1101
> [doc]add-udf-is-on-EN

- src/meta/test/ConfigManTest.cpp
- src/storage/test/StorageClientTest.cpp
- src/storage/test/TestUtils.h
Wait until all leaders have been elected
> fix ut fail when mockStorageServer takes longer time to open rocksdb

- etc/nebula-storaged.conf.default
After #857, the default value of rocksdb option is in json style, update the template.
> Update default storage conf, modify rocksdb options default value

- src/graph/GoExecutor.cpp
- src/graph/test/GoTest.cpp
Issue #1192  Fixed the bug where the default value of the edge prop could not be obtained correctly.
> Fixed the bug when using multi edge

- etc/nebula-graphd.conf.default
> Add local_ip option to etc/nebula-graphd.conf.default

- src/graph/test/SchemaTest.cpp
http://ci.vesoft.com/job/Nebula-Graph-UnitTest/2707/console
> Fix failed SchemaTest

- docs/manual-CN/README.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
- docs/manual-EN/README.md
log EN and update toc
translating from #1235
> [doc]add glog curl command EN

- src/kvstore/NebulaStore.cpp
There are some other problems when using multiple disks.   
Let's open another pr for it,  @darionyaphet   Let's use #1266 to track it.
> Fix bug when ingesting files

- docs/manual-CN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/3.utility-statements/show-syntax.md
> [doc]show parts

- docs/manual-CN/1.overview/2.quick-start/3.supported-clients.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
- docs/manual-CN/README.md
- docs/manual-EN/1.overview/2.quick-start/3.supported-clients.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
- docs/manual-EN/README.md
1. add default value and change format in RocksDB Compact and Flush
2. ref to go and python client in TOC
> [doc]update compaction and flush，TOC

- src/common/stats/StatsManager.cpp
- src/common/stats/StatsManager.h
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/MetaStats.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/admin/HBProcessor.h
- src/meta/test/CMakeLists.txt
- src/storage/CMakeLists.txt
1. modify register stats.
2. add heartbeat stats in meta
[supported metric of meta/storage](https://www.yuque.com/nebulagraph/euuoip/otv64x)
> update storage/meta metrics

- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/log.md
1. update log level
2. fix minor errors in doc
> [doc]update log level

- docs/manual-CN/1.overview/1.concepts/1.data-model.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/rocksdb-compaction-flush.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
- docs/manual-EN/1.overview/1.concepts/1.data-model.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/delete-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/storage-service-administration/storage-balance.md
Changes in this pr:
1. batch scale in  code pr #1243 
2. add new gflag parameters
3. change pict size in data model
4. add edge ranking in CRUD
5. update configs code pr #1273
> [doc]Doc supplement

- src/parser/GraphScanner.h
Thanks to @jievince and @yixinglu for the testing and report.
> Fixed buffer overflow in GraphScanner

- docs/manual-CN/2.query-language/2.functions-and-operators/set-operations.md
- docs/manual-CN/2.query-language/3.language-structure/property-reference.md
- docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
- docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
- docs/manual-EN/2.query-language/2.functions-and-operators/set-operations.md
- docs/manual-EN/2.query-language/3.language-structure/property-reference.md
- docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-space-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/go-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/insert-vertex-syntax.md
Changes in this pr:
1.  Unify query format in doc to `nebula> …`
2. Add insert multiple vertices syntax.
> [doc]unify format

- README-CN.md
- README.md
- docker/README.md
- scripts/README.md
- share/README.md
- src/README.md
- src/client/go/README.md
- src/client/java/README.md
- src/tools/importer/README.md
- src/tools/spark-sstfile-generator/README.md
- src/tools/storage-perf/README.md
Update all the README files in nebula repo excepts docs.
> [doc]update READMEs

- src/storage/BaseProcessor.h
- src/storage/BaseProcessor.inl
- src/storage/UpdateEdgeProcessor.cpp
- src/storage/UpdateVertexProcessor.cpp
> Update operations return leader info when leader change event happens

- src/daemons/MetaDaemon.cpp
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/test/NebulaStoreTest.cpp
- src/meta/test/BalanceIntegrationTest.cpp
- src/storage/GetProcessor.cpp
- src/storage/GetUUIDProcessor.h
- src/storage/QueryBaseProcessor.inl
- src/storage/QueryEdgeKeysProcessor.cpp
- src/storage/QueryEdgePropsProcessor.cpp
So users could use read interfaces to do preheat now. 
@zlcook @zhangguoqing
> Read on leader

- src/graph/GroupByExecutor.cpp
- src/graph/SetExecutor.cpp
- src/parser/MaintainSentences.h
Fix 2 problem in this pr:
1. possible crash problem in SetExecutor.
2. memory leak in ColumnSpecification.
> Fix graphd crash problem caused by SetExecutor.

- src/graph/CreateEdgeExecutor.cpp
- src/graph/CreateSpaceExecutor.cpp
- src/graph/CreateTagExecutor.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/processors/partsMan/CreateSpaceProcessor.cpp
- src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
- src/meta/processors/schemaMan/CreateTagProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/parser/AdminSentences.h
- src/parser/MaintainSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
This option allows you to check if the space/tag/edge
that you create already exists in the database.
example:
create space if not exists testspace
create tag if not exists testtag()
create edge if not exists edge1()
close #1366
> Added "if not exists" option to create space/tag/edge.

- src/kvstore/wal/FileBasedWal.cpp
- src/meta/processors/admin/AdminClient.cpp
Improve unstable test case snapshot_command_test .
> fix unstable problem for link Wal file

- CODE_OF_CONDUCT.md
> [doc]CODE_OF_CONDUCT

- src/jni/java/pom.xml
Update jni pom for uploading to maven central later.
> update jni pom

- README.md
> [doc]update slack link and YouTube link

- src/storage/GetUUIDProcessor.h
My bad, we should not write in synchronous way, which would cause all worker thread blocked.
> fix dead lock in uuid

- src/daemons/GraphDaemon.cpp
- src/daemons/MetaDaemon.cpp
#1501 
Using SCOPE_EXIT to avoid manually stop.
NO.
Manually test.
> Using SCOPE_EXIT to stop webservice.

- src/kvstore/NebulaStore.cpp
Compaction is executed in multiple threads, that is, all rocksdb engines
are compact at the same time when a compact command is received.
> Make compact operations parallel

- docs/manual-CN/1.overview/2.quick-start/2.FAQ.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
- docs/manual-EN/1.overview/2.quick-start/2.FAQ.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
remove load_data_interval_secs in doc.
Code pr #1236
> [doc]remove load_data_interval_secs in doc

- src/common/base/Status.h
- src/common/base/test/StatusTest.cpp
- src/common/filter/Expressions.cpp
- src/console/CmdProcessor.cpp
- src/graph/ExecutionPlan.cpp
- src/graph/GoExecutor.cpp
- src/graph/ReturnExecutor.cpp
- src/graph/SetExecutor.cpp
- src/parser/GQLParser.h
- src/parser/GraphScanner.h
- src/parser/parser.yy
> Support print parse error to log

- docs/manual-CN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/1.data-definition-statements/create-tag-edge-syntax.md
> [doc]fix create tag if not exists

- docs/manual-CN/1.overview/3.design-and-architecture/2.storage-design.md
- docs/manual-EN/1.overview/3.design-and-architecture/2.storage-design.md
as title. There is an error in doc, vertex id is 8 bytes rather than 4. All fixed.
> [doc]vertex id 8 bytes

- README-CN.md
- README.md
1. Added Supported Programming Clients section to both the English and Chinese version
2. Added Facebook page as a contact channel to the English version
> [doc]Updated README

- package/nebula.spec
Fix https://github.com/vesoft-inc/nebula/runs/374607476
Package db_dump to rpm.
NO.
Manually.
> Add db_dump to installation files.

- docs/manual-CN/3.build-develop-and-administration/1.build/1.build-source-code.md
- docs/manual-EN/3.build-develop-and-administration/1.build/1.build-source-code.md
translating from #1565 
thanks for taking care of this dear dutor @dutor
> [doc]add build with source cn and fix lints

- .github/workflows/build.yaml
- .github/workflows/pull_request.yaml
Add cpp lint checks for each PR.
> Add cpplint job

- src/storage/StorageServiceHandler.cpp
- src/storage/StorageServiceHandler.h
- src/storage/query/QueryEdgePropsProcessor.cpp
- src/storage/query/QueryEdgePropsProcessor.h
So the slow read request will not disrupt the normal hear beat logic.
> Separate read/write thread pool on storaged

- docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
- docs/manual-EN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/fetch-syntax.md
> [doc] fetch prop on * $vid

- src/storage/test/IndexTest.cpp
- src/tools/storage-perf/CMakeLists.txt
- src/tools/storage-perf/StorageIndexWritePerfTool.cpp
**Describe:**
- withoutIndex: Without index, and doesn't through way asyncAtomicOp.
- unmatchIndex: Without match index, and through asyncAtomicOp.
- attachIndex: One index, the index contains all the columns of tag.
- duplicateVerticesIndex: One index, and insert deplicate vertices.
- multipleIndex: Three indexes by one tag.
```
total_vertices_size = 2000000
============================================================================
withoutIndex                                                  3.07s  326.21m
unmatchIndex                                                  4.52s  221.15m
attachIndex                                                  39.91s   25.06m
duplicateVerticesIndex                                       46.00s   21.74m
multipleIndex …
```
> Index write benchmark

- docs/manual-CN/1.overview/2.quick-start/1.get-started.md
> [Doc] Minor fix

- src/webservice/Router.h
Fix https://github.com/vesoft-inc/nebula/runs/393715765
@yixinglu  We need a release building triggered by PR to avoid error like this.
NO
> Suppress unused value warning in Webservice/Router

- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/pull_request.yaml
Enable docker and package build steps in action
> cherry-pick #1672 to rc3 branch

- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/release.yaml
> Replace shell with bash for some action jobs

- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/release.yaml
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVertexProcessor.cpp
> cherry pick #1681

- src/kvstore/KVStore.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/plugins/hbase/HBaseStore.cpp
- src/kvstore/plugins/hbase/HBaseStore.h
- src/meta/ActiveHostsMan.cpp
- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/admin/CreateSnapshotProcessor.cpp
- src/meta/processors/admin/DropSnapshotProcessor.cpp
- src/meta/processors/configMan/RegConfigProcessor.cpp
- src/meta/processors/configMan/SetConfigProcessor.cpp
- src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
- src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
- src/meta/processors/indexMan/DropEdgeIndexProcessor.cpp
- src/meta/processors/indexMan/DropTagIndexProcessor.cpp
- src/meta/processors/partsMan/CreateSpaceProcessor.cpp
- src/meta/processors/partsMan/DropSpaceProcessor.cpp
- src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
- src/meta/processors/schemaMan/AlterTagProcessor.cpp
- src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
- src/meta/processors/schemaMan/CreateTagProcessor.cpp
- src/meta/processors/schemaMan/DropEdgeProcessor.cpp
- src/meta/processors/schemaMan/DropTagProcessor.cpp
Add a sync in LastUpdateTimeMan::update
PS: In 3 replicas env, sync only make sure that at least one of the follower has committed. This PR could help in most cases. If we want to totally solve it out, either client only send request to leader of meta server, or write through in meta server, which need be considered more carefully later.
> sync after space/schema changes

- .github/workflows/build.yaml
- .github/workflows/pull_request.yaml
- src/kvstore/KVStore.h
- src/kvstore/NebulaStore.cpp
- src/kvstore/NebulaStore.h
- src/kvstore/plugins/hbase/HBaseStore.cpp
- src/kvstore/plugins/hbase/HBaseStore.h
- src/meta/ActiveHostsMan.cpp
- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/configMan/RegConfigProcessor.cpp
- src/meta/processors/configMan/SetConfigProcessor.cpp
- src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
- src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
- src/meta/processors/indexMan/DropEdgeIndexProcessor.cpp
- src/meta/processors/indexMan/DropTagIndexProcessor.cpp
- src/meta/processors/partsMan/CreateSpaceProcessor.cpp
- src/meta/processors/partsMan/DropSpaceProcessor.cpp
- src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
- src/meta/processors/schemaMan/AlterTagProcessor.cpp
- src/meta/processors/schemaMan/CreateEdgeProcessor.cpp
- src/meta/processors/schemaMan/CreateTagProcessor.cpp
- src/meta/processors/schemaMan/DropEdgeProcessor.cpp
- src/meta/processors/schemaMan/DropTagProcessor.cpp
- src/parser/CMakeLists.txt
Cherry pick #1690 #1689  #1691
> Cherry pick #1690 #1689 #1691

- cmake/ThriftGenerate.cmake
- src/parser/CMakeLists.txt
> Relax warning levels on thrift and parser

- etc/nebula-graphd.conf.default
- src/graph/GraphFlags.cpp
- src/graph/SessionManager.cpp
Session should not have been expired if `FLAGS_session_idle_timeout_secs` is zero
> Fixed session timeout

- src/common/base/ThriftTypes.h
- src/interface/common.thrift
> Remove the duplicate definition of IndexID.

- src/graph/FetchVerticesExecutor.cpp
> cherry pick (#1700)

- src/graph/test/IndexTest.cpp
- src/graph/test/SchemaTest.cpp
- src/interface/meta.thrift
- src/meta/MetaServiceUtils.cpp
- src/meta/MetaServiceUtils.h
- src/meta/processors/BaseProcessor.h
- src/meta/processors/BaseProcessor.inl
- src/meta/processors/indexMan/CreateEdgeIndexProcessor.cpp
- src/meta/processors/indexMan/CreateTagIndexProcessor.cpp
- src/meta/processors/schemaMan/AlterEdgeProcessor.cpp
- src/meta/processors/schemaMan/AlterTagProcessor.cpp
- src/meta/test/ProcessorTest.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/storage/query/QueryBaseProcessor.inl
```
It mainly includes the following parts
1)    use ttl when create tag/edge,  drop ttl when alter tag/edge
       not use ttl when create tag/edge ,  add ttl when alter tag/edge
2)     tag/edge contains index,   not  used  ttl when alter tag/edge
3)     tag/edge uses ttl,   not  create index
4)     add the above unit tests
5)    change columns are not allowed when the column is ttl_col
```
> Check TTL before creating index

- docs/manual-CN/1.overview/2.quick-start/2.FAQ.md
- docs/manual-CN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
- docs/manual-EN/1.overview/2.quick-start/2.FAQ.md
- docs/manual-EN/3.build-develop-and-administration/3.deploy-and-administrations/server-administration/configuration-statements/configs-syntax.md
As title. Add doc on why invalid config happens.
> [doc]Invalid config

- src/graph/DescribeEdgeIndexExecutor.cpp
- src/graph/DescribeTagIndexExecutor.cpp
- src/graph/DropEdgeIndexExecutor.cpp
- src/graph/DropTagIndexExecutor.cpp
When drop edge index, the error message error as below : 
```
(user@127.0.0.1:6999) [my_space]> drop edge index e_index_1;
[ERROR (-8)]: Index not found for tag 'e_index_1'
Mon Feb 24 10:17:26 2020
```
> fix output error for drop index and desc index

- src/kvstore/test/CMakeLists.txt
- src/kvstore/test/PartPerformanceTest.cpp
This PR is an improvement on #983 . 
Improve the following ：
1，Changed CMakeList file form `nebula_add_test` to `nebula_add_executable`
2,  Fixed the `stack-buffer-overflow` error for data load.
3,  Added some comments for test description.
> Test partition scan performance

- src/storage/CompactionFilter.h
[issue 1810: old data may cause storaged crash in compact](https://github.com/vesoft-inc/nebula/issues/1810)
> fix issue #1810 old data may cause storaged crash in compact

- src/common/fs/FileUtils.cpp
- src/common/fs/test/FileUtilsTest.cpp
- src/kvstore/RocksEngine.cpp
- src/kvstore/wal/FileBasedWal.cpp
> fix makedir failed when dir is SYM_LINK

- src/graph/UpdateEdgeExecutor.cpp
- src/graph/UpdateEdgeExecutor.h
- src/graph/test/UpdateTest.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
Now after updating the out-edges successfully,  we update in-edges.
> Fix update logic after store properties on in-edges.

- docs/manual-CN/1.overview/1.concepts/2.nGQL-overview.md
- docs/manual-EN/1.overview/1.concepts/2.nGQL-overview.md
> [doc]comment out go upto

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/package.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/release.yaml
When the pr run ci failed, we want to re-run, it will fail on checkout. 
reference from `https://github.com/actions/checkout/issues/23`
> fix pull request re-run failed

- src/meta/client/MetaClient.cpp
- src/meta/client/MetaClient.h
- src/meta/processors/schemaMan/ListEdgesProcessor.cpp
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
> [Cherrypick] RC4 #1970 #1962

- .github/pull_request_template.md
> [doc]add-checklist-in-pr-template

- src/console/NebulaConsole.cpp
> Strict check the validation of console arguments.

- src/graph/CloudAuthenticator.cpp
- src/graph/test/CloudAccountAuthTest.cpp
for support cloud auth，
Remove token authentication
> support cloud auth

- README-CN.md
- README.md
update README link to docs.
TODO:update cn README.
Chinses doc site is under deployment for the time.
> [doc]update-readme

- .github/workflows/pull_request.yaml
pr of cloud branch triggers ci
> github action add cloud branch

- CODE_OF_CONDUCT.md
> [doc] change code of conduct

- CMakeLists.txt
> Fixed an error when using Clang and opening ENABLE_UBSAN.

- src/graph/test/UpdateTest.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/mutate/UpdateVertexProcessor.cpp
- src/storage/test/IndexTest.cpp
- src/storage/test/UpdateVertexTest.cpp
note，update and upsert only handle one tag of vertex and one edgeType
> upsert statement when insert, the condition is always true  NG-99

- third-party/CMakeLists.txt
- third-party/externals/rocksdb.cmake
> Build RocksDB with LZ4 and BZip2

- src/tools/db-dump/DbDumper.cpp
> Fix db dump.

- src/common/filter/FunctionManager.cpp
> Fix warnings in GCC 10.1

- src/kvstore/RocksEngineConfig.cpp
Disable block cache if `FLAGS_rocksdb_block_cache <= 0`
> Support to disable block cache

- etc/nebula-storaged.conf.default
- etc/nebula-storaged.conf.production
- src/kvstore/RocksEngineConfig.cpp
- src/kvstore/RocksEngineConfig.h
- src/kvstore/test/RocksEngineConfigTest.cpp
This PR requires the third party updated.
> Support to config compression algorithm

- src/graph/SchemaHelper.cpp
- src/graph/ShowExecutor.cpp
- src/graph/test/IndexTest.cpp
- src/graph/test/SchemaTest.cpp
- src/graph/test/TTLTest.cpp
> Fix show create can't execute

- src/jni/CMakeLists.txt
- src/tools/native-client/CMakeLists.txt
- src/tools/native-client/pom.xml
Added missing dependencies and `--no-undefined` option.
> Fixed build of native client

- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
Found it during chaos testing.
> Failed to stop storaged forever if try to stop it before kvstore inited

- src/common/stats/StatsManager.cpp
- src/common/stats/test/StatsManagerTest.cpp
`curl -G "http://127.0.0.1:13070/get_stats"` include p99
> Support StatsManager::readAllValue include p99

- src/storage/test/AddAndUpdateVertexAndEdgeBenchmark.cpp
update insert and update vertex and edge benchmark
> update benckmark result

- etc/nebula-metad.conf.production
- etc/nebula-storaged.conf.default
- etc/nebula-storaged.conf.production
- kubernetes/helm/templates/configmap.yaml
- src/kvstore/RocksEngineConfig.cpp
> set rocksdb_disable_wal to false by default

- package/package.sh
> Fixed a bug in the packaging script.

- src/kvstore/RocksEngineConfig.cpp
If many sub dir is used in the storaged process, a total limiter is required.
> compaction threads/rate limiter

- src/kvstore/NebulaStore.cpp
Fix bugs, the following logic never happens.
https://github.com/vesoft-inc/nebula/blob/09e74ea1cebf51b80b4d18b042471d0e2f9a2727/src/kvstore/NebulaStore.cpp#L108-L112
> fix remove duplicate part in a host

- src/meta/MetaServiceUtils.cpp
- src/meta/MetaServiceUtils.h
- src/meta/processors/admin/AdminClient.cpp
- src/meta/processors/admin/AdminClient.h
- src/meta/processors/admin/CreateSnapshotProcessor.cpp
- src/meta/processors/admin/SnapShot.cpp
- src/meta/processors/admin/SnapShot.h
- src/meta/test/AdminClientTest.cpp
1,  Fixed checkpoint bug. 
2, Refused to create snapshot when index rebuilding.
> Fixed bug of snapshot from chaos test.

- src/storage/query/ScanEdgeProcessor.cpp
- src/storage/query/ScanVertexProcessor.cpp
We just return all data if enable_multi_versions is false.
> fix scan don't return result after add enable_multi_versions

- src/interface/raftex.thrift
- src/kvstore/raftex/Host.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
Reverts vesoft-inc/nebula#2297. @sherman-the-tank, will modify according to discussion.
> Revert "Remove proposed term in raft election"

- src/graph/ShowExecutor.cpp
As show hosts col(Leader distribution) not shown in order, the different row may have the different orders. It is human-readable to make it display in order.
> show hosts in order.

- src/graph/test/DeleteVerticesTest.cpp
- src/graph/test/FetchEdgesTest.cpp
- src/graph/test/GoTest.cpp
- src/graph/test/GroupByLimitTest.cpp
- src/graph/test/SetTest.cpp
- src/graph/test/TraverseTestBase.h
- src/graph/test/YieldTest.cpp
add rank field to the test case
Avoid covering multiple edges of the same type
no
no
Comparison with 2.0 test cases
> add edge rank & fix test case

- src/graph/test/IndexTest.cpp
- src/storage/BaseProcessor.inl
This bug from discuss: 
https://discuss.nebula-graph.com.cn/t/topic/1209
Repeat steps： 
CREATE SPACE alter_space(partition_num=1, replica_factor=1)
USE alter_space
CREATE TAG alter_tag(id int)
CREATE TAG INDEX alter_index ON alter_tag(id)
INSERT VERTEX alter_tag(id) VALUES 100:(1), 200:(2)
ALTER TAG alter_tag ADD (type int)
LOOKUP ON alter_tag WHERE alter_tag.id == 1 YIELD alter_tag.type
> fixed error for lookup after alter tag add column

- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/raftex/RaftPart.h
Forget the original logic,  just focus on the new one. 
The heart logic is we will use 2PC to do election,  otherwise we can't have a totally correct one.
> [RAFT] Refactor leader election logic

- src/common/utils/NebulaKeyUtils.h
- src/graph/LookupExecutor.cpp
- src/graph/LookupExecutor.h
- src/graph/test/IndexTest.cpp
- src/graph/test/LookupTest.cpp
- src/graph/test/LookupTestBase.h
- src/graph/test/TestEnv.h
- src/storage/BaseProcessor.h
- src/storage/index/IndexExecutor.h
- src/storage/index/IndexExecutor.inl
- src/storage/index/IndexPolicyMaker.cpp
- src/storage/index/IndexPolicyMaker.h
- src/storage/test/IndexScanTest.cpp
Disable range scan for string type index. 
Disable contains relational expression in lookup.
> To improve index scan logic since string range scan disabled.

- src/graph/FetchVerticesExecutor.cpp
- src/graph/test/DataTest.cpp
> Fix fetch * return wrong result when the vertex with empty props tag

- src/graph/GoExecutor.cpp
- src/graph/GoExecutor.h
- src/graph/test/GoTest.cpp
https://github.com/vesoft-inc/nebula/issues/2385
All test cases passed
> Fix go n-hop query hanging, and graphd takes up too much memory util OOM 

- third-party/externals/libevent.cmake
- third-party/install-third-party.sh
> Add prebuilt third party for Glibc 2.30 and 2.32

- third-party/CMakeLists.txt
> Fixed third party build on Ubuntu 20.10

- third-party/CMakeLists.txt
> Fix core number dectection in AArch64

- src/graph/test/DataTest.cpp
- src/storage/query/QueryBaseProcessor.inl
The problem comes from https://discuss.nebula-graph.com.cn/t/topic/2245/11
> Fix only get dst with filter push down and max_edge_returned_per_vertex config

- src/graph/test/GoTest.cpp
- src/graph/test/GroupByLimitTest.cpp
- src/parser/parser.yy
Fix limit/offset, Similar to [https://github.com/vesoft-inc/nebula-graph/pull/542](https://github.com/vesoft-inc/nebula-graph/pull/542)
> fix limit/offset

- README-CN.md
- README.md
> comment out roadmap

- src/common/process/ProcessUtils.cpp
from https://discuss.nebula-graph.com.cn/t/topic/3041
> Fix build error under g++ 9.3.0

- README.md
- cmake/ThriftGenerate.cmake
- package/CMakeLists.txt
- package/package.sh
> Fix package script

- .github/workflows/pull_request.yml
- docker/Dockerfile
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
Fix storage and meta rpm package path when build docker image
> Fix Dockerfiles for building docker images

- docker/README.md
- src/README.md
- src/clients/graph/README.md
- src/codec/README.md
- src/common/utils/README.md
- src/daemons/README.md
- src/interface/README.md
- src/kvstore/README.md
- src/kvstore/raftex/README.md
- src/meta/README.md
- src/parser/README.md
- src/parser/test/fuzzing/README.md
These README files is meaningless, so cleanup them.
> Delete useless README files

- .clang-format
- .github/workflows/pull_request.yml
- CMakeLists.txt
- src/common/datatypes/DataSetOps-inl.h
- src/common/datatypes/DateOps-inl.h
- src/common/datatypes/EdgeOps-inl.h
- src/common/datatypes/HostAddrOps-inl.h
- src/common/datatypes/KeyValueOps-inl.h
- src/common/datatypes/ListOps-inl.h
- src/common/datatypes/MapOps-inl.h
- src/common/datatypes/PathOps-inl.h
- src/common/datatypes/SetOps-inl.h
- src/common/datatypes/VertexOps-inl.h
- src/common/graph/AuthResponseOps-inl.h
- src/common/graph/ExecutionResponseOps-inl.h
- src/common/graph/PairOps-inl.h
- src/common/graph/PlanDescriptionOps-inl.h
- src/common/graph/PlanNodeBranchInfoOps-inl.h
- src/common/graph/PlanNodeDescriptionOps-inl.h
- src/common/graph/ProfilingStatsOps-inl.h
Use the env variable inside the dev container
depends on https://github.com/vesoft-inc/nebula-dev-docker/pull/55
> Upgrade clang from 9.0.0 to 10.0.0

- conf/CMakeLists.txt
- scripts/CMakeLists.txt
- src/graph/context/ExecutionContext.h
Fix the missing metad configure files.
> Install metad configure files

- src/codec/NebulaCodecImpl.cpp
- src/codec/NebulaCodecImpl.h
- src/codec/include/NebulaCodec.h
- src/codec/test/NebulaCodecTest.cpp
- src/kvstore/plugins/hbase/HBaseStore.cpp
- src/kvstore/plugins/hbase/test/CMakeLists.txt
- src/meta/test/CMakeLists.txt
We have replaced dataman with codec, but the namespace has not been updated.
> Fix codec namespace

- src/common/datatypes/Value.cpp
- src/common/datatypes/test/ValueTest.cpp
- tests/tck/features/expression/function/TypeConversion.feature
> Fix parsing scientific notation string and add UTs

- tests/requirements.txt
To make sec-scan happy, related CVE are:
- CVE-2017-18342
- CVE-2020-1747
- CVE-2020-14343
- CVE-2019-20477
context: https://discuss.nebula-graph.com.cn/t/topic/5328
> Test Dep PyYAML update

- tests/tck/features/fetch/FetchVertices.intVid.feature
- tests/tck/features/fetch/FetchVertices.strVid.feature
Add failed piped fetch clause test case.
close https://github.com/vesoft-inc/nebula-graph/pull/1341
> add failed piped fetch clause test case

- src/clients/meta/MetaClient.cpp
- src/interface/common.thrift
- src/meta/processors/job/GetStatsProcessor.cpp
> improve show stats display when stats info is empty

- src/meta/processors/BaseProcessor-inl.h
- src/storage/StorageServer.cpp
- src/storage/StorageServer.h
> Reduce unnecessary reading and Typo

- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- tests/common/utils.py
1. Upgrade checkout action
2. update docker `nightly/latest` tag
3. Rename clang compiler
4. Fix docker buildx action default context
> Update GitHub action workflow 

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- tests/tck/conftest.py
When there are many jobs in the queue, waiting for 30s is not enough
> Update wait time according to number of current running or queue jobs

- CMakeLists.txt
> Fix nightly pkg name.

- README-CN.md
> Fix HomePage Link to "官网"

- src/daemons/CMakeLists.txt
> remove redundant code

- tests/tck/job/Job.feature
> Fix job test.

- .github/workflows/pull_request.yml
- cmake/nebula/GeneralCompilerConfig.cmake
- tests/requirements.txt
1. https://github.com/vesoft-inc/nebula-dev-docker/pull/57, waiting for this pr merged.
2. need to verify codecov.io no need token via github action.
> add code coverage

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/executor/Executor.cpp
- src/graph/executor/admin/SpaceExecutor.cpp
- src/graph/executor/admin/SpaceExecutor.h
- src/graph/planner/plan/Admin.cpp
- src/graph/planner/plan/Admin.h
- src/graph/planner/plan/PlanNode.cpp
- src/graph/planner/plan/PlanNode.h
- src/graph/service/PermissionCheck.cpp
- src/graph/validator/AdminValidator.cpp
- src/graph/validator/AdminValidator.h
- src/graph/validator/Validator.cpp
- src/interface/meta.thrift
- src/meta/CMakeLists.txt
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/processors/parts/CreateSpaceAsProcessor.cpp
- src/meta/processors/parts/CreateSpaceAsProcessor.h
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
- tests/common/types.py
- tests/conftest.py
- tests/tck/conftest.py
- tests/tck/features/schema/CreateSpaceAs.feature
like create table as ... 
create a new space as an existing one.
create space <new_space_name> as <old_space_name>, tag, edge and index will also be created. 
this will generate meta only.
```
(root@nebula) [(none)]> create space ldbc2 as ldbc_snb_sf10
Execution succeeded (time spent 11777/12414 us)
Tue, 31 Aug 2021 15:03:59 CST
```
> support create space as

- src/meta/processors/zone/ListZonesProcessor.cpp
```
(root@nebula) [(none)]> show zones
+------+------+------+
| Name | Host | Port |
+------+------+------+
| "z1" | ""   | 0    |
+------+------+------+
Got 1 rows (time spent 2930/3752 us)
Mon, 27 Sep 2021 08:11:04 CST
```
> Enhance show zones without hosts

- tests/tck/features/schema/CreateSpaceAs.feature
wait for storage heartbeat.
fix https://github.com/vesoft-inc/nebula/runs/3736018053?check_suite_focus=true
> [tck] wait for storage schema

- src/clients/storage/GraphStorageClient.cpp
- src/clients/storage/GraphStorageClient.h
- src/graph/executor/query/GetNeighborsExecutor.cpp
- src/graph/executor/query/IndexScanExecutor.cpp
- src/graph/planner/plan/ExecutionPlan.h
- src/interface/storage.thrift
- src/storage/BaseProcessor.h
- src/storage/StorageFlags.cpp
- src/storage/StorageFlags.h
- src/storage/index/LookupProcessor.cpp
- src/storage/mutate/UpdateEdgeProcessor.cpp
- src/storage/query/GetNeighborsProcessor.cpp
- src/tools/storage-perf/StoragePerfTool.cpp
Use profile flag in RPC request instead of gflags![image](https://user-images.githubusercontent.com/22708345/135235553-b4159709-8d71-449e-923f-3122f3e73297.png)
> improve storage profiling

- src/graph/service/GraphService.cpp
- src/graph/service/PermissionCheck.cpp
- src/graph/service/PermissionCheck.h
related the new feature for cloud user and nebula native user. issue #2911 .
Please hold this PR. we need both front-end and back-end debugging.
> Support cloud user and nebula native user can be mixed

- CMakeLists.txt
- src/common/geo/io/CMakeLists.txt
fix https://github.com/vesoft-inc/nebula/issues/2990
> fix the bug of can't find auto generated header file

- src/version/Version.cpp.in
This bug will fail the nightly package workflow.
> Fix origin version error

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- src/graph/validator/LookupValidator.cpp
- src/graph/validator/test/LookupValidatorTest.cpp
- tests/tck/features/lookup/WithYield.feature
- tests/tck/features/lookup/WithYield.intVid.feature
- third-party/install-cmake.sh
- third-party/install-gcc.sh
- third-party/install-third-party.sh
Reverts vesoft-inc/nebula#3250
> Revert "Cherry pick from master to v2.6.1"

- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
> Limit workflow job concurrency

- tests/Makefile
* Update nebula-python installation
* Add --user to pip install
`
> Update nebula-python installation in the test (#3290)

- .github/workflows/nightly.yml
- .github/workflows/pull_request.yml
Speedup compile time since our runners have been upgraded to more powerful machines.
> Increase the number of jobs at compile time

- tests/Makefile
* Update nebula-python installation
* Add --user to pip install
> Cherry pick：Update nebula-python installation in the test (#3290)

- tests/Makefile
fix https://github.com/vesoft-inc/nebula/issues/3495
> must use the latest nebula-python

- .github/workflows/pull_request.yml
Ninja build tool could speed up nebula compiling
> Use ninja to build project

- cmake/nebula/ThirdPartyConfig.cmake
- third-party/install-third-party.sh
> [SIMPLE] Support installing thrd party 3.0

- src/graph/service/GraphService.cpp
- tests/Makefile
- tests/tck/conftest.py
- tests/tck/features/yield/parameter.feature
Just update the client URL used by TCK After python client support parameters.
> change ci nebula-python url

- .github/pull_request_template.md
Description:
As title.
Please check the grammar and spelling use a spellchecker before submitting PRs that modify comments and descriptions.
Tests:
Affects:
> [Minor] Fix typos in the PR submit template

- src/parser/TraverseSentences.cpp
> fix fetch edges tostring

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
> Disable ARM version docker image since related third party not ready

- src/meta/processors/parts/CreateSpaceProcessor.cpp
> Add more check about parse host result

- src/meta/MetaVersionMan.cpp
> Remove deprecated function calling.

- src/graph/session/GraphSessionManager.cpp
Close https://github.com/vesoft-inc/nebula/issues/3612
Description:
Add return when `metaClient->removeSession()` fails
Tests:
Affects:
> Fix remove session

- src/storage/index/LookupProcessor.cpp
- src/storage/test/LookupIndexTest.cpp
> fix clang compile failed

- src/meta/processors/zone/MergeZoneProcessor.cpp
- src/meta/test/MetaClientTest.cpp
- src/meta/test/ProcessorTest.cpp
> Support more check about merge zone arguments

- src/tools/db-upgrade/NebulaKeyUtilsV3.cpp
> fix upgrade bug

- .github/workflows/pull_request.yml
- src/clients/storage/StorageClientBase-inl.h
- src/common/utils/NebulaKeyUtils.cpp
- src/common/utils/NebulaKeyUtils.h
- src/daemons/CMakeLists.txt
- src/daemons/StandAloneDaemon.cpp
- src/graph/executor/test/StorageServerStub.cpp
- src/graph/validator/MaintainValidator.cpp
- src/kvstore/RocksEngine.cpp
- src/meta/ActiveHostsMan.cpp
- src/meta/processors/parts/CreateSpaceProcessor.cpp
- src/meta/test/ProcessorTest.cpp
- src/storage/GraphStorageLocalServer.cpp
- src/storage/stats/StorageStats.cpp
- src/tools/db-upgrade/DbUpgraderTool.cpp
- tests/Makefile
- tests/common/nebula_service.py
- tests/nebula-test-run.py
- tests/pytest.ini
- tests/tck/features/admin/Authentication.feature
- tests/tck/features/admin/Sessions.feature
https://github.com/vesoft-inc/nebula/pull/3643 has conflicts and requires author cherry pick
1. #3798   
-> #3827 
2. #3807 #3814 
-> #3829 
3. #3776 
-> #3828 
4. #3825 #3822 #3818 #3817 
-> this pr
5. #3643 wait
> Cherry pick v3.0.0 0126-2

- .github/workflows/release.yml
Fix typo to avoid sync error.
Run the container in a non-interactive state
Tests:
Affects:
> Fix image sync issue

- tests/Makefile
- tests/requirements.txt
setuptools upgrading will fail the gherkin feature file format checking.
Tests:
Affects:
> None
> Fix CI feature file format checking failure caused by setuptools upgrading

- src/storage/http/StorageHttpPropertyHandler.cpp
> fix: replace http::// with http://

- tests/tck/features/match/MatchById.IntVid.feature
- tests/tck/features/match/MatchById.feature
> add more testcase

- src/clients/storage/GeneralStorageClient.h
- src/clients/storage/InternalStorageClient.h
- src/clients/storage/StorageClient.h
- src/meta/ActiveHostsMan.h
- src/meta/processors/admin/CreateBackupProcessor.h
- src/meta/processors/admin/CreateSnapshotProcessor.h
- src/meta/processors/admin/DropSnapshotProcessor.h
- src/meta/processors/admin/RestoreProcessor.h
- src/meta/processors/admin/SnapShot.h
- src/storage/query/GetPropProcessor.h
> Remove some useless include instructions

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
> Support the ARM platform of docker image

- tests/tck/ldbc/business_intelligence_workload/Read.feature
- tests/tck/ldbc/interactive_workload/ComplexReads.feature
> Modify ldbc cases.

- src/clients/meta/MetaClient.cpp
> fix issue3215

- .dockerignore
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
- package/package.sh
We need not to build console in docker image
Tests:
Affects:
> Disable console building in docker image

- .github/workflows/rc.yml
- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/planner/match/MatchClausePlanner.cpp
- src/graph/service/GraphService.cpp
- src/graph/service/GraphService.h
- src/graph/service/PasswordAuthenticator.h
- src/tools/db-upgrade/DbUpgrader.cpp
- tests/tck/features/bugfix/CrashWhenNullPathExpr.feature
> Cherry pick v3.0.1

- src/graph/service/GraphService.cpp
This commit was overwritten in the previous PR, thus submit again.
Tests:
Affects:
> [Minor] Update error message

- tests/admin/test_permission.py
- tests/tck/conftest.py
- tests/tck/features/mutate/ClearSpace.feature
Improve test case stability
Tests:
Affects:
> Improve test framework for session usage

- src/graph/service/GraphFlags.h
`local_ip` have defined in line 21
Tests:
Affects:
> remove duplicate flag

- .github/workflows/rc.yml
- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
https://github.com/vesoft-inc/nebula/pull/4080
Tests:
Affects:
> None
> fix docker image version （typo）

- src/clients/meta/MetaClient.cpp
- src/graph/executor/admin/SpaceExecutor.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
- src/meta/processors/zone/AddHostsProcessor.cpp
- src/meta/processors/zone/DropHostsProcessor.cpp
- src/meta/test/BalancerTest.cpp
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- tests/tck/features/schema/Comment.feature
1 replace balance across zone with balance data
replace the zone_list with host_list
2 remove balance in zone
3 add default zones to all space when adding hosts, remove default zones from all space when dropping hosts
Tests:
Affects:
> remove the conception of zone in all place

- src/graph/planner/match/MatchClausePlanner.cpp
- src/graph/planner/match/MatchPlanner.cpp
- src/graph/planner/match/MatchPlanner.h
- src/graph/planner/plan/Logic.cpp
- src/graph/planner/plan/Logic.h
- tests/tck/features/match/MultiLineMultiQueryParts.feature
close https://github.com/vesoft-inc/nebula/issues/4069
Tests:
Affects:
> fix multiple match

- src/graph/service/GraphService.cpp
- src/graph/session/GraphSessionManager.cpp
Fix https://github.com/vesoft-inc/nebula/issues/4152
Tests:
Affects:
> fix issue 4152

- src/storage/mutate/AddVerticesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.h
> Cherry pick v3.1.0 (0422-0423) 

- src/common/base/Arena.cpp
- src/common/base/Arena.h
- src/common/base/test/ArenaBenchmark.cpp
- src/common/base/test/ArenaTest.cpp
- src/common/id/CMakeLists.txt
- tests/tck/features/bugfix/VariableExpression.feature
Fix the license header, The CI to check it seems don't works, I will check it later.
Tests:
Affects:
> Fix the license header.

- src/graph/service/GraphService.cpp
> Fix cloud auth

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- tests/admin/test_show_hosts.py
enhance workflow
1. do not use `matrix` when build docker, so it could use docker cache.
2. build package first, and then build docker images.
3. when running rc workflow, download package from OSS, no need to build again
> enhance docker and rc

- .github/workflows/rc.yml
fix rc docker image
Tests:
Affects:
> fix rc docker

- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/984
Tests:
Affects:
> add stats under index condition

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
- src/common/base/ObjectPool.h
- src/daemons/MetaDaemon.cpp
- src/daemons/StandAloneDaemon.cpp
- src/graph/executor/algo/BatchShortestPath.cpp
- src/graph/executor/algo/ShortestPathBase.cpp
- src/graph/executor/algo/ShortestPathBase.h
- src/graph/executor/algo/SingleShortestPath.cpp
- src/graph/optimizer/rule/CollapseProjectRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformAppendVerticesLimitRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformRule.cpp
- src/graph/optimizer/rule/GetEdgesTransformUtils.h
- src/meta/RootUserMan.h
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/test/GetStatsTest.cpp
- src/meta/test/JobManagerTest.cpp
- src/storage/mutate/AddEdgesProcessor.cpp
- src/storage/mutate/AddVerticesProcessor.cpp
- src/webservice/GetFlagsHandler.cpp
- src/webservice/GetStatsHandler.cpp
- src/webservice/Router.cpp
- src/webservice/SetFlagsHandler.cpp
- src/webservice/StatusHandler.cpp
> Cherry pick v3.2.0 (0616-0627)

- src/graph/executor/algo/ShortestPathBase.cpp
> fix_multithread_bug

- .github/workflows/nightly.yml
- src/graph/context/Iterator.cpp
- src/graph/context/Iterator.h
- src/graph/executor/Executor.cpp
- src/graph/executor/Executor.h
- src/graph/executor/query/AppendVerticesExecutor.cpp
- src/graph/executor/query/AppendVerticesExecutor.h
- src/graph/executor/query/FilterExecutor.cpp
- src/graph/executor/query/FilterExecutor.h
- src/graph/executor/query/InnerJoinExecutor.cpp
- src/graph/executor/query/InnerJoinExecutor.h
- src/graph/executor/query/JoinExecutor.cpp
- src/graph/executor/query/JoinExecutor.h
- src/graph/executor/query/LeftJoinExecutor.cpp
- src/graph/executor/query/LeftJoinExecutor.h
- src/graph/executor/query/ProjectExecutor.cpp
- src/graph/executor/query/ProjectExecutor.h
- src/graph/executor/query/TraverseExecutor.cpp
- src/graph/executor/query/TraverseExecutor.h
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- tests/Makefile
- tests/common/nebula_service.py
- tests/nebula-test-run.py
- tests/tck/features/optimizer/PrunePropertiesRule.feature
Some debug infos.
Multi job AppendVertices handle resp.
Multi job Project.
Enhance AppendVertices.
Multi job filter.
Fix row cnt and delete debug info.
Fix AppendV.
Add debug info.
Rm debug info.
Fix copy in traverse.
Set max_job_size to default 20.
Add runMultiJobs template.
Impl Project/Filter/AppendV.
Impl Join.
Fix double free for join.
Fix filter on GetNeighborsIter.
Fix prop iter.
Fix filter on prop iter.
Fix left join by clearing hash tabls manually.
Report error in filter.
Fix tests: the order is not guarentted in scatter gather model.
Iterates to begin out of job.
Modify the default config.
Fix appendv.
Support run multi job mode test.
Test multi job.
Rebase and compatible with single job.
This pr implements inner parallel processing by using Scatter/Gather model and improves a …
> Implement inner parallel procesing by using Scatter/Gather model.

- .github/workflows/codeql-analysis.yml
The workflow generated by GitHub has a syntax error in the branch section
Tests:
Affects:
> fix syntax errors

- .github/workflows/pull_request.yml
update Check License Header
Tests:
Affects:
> Fix lint build error

- src/kvstore/wal/AtomicLogBuffer.cpp
Enhance memory usage of `AtomicLogBuffer`, when a the log is big enough, it would make the memory usage way more bigger than expected. Because we allow 5 dirty nodes, each node contain 64 log. So if the size of log is 1M, it would occupy 1M * 64 * 5 = 320M memory (and it is only 1 part). 
Usually a single log's size will be trivial, but when rebuild index/sync, we will batch the operations, this will make storage OOM.
When the buffer's size is bigger than expected, try to trigger gc anyway (not only when we have enough dirty node).
Tests:
Affects:
> enhance atomic log buffer memory usage

- .github/workflows/pull_request.yml
- src/graph/executor/admin/SpaceExecutor.cpp
- src/kvstore/raftex/RaftPart.cpp
- src/kvstore/wal/AtomicLogBuffer.cpp
> Cherry pick v3.2.0 (0701-0708)

- resources/gflags.json
- src/clients/meta/MetaClient.cpp
- src/common/meta/GflagsManager.cpp
- src/common/meta/GflagsManager.h
- src/common/time/TimezoneInfo.h
- src/daemons/GraphDaemon.cpp
- src/graph/service/GraphService.cpp
- src/storage/StorageServer.cpp
- tests/admin/test_configs.py
> Cherry pick v3.2.0 (0709-0711)

- .github/workflows/nightly.yml
fix nightly package name
Tests:
Affects:
> enhance night tck testing

- package/package.sh
- src/storage/mutate/DeleteEdgesProcessor.cpp
- src/storage/mutate/DeleteVerticesProcessor.cpp
- src/webservice/SetFlagsHandler.cpp
> Cherry pick 3.2.0 (0712-0713)

- src/meta/processors/job/LeaderBalanceJobExecutor.cpp
> Cherry pick 3.2.0 (0714) 

- tests/tck/features/bugfix/VidInvalidLength.feature
close https://github.com/vesoft-inc/nebula/issues/4415
Tests:
Affects:
> Add simple vid overlength tck

- package/package.sh
add a commit file, no need to verify the git commit in binary file.
> add commit in package

- .github/workflows/codeql-analysis.yml
> code analysis doesn't need to run per PR

- README-CN.md
- README.md
> fixed quick start url

- src/clients/storage/StorageClient.cpp
- src/clients/storage/StorageClient.h
- src/graph/context/ast/QueryAstContext.h
- src/graph/executor/CMakeLists.txt
- src/graph/executor/Executor.cpp
- src/graph/executor/StorageAccessExecutor.cpp
- src/graph/executor/StorageAccessExecutor.h
- src/graph/executor/query/GetDstBySrcExecutor.cpp
- src/graph/executor/query/GetDstBySrcExecutor.h
- src/graph/executor/test/StorageServerStub.cpp
- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/planner/ngql/GoPlanner.h
- src/graph/planner/plan/PlanNode.cpp
- src/graph/planner/plan/PlanNode.h
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- src/graph/validator/test/QueryValidatorTest.cpp
- src/storage/GraphStorageLocalServer.cpp
- src/storage/GraphStorageLocalServer.h
- tests/tck/features/go/SimpleCase.feature
Close https://github.com/vesoft-inc/nebula/issues/4484
Tests:
Affects:
- [ x] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [] Performance impacted: Consumes more CPU/Memory
> optimize multi-hop go stmt

- README-CN.md
- README.md
Add company user cases
None
Tests:
Affects:
doc: add users and cases, optimize format for README
> doc: add users and cases, optimize format for README

- scripts/nebula.service
fix exit code, if something error, the code is 1
Tests:
Affects:
> fix exit code in script

- src/codec/CMakeLists.txt
- src/codec/test/CMakeLists.txt
- src/common/utils/CMakeLists.txt
- src/common/utils/test/CMakeLists.txt
- src/console/CMakeLists.txt
- src/graph/context/CMakeLists.txt
- src/graph/gc/CMakeLists.txt
- src/graph/util/test/CMakeLists.txt
- src/kvstore/CMakeLists.txt
- src/kvstore/plugins/CMakeLists.txt
- src/kvstore/raftex/CMakeLists.txt
- src/kvstore/raftex/test/CMakeLists.txt
- src/kvstore/test/CMakeLists.txt
- src/kvstore/wal/CMakeLists.txt
- src/kvstore/wal/test/CMakeLists.txt
- src/mock/CMakeLists.txt
- src/storage/CMakeLists.txt
- src/storage/test/CMakeLists.txt
- src/tools/CMakeLists.txt
- src/tools/db-dump/CMakeLists.txt
- src/tools/meta-dump/CMakeLists.txt
- src/tools/simple-kv-verify/CMakeLists.txt
- src/tools/storage-perf/CMakeLists.txt
> add copyright header for cmaketxt

- src/storage/mutate/AddVerticesProcessor.cpp
Confirmed with PD, modify the `or` to `and` in #4680.
Tests:
Affects:
> insert vertex key when only vertex and flag is set

- src/graph/context/ast/QueryAstContext.h
- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/planner/ngql/GoPlanner.h
- src/graph/validator/GoValidator.cpp
- src/graph/validator/GoValidator.h
- tests/tck/conftest.py
- tests/tck/features/go/SimpleCase.feature
Close https://github.com/vesoft-inc/nebula/issues/4709
Tests:
Affects:
> Refine go planner

- README-CN.md
- README.md
Revisiting and polishing readme
Tests:
Affects:
> chore: polishing readme

- src/meta/processors/job/DataBalanceJobExecutor.cpp
- src/meta/processors/job/LeaderBalanceJobExecutor.cpp
- src/meta/processors/job/ZoneBalanceJobExecutor.cpp
From https://github.com/vesoft-inc/nebula-ent/issues/1524
add log for some failed job
Tests:
Affects:
> add log for failed plan

- src/graph/executor/algo/IsomorExecutor.cpp
- src/graph/executor/algo/IsomorExecutor.h
> Fix the implementation of isomor executor

- src/storage/query/GetPropProcessor.cpp
- src/storage/test/GetPropTest.cpp
For privilege management implementation. 
Depended by https://github.com/vesoft-inc/nebula-ent/pull/1556
Tests:
Affects:
> Modify edge behavior of rpc interface `getProps`

- src/graph/util/ExpressionUtils.cpp
- tests/tck/features/bugfix/PredicationPushDownInGo.feature
> Fix some filter don't push down project.

- src/meta/test/MockAdminClient.h
- src/storage/exec/UpdateNode.h
Since our googletest/gmock has been upgraded in 3rd-party, so we could use more natural gmock interface.
Lower a log level as well.
Tests:
Affects:
> modify outdated gmock interface

- src/graph/validator/ACLValidator.cpp
- src/graph/validator/ACLValidator.h
- tests/tck/features/bugfix/DropRootUser.feature
Close https://github.com/vesoft-inc/nebula/issues/4879
Tests:
Affects:
> Avoid drop root user.

- .github/workflows/pull_request.yml
> reduce link threads to avoid OOM

- src/graph/executor/logic/ArgumentExecutor.cpp
- src/graph/planner/match/MatchPathPlanner.cpp
> fix argument

- third-party/install-third-party.sh
The third party of nebula has to upgrade to version 3.3, otherwise there are some compile errors when building storage.
change the third party version to 3.3
Tests:
Affects:
> Upgrade third party version to 3.3

- tests/tck/features/match/Unwind.feature
from forum user: https://discuss.nebula-graph.com.cn/t/topic/11717/23
from community user, following use case doesn't execute as expected and will full scan index in nebula 3.3.0. I check the behavior in latest develop branch and it has been fixed. 
Only add the two tests into nebula test suit.
Tests:
Affects:
> More unwind tests from community

- tests/conftest.py
- tests/tck/conftest.py
> support loading the test space in tck.

- src/daemons/MetaDaemon.cpp
- src/meta/MetaServiceHandler.cpp
- src/meta/MetaServiceHandler.h
- src/meta/processors/job/AdminJobProcessor.cpp
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/test/CreateBackupProcessorTest.cpp
- src/meta/test/GetStatsTest.cpp
- src/meta/test/JobManagerTest.cpp
> set adminClient for job manager at the beginning

- src/parser/scanner.lex
- src/parser/test/ScannerTest.cpp
- tests/tck/features/delete/DeleteVertexWithoutEdge.feature
- tests/tck/features/go/SimpleCase.feature
- tests/tck/features/insert/insertVertexOnly.feature
close https://github.com/vesoft-inc/nebula-ent/issues/1796
Tests:
Affects:
> delete unused keyword step

- src/parser/parser.yy
- tests/tck/features/index/Index.feature
- tests/tck/features/schema/Schema.feature
Fix https://github.com/vesoft-inc/nebula-ent/issues/1780
Related pr https://github.com/vesoft-inc/nebula/pull/5126/files
Tests:
Affects:
> forbid zero fixed string

- src/parser/scanner.lex
- src/parser/test/ScannerTest.cpp
- tests/tck/features/delete/DeleteVertexWithoutEdge.feature
- tests/tck/features/go/SimpleCase.feature
- tests/tck/features/insert/insertVertexOnly.feature
Reverts vesoft-inc/nebula#5117
> Revert "delete unused keyword step"

- src/graph/executor/query/TraverseExecutor.cpp
- tests/tck/features/bugfix/MatchNodeLabelFilter.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2064
Tests:
Affects:
> fix match node label

- src/clients/meta/MetaClient.cpp
- src/common/graph/Response.h
- src/common/thrift/ThriftClientManager-inl.h
- src/interface/common.thrift
- src/meta/processors/admin/DropSnapshotProcessor.cpp
- src/meta/test/SnapshotProcessorsTest.cpp
1. drop snapshot not exist will return snapshot not found.
2. remove redundant judgement on thrift client.
Tests:
Affects:
> drop space not exist

- src/meta/processors/job/JobDescription.cpp
- src/meta/processors/job/JobDescription.h
- src/meta/processors/job/JobExecutor.h
- src/meta/processors/job/JobManager.cpp
- src/meta/processors/job/JobManager.h
- src/meta/processors/job/JobStatus.cpp
- src/meta/processors/job/JobStatus.h
- src/meta/test/JobManagerTest.cpp
Add add/stop/recover/show job ut test.
And little fix.
Tests:
Affects:
> modify jobmanager ut

- README-CN.md
- README.md
This readme change pr is to expose stack overflow in a prioritized position and it also polished other badges as aligned with the team. 
Tests:
Affects:
n/a
> chore: community badges refined

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- conf/nebula-storaged.conf.default
- conf/nebula-storaged.conf.production
#5205 
add memtracker flags to conf 
Tests:
Affects:
> add memtracker flags to conf

- src/meta/processors/job/RebuildJobExecutor.cpp
- src/meta/processors/job/StatsJobExecutor.cpp
Stop job return error code use balancer error,which is confusing.
Tests:
Affects:
> fix stop job error code

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- conf/nebula-storaged.conf.default
- conf/nebula-storaged.conf.production
- src/common/memory/MemoryUtils.cpp
> print memory stats default to false

- src/meta/processors/index/FTIndexProcessor.cpp
> fix ft index of fixed string

- src/meta/ActiveHostsMan.cpp
This reverts commit 593bffcbdff0e0c6b32335165c0bce2137af50dd.
Tests:
Affects:
> Revert "do not check term for leader info by default para"

- src/meta/processors/job/StorageJobExecutor.cpp
> fix baton miss reset in StorageJobExecutor

- src/daemons/MetaDaemonInit.cpp
- src/meta/MetaVersionMan.cpp
- src/meta/MetaVersionMan.h
> support upgrade from V2 to V3.4

- src/common/graph/Response.h
- src/graph/planner/plan/PlanNode.h
> Fix the check of query plan nodes

- src/graph/executor/test/JoinTest.cpp
- src/graph/planner/ngql/GoPlanner.cpp
- src/graph/planner/ngql/PathPlanner.cpp
- tests/tck/features/go/GO.feature
Fix https://github.com/vesoft-inc/nebula-ent/issues/2345
Tests:
Affects:
> fix getneighbors edge direction showed in plan

- src/graph/planner/ngql/PathPlanner.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/2530
Tests:
Affects:
> fix path result without prop

- src/clients/meta/MetaClient.h
- src/common/meta/ClusterIdManBase.h
> Add salt when generating cluster id to reduce duplication

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
> Add some graph performance options in configure file

- .github/workflows/nightly.yml
- .github/workflows/rc.yml
> fix miss arg $GITHUB_OUTPUT

- src/graph/optimizer/rule/EmbedEdgeAllPredIntoTraverseRule.cpp
- tests/tck/features/match/MultiLineMultiQueryParts.feature
Fix https://github.com/vesoft-inc/nebula-ent/issues/2620
Subtask of https://github.com/vesoft-inc/nebula/issues/5441
Tests:
Affects:
> Fix edge all predicate with function predicate

- tests/requirements.txt
fixed yapf version to the last version supporting tomli 1.x
Tests:
Affects:
> fixed yapf version 

- src/kvstore/Part.cpp
https://github.com/vesoft-inc/nebula/issues/5320
The meta cleanup forgot to remove system commit id/term.
Tests:
Affects:
> Fix meta's cleanup

- src/graph/executor/StorageAccessExecutor.cpp
- src/graph/executor/algo/AllPathsExecutor.cpp
- src/graph/executor/algo/AllPathsExecutor.h
- tests/tck/features/path/AllPath.feature
> change bfs to bibfs in allpath

- conf/nebula-graphd.conf.default
- conf/nebula-graphd.conf.production
- src/graph/executor/algo/AllPathsExecutor.cpp
> change batch size

- src/common/utils/MetaKeyUtils.cpp
Reverts vesoft-inc/nebula#5573
> Revert "fix cluster id is not backuped"

- .github/workflows/pull_request.yml
* add sccache for speed up build and stoarge cache file into Minio service
Speedup build for all system
Tests:
Affects:
> Change ccache to sccache

- .github/workflows/pull_request.yml
Reverts vesoft-inc/nebula#5610
In order to compile pr5612 first, temporarily revert the pr
> Revert "Change ccache to sccache"

- src/graph/executor/maintain/FTIndexExecutor.cpp
- src/kvstore/listener/elasticsearch/ESListener.cpp
> fix bug of fulltext

- .github/workflows/pull_request.yml
Reverts vesoft-inc/nebula#5613
> Revert "Revert "Change ccache to sccache""

- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/optimizer/PrunePropertiesRule.feature
close https://github.com/vesoft-inc/nebula-ent/issues/2960
Tests:
Affects:
> fix return all user-define variables

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/ProduceAllPathsExecutor.cpp
- src/graph/executor/algo/ProduceAllPathsExecutor.h
> replace collect with collectAll

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.cpp
> fix 3.5 shortest path memory tracker

- src/graph/executor/algo/MultiShortestPathExecutor.cpp
> fix 3.4 shortest path memory tracker

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- src/graph/executor/algo/MultiShortestPathExecutor.cpp
- tests/tck/features/path/ShortestPath.IntVid.feature
- tests/tck/features/path/ShortestPath.feature
> fix 3.4-3.5 shortest bug

- src/graph/executor/admin/ListenerExecutor.cpp
> Consistent with Enterprise Edition

- src/graph/executor/algo/BFSShortestPathExecutor.cpp
- tests/tck/features/path/ShortestPath.feature
- tests/tck/features/path/singleShortestPath.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3088
Tests:
Affects:
> fix shortest_limit

- src/graph/validator/YieldValidator.cpp
- tests/tck/features/yield/join.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3123
Tests:
Affects:
> fix innerjoin bug

- src/parser/parser.yy
- tests/tck/features/yield/join.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3223
Tests:
Affects:
> check illegal join statement

- src/graph/optimizer/rule/EliminateFilterRule.cpp
- src/graph/planner/plan/Query.cpp
- src/graph/planner/plan/Query.h
- tests/tck/features/optimizer/ElimintateInvalidProp.feature
close https://github.com/vesoft-inc/nebula-ent/issues/3264
Tests:
Affects:
> fix empty filter

- src/graph/optimizer/Optimizer.cpp
- src/graph/visitor/PropertyTrackerVisitor.cpp
- src/graph/visitor/PrunePropertiesVisitor.cpp
- tests/tck/features/bugfix/PrunePropertiesError.feature
> fix PrunePropertiesVisitor bug

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/service/GraphService.cpp
- src/meta/test/MetaClientTest.cpp
- src/storage/StorageFlags.cpp
- src/storage/StorageFlags.h
- src/storage/StorageServer.cpp
- src/tools/db-dump/DbDumper.cpp
- src/tools/db-upgrade/DbUpgraderTool.cpp
close https://github.com/vesoft-inc/nebula-ent/issues/3444
dump& update tool will  be affected @MuYiYong 
Tests:
Affects:
> add GFlag handshakeKey for graph & storage

- src/clients/meta/MetaClient.cpp
- src/clients/meta/MetaClient.h
- src/graph/service/GraphFlags.cpp
- src/graph/service/GraphFlags.h
- src/graph/service/GraphService.cpp
- src/meta/test/MetaClientTest.cpp
- src/storage/StorageFlags.cpp
- src/storage/StorageFlags.h
- src/storage/StorageServer.cpp
- src/tools/db-dump/DbDumper.cpp
- src/tools/db-upgrade/DbUpgraderTool.cpp
Reverts vesoft-inc/nebula#5801
> Revert "add GFlag handshakeKey for graph & storage"

- src/common/base/Cord.h
- src/graph/planner/plan/ExecutionPlan.h
Make nebula compilable with gcc-13.2.1 on my Arch Linux
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://b
ugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-fu
nction --enable-gnu-unique-object --enable-libstdcxx-backtrace …
```
> chore: make nebula compilable with gcc13

- src/storage/query/GetNeighborsProcessor.cpp
> fix max edge per vertex

- src/graph/executor/query/ExpandAllExecutor.cpp
- src/graph/executor/query/ExpandExecutor.cpp
- src/graph/planner/plan/Query.h
- tests/tck/features/go/SampleLimit.feature
- tests/tck/features/go/SampleLimit.intVid.feature
- tests/tck/features/optimizer/PushSampleDownRule.feature
> push step limit down storage 

- .github/workflows/release.yml
> Fix release runner

- .github/workflows/release.yml
Update release.yml
Tests:
Affects:
> [Cherry-pick] Fix release runner (#5887)

- README-CN.md
- README.md
- Update to the latest product doc link and fix the DBaaS link
Tests:
Affects:
> [DOC] Update to the latest product doc link and fix the DBaaS link

- CONTRIBUTING.md
Small PR - fixes the `how-to-contribute.md` reference in `CONTRIBUTING.md`.
Fix the reference.
Tests:
Affects:
> Update `how-to-contribute.md` reference

- docker/Dockerfile
- docker/Dockerfile.graphd
- docker/Dockerfile.metad
- docker/Dockerfile.storaged
- docker/Dockerfile.tools
> Switch to non-root container user
